// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui_LoginAndRegiste.h"
#include "ui.h"
#include "ui_helpers.h"
static char selectedid[50] = "内科201室";
static char count[10] = "0";
static char selectedtime[50] = {0};
static char patspath[50] = {0};
static char docID[10];
DL patslist;   // 病患队列
PatsList head; // 医生可以操作的病患队列头指针
// 打开文件
FILE *openfile(const char *path, char *mode)
{
    // 打开文件 获取文件流指针
    FILE *fp = fopen(path, mode);
    if (fp == NULL)
    {
        perror("打开文件失败\n");
        return NULL;
    }
    else
    {
        printf("打开文件成功\n");
        printf("文件流指针：%p\n", fp);
        return fp;
    }
}
// 关闭文件
int closefile(FILE *fp)
{
    // 关闭文件 文件流指针负责关闭
    int ret = fclose(fp);
    if (ret == EOF)
    {
        perror("fclose failed\n");
        return -1;
    }
    else
    {
        printf("关闭文件流成功\n");
    }
}

void close_custom_popup(lv_event_t *e)
{
    lv_obj_t *popup = (lv_obj_t *)lv_event_get_user_data(e);

    if (popup && lv_obj_is_valid(popup))
    {
        lv_obj_del(popup);
    }
}

void show_popup(const char *title, const char *message)
{

    lv_obj_t *popup = lv_obj_create(lv_scr_act());
    lv_obj_set_size(popup, LV_PCT(25), LV_SIZE_CONTENT);
    lv_obj_set_flex_flow(popup, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_style_pad_all(popup, 20, 0);
    lv_obj_center(popup);
    lv_obj_set_style_text_font(popup, &ui_font_CHINESEsize25, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t *title_label = lv_label_create(popup);
    lv_label_set_text(title_label, title);
    lv_obj_set_style_text_font(title_label, &lv_font_montserrat_16, 0);
    lv_obj_set_style_text_font(title_label, &ui_font_CHINESEsize25, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t *msg_label = lv_label_create(popup);
    lv_label_set_text(msg_label, message);
    lv_label_set_long_mode(msg_label, LV_LABEL_LONG_WRAP);
    lv_obj_set_width(msg_label, LV_PCT(100));

    lv_obj_t *close_btn = lv_btn_create(popup);
    lv_obj_set_size(close_btn, 30, 30);
    lv_obj_align(close_btn, LV_ALIGN_TOP_RIGHT, 0, 0);
    lv_obj_set_style_radius(close_btn, 5, 0);
    lv_obj_set_style_bg_color(close_btn, lv_color_white(), 0);

    lv_obj_t *x_label = lv_label_create(close_btn);
    lv_label_set_text(x_label, "X");
    lv_obj_center(x_label);
    lv_obj_set_style_text_color(x_label, lv_color_black(), 0);

    lv_obj_add_event_cb(close_btn, close_custom_popup, LV_EVENT_CLICKED, popup);
}

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_guahaoWin
void ui_event_select_id(lv_event_t *e);
void ui_guahaoWin_screen_init(void);
lv_obj_t *ui_guahaoWin;
lv_obj_t *ui_Container1;
lv_obj_t *ui_TabView1;
lv_obj_t *ui_yiceng;
lv_obj_t *ui_ceng1Panel;
lv_obj_t *ui_DocPanelCeng1;
lv_obj_t *ui_GHdocImageCeng1;
lv_obj_t *ui_GHdocnameCeng1;
lv_obj_t *ui_GHceng1countContainerCeng1;
lv_obj_t *ui_GHdzzLabelCeng2;
lv_obj_t *ui_GHdzzLabelCeng1;
lv_obj_t *ui_GHcountLabelCeng1;
lv_obj_t *ui_ImageCeng1;
lv_obj_t *ui_LabelselectCeng1;
lv_obj_t *ui_RollerTimeCeng1;
lv_obj_t *ui_ButtonCeng1;
lv_obj_t *ui_RollerCeng1;
lv_obj_t *ui_erceng;
lv_obj_t *ui_ceng2Panel;
lv_obj_t *ui_ceng2DocPanel;
lv_obj_t *ui_GHdocImage2;
lv_obj_t *ui_GHdocnameCeng2;
lv_obj_t *ui_GHceng1countContainerCeng2;
lv_obj_t *ui_GHdaizhenzhongLabelCeng2;
lv_obj_t *ui_GHdzzLabelCeng3;
lv_obj_t *ui_GHcountLabelCeng2;
lv_obj_t *ui_ImageCeng2;
lv_obj_t *ui_LabelselectCeng2;
lv_obj_t *ui_RollerTimeCeng2;
lv_obj_t *ui_ButtonCeng2;
lv_obj_t *ui_Rollerceng2;
lv_obj_t *ui_guahaohead;
lv_obj_t *ui_fanhuiditu123;
lv_obj_t *ui_jiuxuanyiliao1;
lv_obj_t *ui_JXYLguahao;
lv_obj_t *ui____initial_actions0;
void ui_event_gotoGuaHaoWin(lv_event_t *e);
void ui_event_gotoditu123(lv_event_t *e);
void ui_event_button_tijiao(lv_event_t *e);
const lv_img_dsc_t *ui_imgset_ditu[2] = {&ui_img_ditu1_png, &ui_img_ditu234_png};
const lv_img_dsc_t *ui_imgset_style[1] = {&ui_img_style1_png};

void ui_event_button_tijiao(lv_event_t *e)
{
    DBG_MSG("ui_event_button_tijiao");
    lv_event_code_t event_code = lv_event_get_code(e);
    DBG_MSG("event_code: %d", event_code);
    lv_obj_t *target = lv_event_get_target(e);
    DBG_MSG("target: %p", target);
    if (lv_event_get_code(e) == LV_EVENT_SHORT_CLICKED)
    {
        DBG_PRINT();

        DBG_PRINT();
        const char *msg = (const char *)lv_event_get_user_data(e);
        DBG_PRINT();

        DBG_MSG("提交的预约时间：   %s", selectedtime);
        DBG_MSG("提交的预约科室门牌号：     %s", selectedid);
        DBG_MSG("提交的预约科室医生编号路径：     %s", patspath);
        /*
                int num;
                char path[10];
                sscanf(selectedid, "%*[^0-9]%d", &num);
                sprintf(path, "docsTXT/%d.txt", num);

                DBG_MSG("路径: 医生path = %s\n", path);
         */

        DBG_MSG("登录用户信息: 姓名:%s  身份证:%s  身份: %d   \n",
                LoginUserinfo.username, LoginUserinfo.idcard, LoginUserinfo.role);

        FILE *fp = openfile(patspath, "a");

        char input[50];
        int len = strlen(LoginUserinfo.idcard);

        snprintf(input, sizeof(input), "\n%s...%c%c%c%c",
                 LoginUserinfo.username,
                 LoginUserinfo.idcard[len - 4],
                 LoginUserinfo.idcard[len - 3],
                 LoginUserinfo.idcard[len - 2],
                 LoginUserinfo.idcard[len - 1]);

        // 写入文件
        fprintf(fp, "%s\n", input);
        fflush(fp);
        fclose(fp);

        // 入队
        inD(patslist, input);

        char syspath[50] = {0};
        sprintf(syspath, "cat %s", patspath);
        system(syspath);
        DBG_MSG("count%s", count);
        int newcount = atoi(count);
        newcount++;
        char new_count[10];
        sprintf(new_count, "%d", newcount);
        lv_label_set_text(ui_GHcountLabelCeng1, new_count);
        lv_label_set_text(ui_GHcountLabelCeng2, new_count);
        DBG_PRINT();
    }
}

void ui_event_select_time(lv_event_t *e)
{
    DBG_MSG("ui_event_select_time");
    lv_event_code_t event_code = lv_event_get_code(e);
    DBG_MSG("event_code: %d", event_code);
    lv_obj_t *target = lv_event_get_target(e);
    DBG_MSG("target: %p", target);
    if (lv_event_get_code(e) == LV_EVENT_VALUE_CHANGED)
    {
        DBG_PRINT();

        DBG_PRINT();
        const char *msg = (const char *)lv_event_get_user_data(e);
        DBG_PRINT();
        if (strcmp(msg, "1") == 0)
        {
            DBG_PRINT();
            lv_roller_get_selected_str(ui_RollerTimeCeng1, selectedtime, sizeof(selectedtime));
        }
        else
        {
            DBG_PRINT();
            lv_roller_get_selected_str(ui_RollerTimeCeng2, selectedtime, sizeof(selectedtime));
        }

        DBG_MSG("选中时间：%s", selectedtime);
        DBG_MSG("选中科室门牌号：%s", selectedid);
    }
}

char *show_guahaoinfo(const char *msg)
{

    char path[10];
    int num;
    if (sscanf(selectedid, "%*[^0-9]%d", &num) == 1)
    {
        DBG_PRINT();
        sprintf(path, "docsTXT/%d.txt", num);
        printf("医生路径: path = %s\n", path);
        DBG_PRINT();
        char DOCname[20] = {0};
        char DOCid[20] = {0};
        DBG_PRINT();
        FILE *DOCfp = openfile(path, "r");
        fgets(DOCname, sizeof(DOCname), DOCfp); // 医生姓名
        lv_label_set_text(ui_GHdocnameCeng1, DOCname);
        lv_label_set_text(ui_GHdocnameCeng2, DOCname);
        DBG_MSG("DOCname : %s    ", DOCname);
        DBG_PRINT();
        fgets(DOCid, sizeof(DOCname), DOCfp); // 医生编号
        DOCid[strcspn(DOCid, "\r\n")] = '\0';

        sprintf(patspath, "patsTXT/%s.txt", DOCid);
        DBG_MSG("DOCid : %s    ", DOCid);
        DBG_MSG("路径: 病患path = %s\n", patspath);
        FILE *patsp = openfile(patspath, "r");

        DBG_PRINT();

        DBG_PRINT();
        char patspname[50] = {0};
        DBG_PRINT();
        clearD(patslist);
        while (feof(patsp) == 0)
        {
            DBG_PRINT();

            fgets(patspname, sizeof(patspname), patsp);
            DBG_MSG("病患信息: %s", patspname);
            if (strlen(patspname) == "pm")
                continue;
            inD(patslist, patspname);
            DBG_PRINT();
        }

        DBG_PRINT();
        sprintf(count, "%d", patslist->length);
        DBG_PRINT();
        return count;
    }
    else
    {
        DBG_MSG("默认科室selectedid:%s", selectedid);

        printf("路径获取失败\n");
    }
}

void ui_event_select_id(lv_event_t *e)
{
    DBG_MSG("ui_event_select_id");
    lv_event_code_t event_code = lv_event_get_code(e);
    DBG_MSG("event_code: %d", event_code);
    lv_obj_t *target = lv_event_get_target(e);
    DBG_MSG("target: %p", target);
    const char *msg = (const char *)lv_event_get_user_data(e);

    if (lv_event_get_code(e) == LV_EVENT_VALUE_CHANGED)
    {
        DBG_PRINT();
        if (strcmp(msg, "1") == 0)
        {
            DBG_PRINT();
            lv_roller_get_selected_str(ui_RollerCeng1, selectedid, sizeof(selectedid));
        }
        else
        {
            DBG_PRINT();
            lv_roller_get_selected_str(ui_Rollerceng2, selectedid, sizeof(selectedid));
        }

        DBG_MSG("选中科室：%s", selectedid);
        char *count = show_guahaoinfo(msg);
        if ((strcmp(msg, "1") == 0))
        {

            DBG_MSG("count:   %s", count);
            lv_label_set_text(ui_GHcountLabelCeng1, count);
            DBG_MSG("ui_GHcountLabelCeng1:  %s", ui_GHcountLabelCeng1);
        }
        else
        {
            DBG_MSG("count:   %s", count);
            lv_label_set_text(ui_GHcountLabelCeng2, count);
            DBG_MSG("ui_GHcountLabelCeng2:  %s", ui_GHcountLabelCeng2);
        }
    }
}
///////////////////// VARIABLES ////////////////////

// SCREEN: ui_doctorWin
void ui_doctorWin_screen_init(void);
lv_obj_t *ui_doctorWin;
lv_obj_t *ui_doctorHead;
lv_obj_t *ui_head;
lv_obj_t *ui_fanhui_goWINditu123;
void ui_event_gotoditu123(lv_event_t *e);
lv_obj_t *ui_time;
lv_obj_t *ui_jiuxuanyiliao;
lv_obj_t *ui_JXYLzyk;
lv_obj_t *ui_JXYLkfk;
lv_obj_t *ui_JXYLnk;
lv_obj_t *ui_JXYLwk;
lv_obj_t *ui_doctorinfo;
lv_obj_t *ui_doctorPNG;
void ui_event_doctorPNG1(lv_event_t *e);
lv_obj_t *ui_doctorPNG1;
lv_obj_t *ui_Image3;
lv_obj_t *ui_doctorgaishu;
lv_obj_t *ui_shanchangINFO;
lv_obj_t *ui_shanchang;
lv_obj_t *ui_keshiIDlabel;
lv_obj_t *ui_zhiweiLabel;
lv_obj_t *ui_jianjieANDhouzhen;
lv_obj_t *ui_DOCjianjie;
lv_obj_t *ui_dctXiangxijieshaoContainer;
lv_obj_t *ui_doctorxiangxijieshao;
lv_obj_t *ui_DOCxiangxijieshaoText;
lv_obj_t *ui_houzhenqu;
lv_obj_t *ui_daizhenzhong;
lv_obj_t *ui_daizhenzhongText;
lv_obj_t *ui_AMandPM;
lv_obj_t *ui_AMlist;
lv_obj_t *ui_AMbinghuanlist;
lv_obj_t *ui_AMtime;
lv_obj_t *ui_PMlist;
lv_obj_t *ui_PMbinghuanlist;
lv_obj_t *ui_PMtime;
lv_obj_t *ui_jiuzhenzhong;
lv_obj_t *ui_jiuzhenzhongText;
lv_obj_t *ui_binghuanNAME;
lv_obj_t *ui_binghuanNAMElabel;
lv_obj_t *ui_JINGAOlabel;
lv_obj_t *ui_huhuanzhong;
lv_obj_t *ui_huhuanzhongLABEL;
lv_obj_t *ui_tixing;
lv_obj_t *ui_tixingNAME;
lv_obj_t *ui_tixingGOTO;
lv_obj_t *ui_tixingIP;
lv_obj_t *ui_tixingci;
lv_obj_t *ui_jiuzhenzhongDropdown;
lv_obj_t *ui_huhuanzhongDropdown;
void ui_event____initial_actions0(lv_event_t *e);
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 32
#error "LV_COLOR_DEPTH should be 32bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP != 0
#error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

void ui_event_jiuzhenzhongDropdown(lv_event_t *e)
{

    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_VALUE_CHANGED)
    {
        clearHouZhenList(head);
        static char selectres[20];
        lv_dropdown_get_selected_str(ui_huhuanzhongDropdown, selectres, sizeof(selectres));

        if (strcmp(selectres, "-o-") == 0)
        {
            DBG_MSG("点击了 %s", selectres);
            lv_label_set_text(ui_binghuanNAMElabel, "空闲中");
        }
    }
}
void ui_event_huhuanzhongDropdown(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_VALUE_CHANGED)
    {
        clearHouZhenList(head);
        static char selectres[20];
        lv_dropdown_get_selected_str(ui_huhuanzhongDropdown, selectres, sizeof(selectres));

        if (strcmp(selectres, "-o-") == 0)
        {
            DBG_MSG("点击了 %s", selectres);

            char tixinginfo[100] = {0};
            char huhuanzhong_name[50] = {0};
            const char *tixing = lv_label_get_text(ui_tixingNAME);

            if (tixing && tixing[0])
            {
                const char *newline = strchr(tixing, '\n');
                if (newline != NULL)
                {
                    int name_len = newline - tixing;
                    if (name_len >= (int)sizeof(huhuanzhong_name))
                        name_len = sizeof(huhuanzhong_name) - 1;
                    strncpy(huhuanzhong_name, tixing, name_len);
                    huhuanzhong_name[name_len] = '\0';

                    strncpy(tixinginfo, newline + 1, sizeof(tixinginfo) - 1);
                    tixinginfo[sizeof(tixinginfo) - 1] = '\0';
                }
                else
                {
                    strncpy(huhuanzhong_name, tixing, sizeof(huhuanzhong_name) - 1);
                    huhuanzhong_name[sizeof(huhuanzhong_name) - 1] = '\0';
                }
                lv_label_set_text(ui_binghuanNAMElabel, huhuanzhong_name);
            }
            else
            {
                lv_label_set_text(ui_tixingNAME, "");
            }

            const char *amList = lv_label_get_text(ui_AMbinghuanlist);
            char am_names[10][50];
            int am_count = 0;
            char new_am_list[500] = {0};

            if (amList && amList[0])
            {
                DBG_MSG("AM病人列表: %s", amList);
                char buffer[500];
                strncpy(buffer, amList, sizeof(buffer) - 1);
                buffer[sizeof(buffer) - 1] = '\0';

                char temp[50];
                int j = 0;
                for (int i = 0; buffer[i] != '\0'; i++)
                {
                    if (buffer[i] == '\n')
                    {
                        if (j > 0 && am_count < 30)
                        {
                            temp[j] = '\0';
                            strcpy(am_names[am_count++], temp);
                            j = 0;
                        }
                    }
                    else if (j < (int)sizeof(temp) - 1)
                    {
                        temp[j++] = buffer[i];
                    }
                }
                if (j > 0 && am_count < 30)
                {
                    temp[j] = '\0';
                    strcpy(am_names[am_count++], temp);
                }
            }

            if (am_count > 0)
            {
                char newTixing[200];
                snprintf(newTixing, sizeof(newTixing), "%s\n%s", am_names[0], tixinginfo);
                lv_label_set_text(ui_tixingNAME, newTixing);

                for (int i = 1; i < am_count; i++)
                {
                    insertPatsAtTail(head, am_names[i]);
                    if (i > 1)
                        strcat(new_am_list, "\n");
                    strcat(new_am_list, am_names[i]);
                }
                lv_label_set_text(ui_AMbinghuanlist, new_am_list);
            }
            else
            {
                lv_label_set_text(ui_AMbinghuanlist, "");
            }

            insertPatsAtTail(head, "pm");

            const char *pmList = lv_label_get_text(ui_PMbinghuanlist);
            char pm_names[30][50];
            int pm_count = 0;
            char new_pm_list[500] = {0};

            if (pmList && pmList[0])
            {
                DBG_MSG("PM病人列表: %s", pmList);
                char buffer[500];
                strncpy(buffer, pmList, sizeof(buffer) - 1);
                buffer[sizeof(buffer) - 1] = '\0';

                char temp[50];
                int j = 0;
                for (int i = 0; buffer[i] != '\0'; i++)
                {
                    if (buffer[i] == '\n')
                    {
                        if (j > 0 && pm_count < 30)
                        {
                            temp[j] = '\0';
                            strcpy(pm_names[pm_count++], temp);
                            j = 0;
                        }
                    }
                    else if (j < (int)sizeof(temp) - 1)
                    {
                        temp[j++] = buffer[i];
                    }
                }
                if (j > 0 && pm_count < 30)
                {
                    temp[j] = '\0';
                    strcpy(pm_names[pm_count++], temp);
                }
            }

            const char *current_tixing = lv_label_get_text(ui_tixingNAME);
            if (!current_tixing || current_tixing[0] == ' ' || current_tixing[0] == '\0')
            {
                if (pm_count > 0)
                {
                    char newTixing[200];
                    snprintf(newTixing, sizeof(newTixing), "%s\n%s", pm_names[0], tixinginfo);
                    lv_label_set_text(ui_tixingNAME, newTixing);

                    for (int i = 1; i < pm_count; i++)
                    {
                        insertPatsAtTail(head, pm_names[i]);
                        if (i > 1)
                            strcat(new_pm_list, "\n");
                        strcat(new_pm_list, pm_names[i]);
                    }
                    lv_label_set_text(ui_PMbinghuanlist, new_pm_list);
                }
            }
            else
            {
                for (int i = 0; i < pm_count; i++)
                {
                    insertPatsAtTail(head, pm_names[i]);
                }
                lv_label_set_text(ui_PMbinghuanlist, "");
            }

            dispaly(head);

            const char *binghuanNAME = lv_label_get_text(ui_binghuanNAMElabel);
            if (!binghuanNAME || binghuanNAME[0] == '\0')
                binghuanNAME = "空闲中";

            char huhuan_xingming[50] = {0};
            const char *tixing_label = lv_label_get_text(ui_tixingNAME);
            if (tixing_label && tixing_label[0])
            {
                sscanf(tixing_label, "%49[^\n]", huhuan_xingming);
            }

            char full_content[3000] = {0};

            strncat(full_content, binghuanNAME, sizeof(full_content) - strlen(full_content) - 1);
            strcat(full_content, "\n");

            strncat(full_content, huhuan_xingming, sizeof(full_content) - strlen(full_content) - 1);
            strcat(full_content, "\n");

            PatsNode *cur = head->next;
            while (cur != head)
            {
                if (strlen(full_content) + strlen(cur->patsInfo) + 2 < sizeof(full_content))
                {
                    strcat(full_content, cur->patsInfo);
                    strcat(full_content, "\n");
                }
                else
                {
                    break;
                }
                cur = cur->next;
            }

            size_t len = strlen(full_content);
            if (len > 0 && full_content[len - 1] == '\n')
                full_content[len - 1] = '\0';

            char DOCpath[100];
            snprintf(DOCpath, sizeof(DOCpath), "patsTXT/%s.txt", docID);

            FILE *fp = fopen(DOCpath, "w");
            if (fp)
            {
                fputs(full_content, fp);
                fclose(fp);
                DBG_MSG("已保存状态到: %s", DOCpath);
            }
            else
            {
                DBG_MSG("无法写入文件: %s", DOCpath);
            }
        }

        else
        {
            DBG_MSG("点击了 %s", selectres);
            DBG_PRINT();
            char tixinginfo[100] = {0};
            static char huhuanzhong_name[50] = {0};
            const char *tixing = lv_label_get_text(ui_tixingNAME);
            lv_label_set_text(ui_binghuanNAMElabel, "空闲中");
            if (tixing && tixing[0])
            {
                DBG_PRINT();
                const char *newline = strchr(tixing, '\n');
                if (newline != NULL)
                {
                    DBG_PRINT();
                    int name_len = newline - tixing;
                    if (name_len >= (int)sizeof(huhuanzhong_name))
                        name_len = sizeof(huhuanzhong_name) - 1;
                    strncpy(huhuanzhong_name, tixing, name_len);
                    huhuanzhong_name[name_len] = '\0';
                    DBG_PRINT();
                    strncpy(tixinginfo, newline + 1, sizeof(tixinginfo) - 1);
                    tixinginfo[sizeof(tixinginfo) - 1] = '\0';
                }
                else
                {
                    DBG_PRINT();
                    strncpy(huhuanzhong_name, tixing, sizeof(huhuanzhong_name) - 1);
                    huhuanzhong_name[sizeof(huhuanzhong_name) - 1] = '\0';
                }
            }
            else
            {
                DBG_PRINT();
                lv_label_set_text(ui_tixingNAME, "");
            }

            const char *amList = lv_label_get_text(ui_AMbinghuanlist);
            char am_names[10][50];
            int am_count = 0;
            char new_am_list[500] = {0};

            if (amList && amList[0])
            {
                DBG_MSG("AM病人列表: %s", amList);
                char buffer[500];
                strncpy(buffer, amList, sizeof(buffer) - 1);
                buffer[sizeof(buffer) - 1] = '\0';
                DBG_PRINT();
                char temp[50];
                int j = 0;
                for (int i = 0; buffer[i] != '\0'; i++)
                {
                    DBG_PRINT();
                    if (buffer[i] == '\n')
                    {
                        DBG_PRINT();
                        if (j > 0 && am_count < 30)
                        {
                            DBG_PRINT();
                            temp[j] = '\0';
                            strcpy(am_names[am_count++], temp);
                            j = 0;
                        }
                    }
                    else if (j < (int)sizeof(temp) - 1)
                    {
                        DBG_PRINT();
                        temp[j++] = buffer[i];
                    }
                }
                if (j > 0 && am_count < 30)
                {
                    DBG_PRINT();
                    temp[j] = '\0';
                    strcpy(am_names[am_count++], temp);
                }
            }

            if (am_count > 0)
            {
                DBG_PRINT();
                char newTixing[200];
                snprintf(newTixing, sizeof(newTixing), "%s\n%s", am_names[0], tixinginfo);
                lv_label_set_text(ui_tixingNAME, newTixing);

                for (int i = 1; i < am_count; i++)
                {
                    DBG_PRINT();
                    insertPatsAtTail(head, am_names[i]);
                    if (i > 1)
                        strcat(new_am_list, "\n");
                    strcat(new_am_list, am_names[i]);
                }
                lv_label_set_text(ui_AMbinghuanlist, new_am_list);
            }
            else
            {
                DBG_PRINT();
                lv_label_set_text(ui_AMbinghuanlist, "");
            }

            insertPatsAtTail(head, "pm");

            const char *pmList = lv_label_get_text(ui_PMbinghuanlist);
            char pm_names[30][50];
            int pm_count = 0;
            char new_pm_list[500] = {0};

            if (pmList && pmList[0])
            {
                DBG_PRINT();
                DBG_MSG("PM病人列表: %s", pmList);
                char buffer[500];
                strncpy(buffer, pmList, sizeof(buffer) - 1);
                buffer[sizeof(buffer) - 1] = '\0';

                char temp[50];
                int j = 0;
                for (int i = 0; buffer[i] != '\0'; i++)
                {
                    DBG_PRINT();
                    if (buffer[i] == '\n')
                    {
                        DBG_PRINT();
                        if (j > 0 && pm_count < 30)
                        {
                            DBG_PRINT();
                            temp[j] = '\0';
                            strcpy(pm_names[pm_count++], temp);
                            j = 0;
                        }
                    }
                    else if (j < (int)sizeof(temp) - 1)
                    {
                        temp[j++] = buffer[i];
                    }
                }
                if (j > 0 && pm_count < 30)
                {
                    DBG_PRINT();
                    temp[j] = '\0';
                    strcpy(pm_names[pm_count++], temp);
                }
            }

            const char *current_tixing = lv_label_get_text(ui_tixingNAME);

            DBG_PRINT();
            char newTixing[200];
            snprintf(newTixing, sizeof(newTixing), "%s\n%s", pm_names[0], tixinginfo);
            lv_label_set_text(ui_tixingNAME, newTixing);
            DBG_PRINT();
            for (int i = 1; i < pm_count; i++)
            {
                DBG_PRINT();
                insertPatsAtTail(head, pm_names[i]);
                if (i > 1)
                    strcat(new_pm_list, "\n");
                strcat(new_pm_list, pm_names[i]);
            }
            DBG_PRINT();
            char newnew_pm_list[500] = {0};
            sprintf(newnew_pm_list, "%s\n%s", new_pm_list, huhuanzhong_name);
            lv_label_set_text(ui_PMbinghuanlist, newnew_pm_list);

            insertPatsAtTail(head, huhuanzhong_name);
            DBG_PRINT();
            dispaly(head);
            DBG_PRINT();
            const char *binghuanNAME = lv_label_get_text(ui_binghuanNAMElabel);
            if (!binghuanNAME || binghuanNAME[0] == '\0')
                binghuanNAME = "空闲中";
            DBG_PRINT();
            char huhuan_xingming[50] = {0};
            const char *tixing_label = lv_label_get_text(ui_tixingNAME);
            if (tixing_label && tixing_label[0])
            {
                sscanf(tixing_label, "%49[^\n]", huhuan_xingming);
            }
            DBG_PRINT();

            char full_content[3000] = {0};

            strncat(full_content, binghuanNAME, sizeof(full_content) - strlen(full_content) - 1);
            strcat(full_content, "\n");
            DBG_PRINT();
            strncat(full_content, huhuan_xingming, sizeof(full_content) - strlen(full_content) - 1);
            strcat(full_content, "\n");
            DBG_PRINT();
            PatsNode *cur = head->next;
            while (cur != head)
            {
                DBG_PRINT();
                if (strlen(full_content) + strlen(cur->patsInfo) + 2 < sizeof(full_content))
                {
                    DBG_PRINT();
                    strcat(full_content, cur->patsInfo);
                    strcat(full_content, "\n");
                }
                else
                {
                    DBG_PRINT();
                    break;
                }
                cur = cur->next;
            }
            size_t len = strlen(full_content);
            if (len > 0 && full_content[len - 1] == '\n')
                full_content[len - 1] = '\0';
            DBG_PRINT();
            char DOCpath[100];
            snprintf(DOCpath, sizeof(DOCpath), "patsTXT/%s.txt", docID);

            FILE *fp = fopen(DOCpath, "w");
            if (fp)
            {
                DBG_PRINT();
                fputs(full_content, fp);
                fclose(fp);
                DBG_MSG("已保存状态到: %s", DOCpath);
            }
            else
            {
                DBG_MSG("无法写入文件: %s", DOCpath);
            }
        }
    }
}

void ui_event_doctorPNG1(lv_event_t *e)
{
    DBG_MSG("ui_event_doctorPNG1");
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_flag_modify(ui_dctXiangxijieshaoContainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    DBG_PRINT();
}

void ui_event_gotoditu123(lv_event_t *e)
{
    DBG_PRINT();
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_CLICKED)
    {
        lv_disp_load_scr(ui_ditu123);
    }
    DBG_PRINT();
}

void ui_event____initial_actions0(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_SCREEN_LOAD_START)
    {
        _ui_screen_change(&ui_doctorWin, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_doctorWin_screen_init);
    }
}

// SCREEN: ui_LoginRegisteWin
lv_obj_t *ui_errormsg;
lv_obj_t *ui_errorLabel;
void ui_LoginRegisteWin_screen_init(void);
lv_obj_t *ui_LoginRegisteWin;
lv_obj_t *ui_loginBG;
lv_obj_t *ui_LRContainer;
lv_obj_t *ui_LoginRegiste;
lv_obj_t *ui_username;
void ui_event_usernameText(lv_event_t *e);
lv_obj_t *ui_usernameText;
lv_obj_t *ui_usernameLabel;
lv_obj_t *ui_password;
void ui_event_mmText_(lv_event_t *e);
lv_obj_t *ui_mmText_;
lv_obj_t *ui_mmLabel;
void ui_event_mmX(lv_event_t *e);
lv_obj_t *ui_mmX;
void ui_event_mmY(lv_event_t *e);
lv_obj_t *ui_mmY;
lv_obj_t *ui_userIDcard;
void ui_event_userIDcardText_(lv_event_t *e);
lv_obj_t *ui_userIDcardText_;
lv_obj_t *ui_userIDcardLabel;
void ui_event_shenfenChange(lv_event_t *e);
lv_obj_t *ui_shenfenChange;
lv_obj_t *ui_shenfenPanel;
lv_obj_t *ui_shenfenLabel;
void ui_event_shenfen(lv_event_t *e);
lv_obj_t *ui_shenfen;
lv_obj_t *ui_doctorCon;
lv_obj_t *ui_doctorText;
lv_obj_t *ui_LRbutton;
lv_obj_t *ui_denglu;
void ui_event_zhuce(lv_event_t *e);
lv_obj_t *ui_zhuce;
lv_obj_t *ui_loginpng1;
lv_obj_t *ui_loginJINGAO;
void ui_event_jianpanX(lv_event_t *e);
lv_obj_t *ui_jianpanX;
lv_obj_t *ui_jianpan;
lv_obj_t *ui_jianpanPanel;
lv_obj_t *ui_MSGbg;
lv_obj_t *ui_jianpanLabel;
lv_obj_t *ui_TextdocID;
lv_obj_t *ui____initial_actions0;
void ui_event_TextdocIDText(lv_event_t *e);
///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 32
#error "LV_COLOR_DEPTH should be 32bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP != 0
#error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

void ui_event_TextdocIDText(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_flag_modify(ui_jianpanPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_keyboard_set_target(ui_jianpan, ui_TextdocID);
    }
}

void ui_event_usernameText(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_flag_modify(ui_jianpanPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_keyboard_set_target(ui_jianpan, ui_usernameText);
    }
}
void ui_event_mmText_(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    // if(event_code == LV_EVENT_PRESS_LOST) {
    if (event_code == LV_EVENT_CLICKED)
    {

        _ui_flag_modify(ui_jianpanPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_keyboard_set_target(ui_jianpan, ui_mmText_);
    }
}
void ui_event_mmX(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_flag_modify(ui_mmX, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_mmY, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);

        lv_textarea_set_password_mode(ui_mmText_, false);
    }
}
void ui_event_mmY(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_flag_modify(ui_mmY, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_mmX, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        lv_textarea_set_password_mode(ui_mmText_, true);
    }
}
void ui_event_userIDcardText_(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_flag_modify(ui_jianpanPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_keyboard_set_target(ui_jianpan, ui_userIDcardText_);
    }
}
void ui_event_shenfenChange(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_flag_modify(ui_jianpanPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_shenfen(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_VALUE_CHANGED)
    {
        lv_obj_add_flag(ui_jianpanPanel, LV_OBJ_FLAG_HIDDEN); // 隐藏
        // 获取选中的文本
        static char role_buf[20]; // 建议 static 避免栈溢出
        lv_dropdown_get_selected_str(ui_shenfen, role_buf, sizeof(role_buf));

        lv_label_set_text(ui_shenfenLabel, role_buf);

        if (strcmp(role_buf, "普通用户") == 0)
        {
            DBG_PRINT();
            printf("%s\n", role_buf);
            lv_obj_add_flag(ui_jianpanPanel, LV_OBJ_FLAG_HIDDEN); // 隐藏
            lv_obj_add_flag(ui_TextdocID, LV_OBJ_FLAG_HIDDEN);    // 隐藏
        }
        else
        {
            DBG_PRINT();
            printf("%s\n", role_buf);
            lv_obj_clear_flag(ui_jianpanPanel, LV_OBJ_FLAG_HIDDEN);
            lv_obj_clear_flag(ui_TextdocID, LV_OBJ_FLAG_HIDDEN);
        }
    }
}

void ui_event_jianpanX(lv_event_t *e)
{
    DBG_PRINT();
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);

    lv_obj_add_flag(ui_jianpanPanel, LV_OBJ_FLAG_HIDDEN); // 隐藏
}

///////////////////// VARIABLES ////////////////////
// SCREEN: ui_ditu123
void ui_ditu123_screen_init(void);
lv_obj_t *ui_ditu123;
lv_obj_t *ui_DocWinContainer;
lv_obj_t *ui_DocWinTabView;
lv_obj_t *ui_ceng3;
lv_obj_t *ui_ContainerCeng3;
lv_obj_t *ui_shoufutiPanel3;
lv_obj_t *ui_shoufutiX3;
lv_obj_t *ui_shoufutiS3;
lv_obj_t *ui_shoufutiText3;
lv_obj_t *ui_cesuo3;
lv_obj_t *ui_sosContainer3;
lv_obj_t *ui_SOS3;
lv_obj_t *ui_SOSlabel3;
lv_obj_t *ui_kangfukeContainer;
lv_obj_t *ui_keshi5;
lv_obj_t *ui_kangfukeButton306;
lv_obj_t *ui_kangfuke306;
lv_obj_t *ui_kangfukeButton305;
lv_obj_t *ui_kangfuke305;
lv_obj_t *ui_kangfukeButton304;
lv_obj_t *ui_kangfuke304;
lv_obj_t *ui_kangfukeLabel4;
lv_obj_t *ui_kangfuke;
lv_obj_t *ui_neikeContainer1;
lv_obj_t *ui_keshi3;
lv_obj_t *ui_zhongyikeButton303;
lv_obj_t *ui_zhongyikeLabel303;
lv_obj_t *ui_zhongyikeButton302;
lv_obj_t *ui_zhongyikeLabel302;
lv_obj_t *ui_zhongyikeButton301;
lv_obj_t *ui_zhongyikeLabel301;
lv_obj_t *ui_zhongyikeLabel4;
lv_obj_t *ui_neike1;
lv_obj_t *ui_houzhenquPanel3;
lv_obj_t *ui_houzhenqu3;
lv_obj_t *ui_houzhenquLabel3;
lv_obj_t *ui_ceng2;
lv_obj_t *ui_ContainerCeng2;
lv_obj_t *ui_shoufutiPanel2;
lv_obj_t *ui_shoufutiX2;
lv_obj_t *ui_shoufutiS2;
lv_obj_t *ui_shoufutiText2;
lv_obj_t *ui_waikeContainer;
lv_obj_t *ui_keshi1;
lv_obj_t *ui_waikeButton206;
lv_obj_t *ui_waikeLabel206;
lv_obj_t *ui_waikeButton205;
lv_obj_t *ui_waikeLabel205;
lv_obj_t *ui_waikeButton204;
lv_obj_t *ui_waikeLabel204;
lv_obj_t *ui_waike;
lv_obj_t *ui_waikeLabel;
lv_obj_t *ui_sosContainer;
lv_obj_t *ui_SOS;
lv_obj_t *ui_SOSlabel;
lv_obj_t *ui_cesuo2;
lv_obj_t *ui_neikeContainer;
lv_obj_t *ui_keshi2;
lv_obj_t *ui_neikeButton203;
lv_obj_t *ui_neikeLabel203;
lv_obj_t *ui_neikeButton202;
lv_obj_t *ui_neikeLabel202;
lv_obj_t *ui_neikeButton201;
lv_obj_t *ui_neikeLabel1;
lv_obj_t *ui_neikeLabel201;
lv_obj_t *ui_neike;
lv_obj_t *ui_houzhenquPanel2;
lv_obj_t *ui_houzhenqu2;
lv_obj_t *ui_houzhenquLabel2;
lv_obj_t *ui_ceng1;
lv_obj_t *ui_bgContainer;
lv_obj_t *ui_damen;
lv_obj_t *ui_denghouqu1Panel;
lv_obj_t *ui_denghouqu1;
lv_obj_t *ui_Label3;
lv_obj_t *ui_jiaofeichuPanel1;
lv_obj_t *ui_jiaofeiLabel;
lv_obj_t *ui_jiaofei;
lv_obj_t *ui_quyaochu;
lv_obj_t *ui_quyaoLabel;
lv_obj_t *ui_zixunquPanel;
lv_obj_t *ui_zixun1;
lv_obj_t *ui_zixun2;
lv_obj_t *ui_zixun3;
lv_obj_t *ui_zixunquLabel;
lv_obj_t *ui_guahaoPanel;
lv_obj_t *ui_guahaoLabel;
lv_obj_t *ui_guahaoButton;
lv_obj_t *ui_cesuo1;
lv_obj_t *ui_shoufutiPanel1;
lv_obj_t *ui_shoufutiX1;
lv_obj_t *ui_shoufutiS1;
lv_obj_t *ui_shoufutiText1;
lv_obj_t *ui_sosContainer1;
lv_obj_t *ui_SOS1;
lv_obj_t *ui_SOSlabel1;
lv_obj_t *ui_head2;
lv_obj_t *ui_fanhuilogin;
lv_obj_t *ui_dituTIME;
lv_obj_t *ui_jiuxuanyiliao2;
lv_obj_t *ui_JXYLceng1;
lv_obj_t *ui_JXYLceng3;
lv_obj_t *ui_JXYLceng2;
lv_obj_t *ui____initial_actions0;
void ui_event_goWINdoc(lv_event_t *e);
/* void ui_event_goWINdoc202(lv_event_t *e);
void ui_event_goWINdoc203(lv_event_t *e);
void ui_event_goWINdoc204(lv_event_t *e);
void ui_event_goWINdoc205(lv_event_t *e);
void ui_event_goWINdoc206(lv_event_t *e);

void ui_event_goWINdoc301(lv_event_t *e);
void ui_event_goWINdoc302(lv_event_t *e);
void ui_event_goWINdoc303(lv_event_t *e);
void ui_event_goWINdoc304(lv_event_t *e);
void ui_event_goWINdoc305(lv_event_t *e);
void ui_event_goWINdoc306(lv_event_t *e); */
void ui_event_gotologin(lv_event_t *e);
void ui_DocWinTabView_event_handler(lv_event_t *e);
void create_timer();
void update_time(lv_timer_t *timer);

static lv_obj_t *label_time;

void ui_DocWinTabView_event_handler(lv_event_t *e)
{
    lv_event_code_t code = lv_event_get_code(e);
    if (code == LV_EVENT_VALUE_CHANGED)
    {
        int cengID = lv_tabview_get_tab_act(ui_DocWinTabView);

        lv_obj_add_flag(ui_JXYLceng1, LV_OBJ_FLAG_HIDDEN);
        lv_obj_add_flag(ui_JXYLceng2, LV_OBJ_FLAG_HIDDEN);
        lv_obj_add_flag(ui_JXYLceng3, LV_OBJ_FLAG_HIDDEN);

        switch (cengID)
        {
        case 0: // 三层
            lv_obj_clear_flag(ui_JXYLceng3, LV_OBJ_FLAG_HIDDEN);
            break;
        case 1: // 二层
            lv_obj_clear_flag(ui_JXYLceng2, LV_OBJ_FLAG_HIDDEN);
            break;
        case 2: // 一层
            lv_obj_clear_flag(ui_JXYLceng1, LV_OBJ_FLAG_HIDDEN);
            break;
        default:
            lv_obj_clear_flag(ui_JXYLceng1, LV_OBJ_FLAG_HIDDEN);
            break;
        }

        DBG_MSG("切换到楼层索引: %d", (int)cengID);
    }
}
void check_and_update_label(lv_timer_t *timer)
{
    if (ui_GHcountLabelCeng1 != NULL)
    {
        lv_label_set_text(ui_GHcountLabelCeng1, count);
        DBG_MSG("check_and_update_label -> count: %s\n", count);
        lv_timer_del(timer);
    }
    else
    {

        DBG_MSG("Label not ready, waiting...\n");
    }
}
void ui_event_gotoGuaHaoWin(lv_event_t *e)
{
    DBG_MSG("ui_event_gotoGuaHaoWin");
    lv_event_code_t event_code = lv_event_get_code(e);
    DBG_MSG("event_code: %d", event_code);
    lv_obj_t *target = lv_event_get_target(e);
    DBG_MSG("target: %p", target);

    if (lv_event_get_code(e) == LV_EVENT_CLICKED)
    {
        DBG_MSG("跳转挂号界面");
        lv_disp_load_scr(ui_guahaoWin);
        show_guahaoinfo("1");
        DBG_MSG("ui_event_gotoGuaHaoWin ->count:   %s", count);

        lv_timer_create(check_and_update_label, 50, NULL);
    }
}

void ui_event_goWINdoc(lv_event_t *e)
{
    DBG_MSG("ui_event_goWINdoc");
    lv_event_code_t event_code = lv_event_get_code(e);
    DBG_MSG("event_code: %d", event_code);
    lv_obj_t *target = lv_event_get_target(e);
    DBG_MSG("target: %p", target);
    /*   if (event_code == LV_EVENT_CLICKED)
      {
          lv_label_set_text(ui_keshiIDlabel, "201 ");
          lv_label_set_text(ui_tixingIP, "201");
          lv_disp_load_scr(ui_doctorWin);
          DBG_MSG("跳转201成功");
      } */
    if (lv_event_get_code(e) == LV_EVENT_CLICKED)
    {
        const char *room_id = (const char *)lv_event_get_user_data(e);
        char buf[8];

        strcpy(buf, room_id);
        DBG_MSG("接受门牌号: %s", buf);

        // 获取科室医生信息
        char DOCname[100], DOCjianjie[500];
        char DOCpath[100] = {0};
        sprintf(DOCpath, "docsTXT/%s.txt", buf);
        DBG_MSG("门牌号对应的文件路径: %s", DOCpath);
        FILE *DOCfp = openfile(DOCpath, "r");     // 打开科室文件
        fgets(DOCname, sizeof(DOCname), DOCfp);   // 姓名
        lv_label_set_text(ui_shanchang, DOCname); // 原打算写医生擅长,后考虑改为医生姓名展示
        DOCname[strcspn(DOCname, "\r\n")] = '\0';
        DBG_MSG("医生姓名: %s ", DOCname);
        fgets(docID, sizeof(docID), DOCfp); // 医生编号     用于获取对应的就诊中,待诊中,候诊中病患名字

        docID[strcspn(docID, "\r\n")] = '\0';
        DBG_MSG("医生编号: %s ", docID);
        fgets(DOCjianjie, sizeof(DOCjianjie), DOCfp); // 简介
        DOCjianjie[strcspn(DOCjianjie, "\r\n")] = '\0';

        DOCjianjie[strcspn(DOCjianjie, "。")] = '\n';
        DBG_MSG("简介: %s ", DOCjianjie);
        lv_textarea_set_text(ui_DOCxiangxijieshaoText, DOCjianjie); // 医生简介

        closefile(DOCfp); // 关闭科室文件
        DBG_MSG("开始获取病患信息");
        sprintf(DOCpath, "patsTXT/%s.txt", docID); // 医生编号
        DBG_MSG("病患文件路径: %s", DOCpath);
        DOCfp = openfile(DOCpath, "r"); // 打开医生编号对应的病患文件
        char PATSname[100];

        fgets(PATSname, sizeof(PATSname), DOCfp); //
        DBG_MSG("就诊中病患姓名: ", PATSname);
        PATSname[strcspn(PATSname, "\r\n")] = '\0';
        if (strlen(PATSname) == 0 || strcmp(PATSname, "pm") == 0)
        {
            lv_label_set_text(ui_binghuanNAMElabel, "暂无病患");
        }
        else
        {
            lv_label_set_text(ui_binghuanNAMElabel, PATSname); // 就诊中的病患名
        }
        char tixingNAME[100] = {0};

        memset(PATSname, 0, sizeof(PATSname));    // 清空再读取
        fgets(PATSname, sizeof(PATSname), DOCfp); // 被呼叫的病患名
        PATSname[strcspn(PATSname, "\r\n")] = '\0';
        if (strcmp(PATSname, "pm") == 0)
        {
            memset(PATSname, 0, sizeof(PATSname));    // 清空再读取
            fgets(PATSname, sizeof(PATSname), DOCfp); // 被呼叫的病患名
            PATSname[strcspn(PATSname, "\r\n")] = '\0';
        }

        sprintf(tixingNAME, "%s", PATSname);
        char PATSnameList[200] = {0};
        fgets(PATSname, sizeof(PATSname), DOCfp); // 就诊中病患姓名
        PATSname[strcspn(PATSname, "\r\n")] = '\0';
        while (1)
        {
            DBG_MSG("am-");
            int len = strlen(PATSnameList);
            if (strcmp(PATSname, "pm") == 0)
            {
                sprintf(PATSname, " ");
                PATSname[strcspn(PATSname, "\r\n")] = '\0';
                snprintf(PATSnameList + len, sizeof(PATSnameList) - len, "%s\n", " ");
                break;
            }

            snprintf(PATSnameList + len, sizeof(PATSnameList) - len, "%s\n", PATSname);
            if (feof(DOCfp) != 0 || strcmp(PATSname, "pm") == 0) // 文件读取到达文件末尾
                break;
            fgets(PATSname, sizeof(PATSname), DOCfp); // 就诊中病患姓名
            PATSname[strcspn(PATSname, "\r\n")] = '\0';
            DBG_MSG("-am");
        }

        if (strlen(PATSnameList) == 0)
        {
            lv_label_set_text(ui_AMbinghuanlist, "暂无候诊");
        }
        else
        {

            lv_label_set_text(ui_AMbinghuanlist, PATSnameList); // 早上的候诊病患列表
        }
        memset(PATSnameList, 0, sizeof(PATSnameList)); // 重新清空
        memset(PATSname, 0, sizeof(PATSname));
        fgets(PATSname, sizeof(PATSname), DOCfp); // 就诊中病患姓名
        PATSname[strcspn(PATSname, "\r\n")] = '\0';
        while (1)
        {
            DBG_MSG("pm-");
            int len = strlen(PATSnameList);
            if (strcmp(PATSname, "pm") == 0)
            {
                sprintf(PATSname, " ");
                PATSname[strcspn(PATSname, "\r\n")] = '\0';
                snprintf(PATSnameList + len, sizeof(PATSnameList) - len, "%s\n", " ");
                continue;
            }

            snprintf(PATSnameList + len, sizeof(PATSnameList) - len, "%s\n", PATSname);
            if (feof(DOCfp) != 0) // 文件读取到达文件末尾
                break;
            fgets(PATSname, sizeof(PATSname), DOCfp); // 就诊中病患姓名
            PATSname[strcspn(PATSname, "\r\n")] = '\0';
            DBG_MSG("-pm");
        }
        if (strlen(PATSnameList) == 0)
        {
            lv_label_set_text(PATSnameList, "暂无候诊");
        }
        else
        {

            lv_label_set_text(ui_PMbinghuanlist, PATSnameList); // 下午的候诊病患列表
        }

        // 更新科室种类名图片显示
        lv_obj_add_flag(ui_JXYLzyk, LV_OBJ_FLAG_HIDDEN);
        lv_obj_add_flag(ui_JXYLkfk, LV_OBJ_FLAG_HIDDEN);
        lv_obj_add_flag(ui_JXYLnk, LV_OBJ_FLAG_HIDDEN);
        lv_obj_add_flag(ui_JXYLwk, LV_OBJ_FLAG_HIDDEN);
        int len = strlen(ui_tixingNAME);

        char room_tag[100] = {0};
        switch (atoi(buf))
        {
            // 内科
        case 201:
        case 202:
        case 203:
            sprintf(room_tag, "\n请提前抵达\n二层内科 \n--     %s室 \n等待就诊", buf);
            DBG_MSG("科室编号=%d", atoi(buf));
            lv_obj_clear_flag(ui_JXYLnk, LV_OBJ_FLAG_HIDDEN);
            break;
            // 外科
        case 204:
        case 205:
        case 206:
            sprintf(room_tag, "\n请提前抵达\n二层外科 \n--     %s室 \n等待就诊", buf);
            DBG_MSG("科室编号=%d", atoi(buf));
            lv_obj_clear_flag(ui_JXYLwk, LV_OBJ_FLAG_HIDDEN);
            break;
            // 中医科
        case 301:
        case 302:
        case 303:
            sprintf(room_tag, "\n请提前抵达\n三层中医科 \n--     %s室 \n等待就诊", buf);
            DBG_MSG("科室编号=%d", atoi(buf));
            lv_obj_clear_flag(ui_JXYLzyk, LV_OBJ_FLAG_HIDDEN);
            break;
            // 康复科
        case 304:
        case 305:
        case 306:
            sprintf(room_tag, "\n请提前抵达\n三层康复科 \n--     %s室 \n等待就诊", buf);
            DBG_MSG("科室编号=%d", atoi(buf));
            lv_obj_clear_flag(ui_JXYLkfk, LV_OBJ_FLAG_HIDDEN);
            break;
        default:
            lv_obj_clear_flag(ui_JXYLkfk, LV_OBJ_FLAG_HIDDEN);
            break;
        }

        if (strlen(tixingNAME) > 0)
        {
            snprintf(tixingNAME + len, sizeof(tixingNAME) - len, "%s\n", room_tag);
        }
        if (strlen(tixingNAME) > 0)
        {
            lv_label_set_text(ui_tixingNAME, tixingNAME); // 被呼叫的病患名
        }
        else
        {
            lv_label_set_text(ui_tixingNAME, "无待诊病患");
        }

        lv_label_set_text(ui_keshiIDlabel, buf);

        //  lv_label_set_text(ui_tixingIP, room_id);//体型病患前往的科室号码
        lv_disp_load_scr(ui_doctorWin);
        DBG_MSG(" room_id: %s", room_id);
        DBG_MSG("跳转%s成功", room_id);
    }
    else
    {
        DBG_MSG("跳转科室失败");
    }
}

void ui_event_gotologin(lv_event_t *e)
{
    DBG_PRINT();
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_CLICKED)
    {
        lv_obj_add_flag(label_timeANDdate, LV_OBJ_FLAG_HIDDEN); // 隐藏
        DBG_MSG("跳转登录界面,并隐藏时间标签");
        lv_disp_load_scr(ui_LoginRegisteWin);
    }
    DBG_PRINT();
}

///////////////////// SCREENS ////////////////////

lv_obj_t *label_timeANDdate = NULL;
void init_global_time_label(void)
{
    label_timeANDdate = lv_label_create(lv_layer_top());

    lv_label_set_text(label_timeANDdate, " ");
    lv_obj_align(label_timeANDdate, LV_ALIGN_OUT_TOP_LEFT, 170, 30);
    lv_obj_set_style_text_color(label_timeANDdate, lv_color_hex(0x7E00FF), 0);
    lv_obj_set_style_text_font(label_timeANDdate, &ui_font_CHINESEsize25, 0);
    lv_obj_add_flag(label_timeANDdate, LV_OBJ_FLAG_HIDDEN); // 隐藏

    lv_timer_create(update_time, 1000, NULL);
}
void update_time(lv_timer_t *timer)
{
    time_t now = time(NULL);
    struct tm *info = localtime(&now);
    char time_str[50];
    const char *week_days[] = {"周一", "周二", "周三", "周四", "周五", "周六", "周日"};
    // DBG_MSG("星期: %s", week_days[info->tm_wday]);
    sprintf(time_str, "%04d 年 %02d 月 %02d 日 |\n%s          %02d:%02d:%02d |",
            info->tm_year + 1900, info->tm_mon + 1, info->tm_mday,
            week_days[info->tm_wday], info->tm_hour, info->tm_min, info->tm_sec);

    // DBG_MSG("时间: %s", time_str);
    lv_label_set_text(label_timeANDdate, time_str);

    const char *jjz = lv_label_get_text(ui_binghuanNAMElabel);
    const char *tixing = lv_label_get_text(ui_tixingNAME);
    const char *amList = lv_label_get_text(ui_AMbinghuanlist);
    const char *pmList = lv_label_get_text(ui_PMbinghuanlist);

    if (strlen(jjz)== 0)
    { 
        lv_label_set_text(ui_binghuanNAMElabel, "空闲中");
    }
    if (strlen(tixing)== 0)
    { 
        lv_label_set_text(ui_tixingNAME, "空闲中");
    }
    if (strlen(amList)== 0)
    { 
        lv_label_set_text(ui_AMbinghuanlist, "空闲中");
    }
    if (strlen(pmList)== 0)
    { 
        lv_label_set_text(ui_PMbinghuanlist, "空闲中");
    }



}

void ui_init(void)
{

    lv_disp_t *dispp = lv_disp_get_default();
    lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                              false, LV_FONT_DEFAULT);
    DBG_PRINT();
    lv_disp_set_theme(dispp, theme);
    DBG_PRINT();
    ui_LoginRegisteWin_screen_init();
    DBG_PRINT();
    ui_doctorWin_screen_init();
    DBG_PRINT();
    ui_ditu123_screen_init();
    DBG_PRINT();
    ui_guahaoWin_screen_init();
    DBG_PRINT();
    ui____initial_actions0 = lv_obj_create(NULL);
    DBG_PRINT();
    head = initHouZhenList(); // 初始化候诊列表
    patslist = Dinit();
    init_global_time_label();
    lv_timer_create(update_time, 1000, NULL);
    lv_disp_load_scr(ui_LoginRegisteWin);
    DBG_PRINT();
    // lv_disp_load_scr(ui_doctorWin);
    // lv_disp_load_scr(ui_ditu123);
    // lv_disp_load_scr(ui_guahaoWin);
}
