// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C"
{
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

  // 定时器
  void update_time(lv_timer_t *timer);
  void create_timer();
  extern lv_obj_t *label_timeANDdate;
  // 弹窗
  void show_popup(const char *title, const char *message);

  // SCREEN: ui_guahaoWin
  void ui_event_select_time(lv_event_t *e);

  void ui_event_select_id(lv_event_t *e);
  void ui_guahaoWin_screen_init(void);
  void ui_event_button_tijiao(lv_event_t *e);
  extern lv_obj_t *ui_guahaoWin;
  extern lv_obj_t *ui_Container1;
  extern lv_obj_t *ui_TabView1;
  extern lv_obj_t *ui_yiceng;
  extern lv_obj_t *ui_ceng1Panel;
  extern lv_obj_t *ui_DocPanelCeng1;
  extern lv_obj_t *ui_GHdocImageCeng1;
  extern lv_obj_t *ui_GHdocnameCeng1;
  extern lv_obj_t *ui_GHceng1countContainerCeng1;
  extern lv_obj_t *ui_GHdzzLabelCeng2;
  extern lv_obj_t *ui_GHdzzLabelCeng1;
  extern lv_obj_t *ui_GHcountLabelCeng1;
  extern lv_obj_t *ui_ImageCeng1;
  extern lv_obj_t *ui_LabelselectCeng1;
  extern lv_obj_t *ui_RollerTimeCeng1;
  extern lv_obj_t *ui_ButtonCeng1;
  extern lv_obj_t *ui_RollerCeng1;
  extern lv_obj_t *ui_erceng;
  extern lv_obj_t *ui_ceng2Panel;
  extern lv_obj_t *ui_ceng2DocPanel;
  extern lv_obj_t *ui_GHdocImage2;
  extern lv_obj_t *ui_GHdocnameCeng2;
  extern lv_obj_t *ui_GHceng1countContainerCeng2;
  extern lv_obj_t *ui_GHdaizhenzhongLabelCeng2;
  extern lv_obj_t *ui_GHdzzLabelCeng3;
  extern lv_obj_t *ui_GHcountLabelCeng2;
  extern lv_obj_t *ui_ImageCeng2;
  extern lv_obj_t *ui_LabelselectCeng2;
  extern lv_obj_t *ui_RollerTimeCeng2;
  extern lv_obj_t *ui_ButtonCeng2;
  extern lv_obj_t *ui_Rollerceng2;
  extern lv_obj_t *ui_guahaohead;
  extern lv_obj_t *ui_fanhuiditu123;
  extern lv_obj_t *ui_jiuxuanyiliao1;
  extern lv_obj_t *ui_JXYLguahao;
  extern lv_obj_t *ui____initial_actions0;
  void ui_event_gotoGuaHaoWin(lv_event_t *e);

  LV_IMG_DECLARE(ui__temporary_image);
  LV_IMG_DECLARE(ui_img_ditu234_png);    // assets/ditu234.png
  LV_IMG_DECLARE(ui_img_shoufutix_png);  // assets/shoufutiX.png
  LV_IMG_DECLARE(ui_img_shoufutiis_png); // assets/shoufutiiS.png
  LV_IMG_DECLARE(ui_img_cesuo_png);      // assets/cesuo.png
  LV_IMG_DECLARE(ui_img_sostongdao_png); // assets/SOStongdao.png
  LV_IMG_DECLARE(ui_img_kangfuke_png);   // assets/kangfuke.png
  LV_IMG_DECLARE(ui_img_zhongyike_png);  // assets/zhongyike.png
  LV_IMG_DECLARE(ui_img_denghouqu_png);  // assets/denghouqu.png
  LV_IMG_DECLARE(ui_img_waike_png);      // assets/waike.png
  LV_IMG_DECLARE(ui_img_neike_png);      // assets/neike.png
  LV_IMG_DECLARE(ui_img_ditu1_png);      // assets/ditu1.png
  LV_IMG_DECLARE(ui_img_damen_png);      // assets/damen.png
  LV_IMG_DECLARE(ui_img_jiaofeichu_png); // assets/jiaofeichu.png
  LV_IMG_DECLARE(ui_img_quyaochu_png);   // assets/quyaochu.png
  LV_IMG_DECLARE(ui_img_qiantai_png);    // assets/qiantai.png
  LV_IMG_DECLARE(ui_img_guahao_png);     // assets/guahao.png
  LV_IMG_DECLARE(ui_img_back_png);       // assets/back.png
  LV_IMG_DECLARE(ui_img_jxyl_png);       // assets/jxyl.png
  LV_IMG_DECLARE(ui_img_yiceng_png);     // assets/yiceng.png
  LV_IMG_DECLARE(ui_img_sanceng_png);    // assets/sanceng.png
  LV_IMG_DECLARE(ui_img_erceng_png);     // assets/erceng.png
  LV_IMG_DECLARE(ui_img_missdoctor_png); // assets/missdoctor.png
  LV_IMG_DECLARE(ui_img_style1_png);     // assets/style1.png
  LV_IMG_DECLARE(ui_img_tijiao_png);     // assets/tijiao.png
  LV_IMG_DECLARE(ui_img_headguahao_png); // assets/headguahao.png

  static int keshiid = 201;

  // SCREEN: ui_ditu123
  void ui_ditu123_screen_init(void);
  extern lv_obj_t *ui_ditu123;
  extern lv_obj_t *ui_DocWinContainer;
  extern lv_obj_t *ui_DocWinTabView;
  extern lv_obj_t *ui_ceng3;
  extern lv_obj_t *ui_ContainerCeng3;
  extern lv_obj_t *ui_shoufutiPanel3;
  extern lv_obj_t *ui_shoufutiX3;
  extern lv_obj_t *ui_shoufutiS3;
  extern lv_obj_t *ui_shoufutiText3;
  extern lv_obj_t *ui_cesuo3;
  extern lv_obj_t *ui_sosContainer3;
  extern lv_obj_t *ui_SOS3;
  extern lv_obj_t *ui_SOSlabel3;
  extern lv_obj_t *ui_kangfukeContainer;
  extern lv_obj_t *ui_keshi5;
  extern lv_obj_t *ui_kangfukeButton306;
  extern lv_obj_t *ui_kangfuke306;
  extern lv_obj_t *ui_kangfukeButton305;
  extern lv_obj_t *ui_kangfuke305;
  extern lv_obj_t *ui_kangfukeButton304;
  extern lv_obj_t *ui_kangfuke304;
  extern lv_obj_t *ui_kangfukeLabel4;
  extern lv_obj_t *ui_kangfuke;
  extern lv_obj_t *ui_neikeContainer1;
  extern lv_obj_t *ui_keshi3;
  extern lv_obj_t *ui_zhongyikeButton303;
  extern lv_obj_t *ui_zhongyikeLabel303;
  extern lv_obj_t *ui_zhongyikeButton302;
  extern lv_obj_t *ui_zhongyikeLabel302;
  extern lv_obj_t *ui_zhongyikeButton301;
  extern lv_obj_t *ui_zhongyikeLabel301;
  extern lv_obj_t *ui_zhongyikeLabel4;
  extern lv_obj_t *ui_neike1;
  extern lv_obj_t *ui_houzhenquPanel3;
  extern lv_obj_t *ui_houzhenqu3;
  extern lv_obj_t *ui_houzhenquLabel3;
  extern lv_obj_t *ui_ceng2;
  extern lv_obj_t *ui_ContainerCeng2;
  extern lv_obj_t *ui_shoufutiPanel2;
  extern lv_obj_t *ui_shoufutiX2;
  extern lv_obj_t *ui_shoufutiS2;
  extern lv_obj_t *ui_shoufutiText2;
  extern lv_obj_t *ui_waikeContainer;
  extern lv_obj_t *ui_keshi1;
  extern lv_obj_t *ui_waikeButton206;
  extern lv_obj_t *ui_waikeLabel206;
  extern lv_obj_t *ui_waikeButton205;
  extern lv_obj_t *ui_waikeLabel205;
  extern lv_obj_t *ui_waikeButton204;
  extern lv_obj_t *ui_waikeLabel204;
  extern lv_obj_t *ui_waike;
  extern lv_obj_t *ui_waikeLabel;
  extern lv_obj_t *ui_sosContainer;
  extern lv_obj_t *ui_SOS;
  extern lv_obj_t *ui_SOSlabel;
  extern lv_obj_t *ui_cesuo2;
  extern lv_obj_t *ui_neikeContainer;
  extern lv_obj_t *ui_keshi2;
  extern lv_obj_t *ui_neikeButton203;
  extern lv_obj_t *ui_neikeLabel203;
  extern lv_obj_t *ui_neikeButton202;
  extern lv_obj_t *ui_neikeLabel202;
  extern lv_obj_t *ui_neikeButton201;
  extern lv_obj_t *ui_neikeLabel1;
  extern lv_obj_t *ui_neikeLabel201;
  extern lv_obj_t *ui_neike;
  extern lv_obj_t *ui_houzhenquPanel2;
  extern lv_obj_t *ui_houzhenqu2;
  extern lv_obj_t *ui_houzhenquLabel2;
  extern lv_obj_t *ui_ceng1;
  extern lv_obj_t *ui_bgContainer;
  extern lv_obj_t *ui_damen;
  extern lv_obj_t *ui_denghouqu1Panel;
  extern lv_obj_t *ui_denghouqu1;
  extern lv_obj_t *ui_Label3;
  extern lv_obj_t *ui_jiaofeichuPanel1;
  extern lv_obj_t *ui_jiaofeiLabel;
  extern lv_obj_t *ui_jiaofei;
  extern lv_obj_t *ui_quyaochu;
  extern lv_obj_t *ui_quyaoLabel;
  extern lv_obj_t *ui_zixunquPanel;
  extern lv_obj_t *ui_zixun1;
  extern lv_obj_t *ui_zixun2;
  extern lv_obj_t *ui_zixun3;
  extern lv_obj_t *ui_zixunquLabel;
  extern lv_obj_t *ui_guahaoPanel;
  extern lv_obj_t *ui_guahaoLabel;
  extern lv_obj_t *ui_guahaoButton;
  extern lv_obj_t *ui_cesuo1;
  extern lv_obj_t *ui_shoufutiPanel1;
  extern lv_obj_t *ui_shoufutiX1;
  extern lv_obj_t *ui_shoufutiS1;
  extern lv_obj_t *ui_shoufutiText1;
  extern lv_obj_t *ui_sosContainer1;
  extern lv_obj_t *ui_SOS1;
  extern lv_obj_t *ui_SOSlabel1;
  extern lv_obj_t *ui_head2;
  extern lv_obj_t *ui_fanhuilogin;
  extern lv_obj_t *ui_dituTIME;
  extern lv_obj_t *ui_jiuxuanyiliao2;
  extern lv_obj_t *ui_JXYLceng1;
  extern lv_obj_t *ui_JXYLceng3;
  extern lv_obj_t *ui_JXYLceng2;
  extern lv_obj_t *ui____initial_actions0;

  LV_IMG_DECLARE(ui__temporary_image);
  LV_IMG_DECLARE(ui_img_back_png);       // assets/back.png
  LV_IMG_DECLARE(ui_img_jxyl_png);       // assets/jxyl.png
  LV_IMG_DECLARE(ui_img_jxylzyk_png);    // assets/jxylzyk.png
  LV_IMG_DECLARE(ui_img_jxylkfk_png);    // assets/JXYLkfk.png
  LV_IMG_DECLARE(ui_img_jxylnk_png);     // assets/JXYLnk.png
  LV_IMG_DECLARE(ui_img_jxylwk_png);     // assets/JXYLwk.png
  LV_IMG_DECLARE(ui_img_missdoctor_png); // assets/missdoctor.png
  LV_IMG_DECLARE(ui_img_ditu234_png);    // assets/ditu234.png
  LV_IMG_DECLARE(ui_img_shoufutix_png);  // assets/shoufutiX.png
  LV_IMG_DECLARE(ui_img_shoufutiis_png); // assets/shoufutiiS.png
  LV_IMG_DECLARE(ui_img_cesuo_png);      // assets/cesuo.png
  LV_IMG_DECLARE(ui_img_sostongdao_png); // assets/SOStongdao.png
  LV_IMG_DECLARE(ui_img_kangfuke_png);   // assets/kangfuke.png
  LV_IMG_DECLARE(ui_img_zhongyike_png);  // assets/zhongyike.png
  LV_IMG_DECLARE(ui_img_denghouqu_png);  // assets/denghouqu.png
  LV_IMG_DECLARE(ui_img_waike_png);      // assets/waike.png
  LV_IMG_DECLARE(ui_img_neike_png);      // assets/neike.png
  LV_IMG_DECLARE(ui_img_ditu1_png);      // assets/ditu1.png
  LV_IMG_DECLARE(ui_img_damen_png);      // assets/damen.png
  LV_IMG_DECLARE(ui_img_jiaofeichu_png); // assets/jiaofeichu.png
  LV_IMG_DECLARE(ui_img_quyaochu_png);   // assets/quyaochu.png
  LV_IMG_DECLARE(ui_img_qiantai_png);    // assets/qiantai.png
  LV_IMG_DECLARE(ui_img_guahao_png);     // assets/guahao.png
  LV_IMG_DECLARE(ui_img_yiceng_png);     // assets/yiceng.png
  LV_IMG_DECLARE(ui_img_sanceng_png);    // assets/sanceng.png
  LV_IMG_DECLARE(ui_img_erceng_png);     // assets/erceng.png
  LV_IMG_DECLARE(ui_img_style1_png);     // assets/style1.png

  LV_FONT_DECLARE(ui_font_CHINESEsize25);

  void ui_event_goWINdoc(lv_event_t *e);
  /* void ui_event_goWINdoc202(lv_event_t * e);
  void ui_event_goWINdoc203(lv_event_t * e);
  void ui_event_goWINdoc204(lv_event_t * e);
  void ui_event_goWINdoc205(lv_event_t * e);
  void ui_event_goWINdoc206(lv_event_t * e);

  void ui_event_goWINdoc301(lv_event_t * e);
  void ui_event_goWINdoc302(lv_event_t * e);
  void ui_event_goWINdoc303(lv_event_t * e);
  void ui_event_goWINdoc304(lv_event_t * e);
  void ui_event_goWINdoc305(lv_event_t * e);
  void ui_event_goWINdoc306(lv_event_t * e); */

  void ui_event_gotologin(lv_event_t *e);
  void ui_DocWinTabView_event_handler(lv_event_t *e);

  LV_FONT_DECLARE(ui_font_CHINESEsize25);

  // SCREEN: ui_doctorWin
  void ui_doctorWin_screen_init(void);
  extern lv_obj_t *ui_doctorWin;
  extern lv_obj_t *ui_doctorHead;
  extern lv_obj_t *ui_head;
  extern lv_obj_t *ui_fanhui_goWINditu123;
  void ui_event_gotoditu123(lv_event_t *e);
  /* extern lv_obj_t * ui_DOCtime; */
  extern lv_obj_t *ui_jiuxuanyiliao;
  extern lv_obj_t *ui_JXYLzyk;
  extern lv_obj_t *ui_JXYLkfk;
  extern lv_obj_t *ui_JXYLnk;
  extern lv_obj_t *ui_JXYLwk;
  extern lv_obj_t *ui_doctorinfo;
  extern lv_obj_t *ui_doctorPNG;
  void ui_event_doctorPNG1(lv_event_t *e);
  extern lv_obj_t *ui_doctorPNG1;
  extern lv_obj_t *ui_Image3;
  extern lv_obj_t *ui_doctorgaishu;
  extern lv_obj_t *ui_shanchangINFO;
  extern lv_obj_t *ui_shanchang;
  extern lv_obj_t *ui_keshiIDlabel;
  extern lv_obj_t *ui_zhiweiLabel;
  extern lv_obj_t *ui_jianjieANDhouzhen;
  extern lv_obj_t *ui_DOCjianjie;
  extern lv_obj_t *ui_dctXiangxijieshaoContainer;
  extern lv_obj_t *ui_doctorxiangxijieshao;
  extern lv_obj_t *ui_DOCxiangxijieshaoText;
  extern lv_obj_t *ui_houzhenqu;
  extern lv_obj_t *ui_daizhenzhong;
  extern lv_obj_t *ui_daizhenzhongText;
  extern lv_obj_t *ui_AMandPM;
  extern lv_obj_t *ui_AMlist;
  extern lv_obj_t *ui_AMbinghuanlist;
  extern lv_obj_t *ui_AMtime;
  extern lv_obj_t *ui_PMlist;
  extern lv_obj_t *ui_PMbinghuanlist;
  extern lv_obj_t *ui_PMtime;
  extern lv_obj_t *ui_jiuzhenzhong;
  extern lv_obj_t *ui_jiuzhenzhongText;
  extern lv_obj_t *ui_binghuanNAME;
  extern lv_obj_t *ui_binghuanNAMElabel;
  extern lv_obj_t *ui_JINGAOlabel;
  extern lv_obj_t *ui_huhuanzhong;
  extern lv_obj_t *ui_huhuanzhongLABEL;
  extern lv_obj_t *ui_tixing;
  extern lv_obj_t *ui_tixingNAME;
  extern lv_obj_t *ui_tixingGOTO;
  extern lv_obj_t *ui_tixingIP;
  extern lv_obj_t *ui_tixingci;
  extern lv_obj_t *ui_jiuzhenzhongDropdown;
  extern lv_obj_t *ui_huhuanzhongDropdown;
  void ui_event_jiuzhenzhongDropdown(lv_event_t *e);
  void ui_event_huhuanzhongDropdown(lv_event_t *e);
  void ui_event____initial_actions0(lv_event_t *e);
  extern lv_obj_t *ui____initial_actions0;

  LV_IMG_DECLARE(ui__temporary_image);
  LV_IMG_DECLARE(ui_img_back_png);       // assets/back.png
  LV_IMG_DECLARE(ui_img_jxyl_png);       // assets/jxyl.png
  LV_IMG_DECLARE(ui_img_zyk_png);        // assets/zyk.png
  LV_IMG_DECLARE(ui_img_jxylkfk_png);    // assets/JXYLkfk.png
  LV_IMG_DECLARE(ui_img_jxylnk_png);     // assets/JXYLnk.png
  LV_IMG_DECLARE(ui_img_jxylwk_png);     // assets/JXYLwk.png
  LV_IMG_DECLARE(ui_img_missdoctor_png); // assets/missdoctor.png
  LV_IMG_DECLARE(ui_img_ditu234_png);    // assets/ditu234.png
  LV_IMG_DECLARE(ui_img_zhongyike_png);  // assets/zhongyike.png
  LV_IMG_DECLARE(ui_img_shoufutix_png);  // assets/shoufutiX.png
  LV_IMG_DECLARE(ui_img_shoufutiis_png); // assets/shoufutiiS.png
  LV_IMG_DECLARE(ui_img_kangfuke_png);   // assets/kangfuke.png
  LV_IMG_DECLARE(ui_img_cesuo_png);      // assets/cesuo.png
  LV_IMG_DECLARE(ui_img_sostongdao_png); // assets/SOStongdao.png
  LV_IMG_DECLARE(ui_img_neike_png);      // assets/neike.png
  LV_IMG_DECLARE(ui_img_waike_png);      // assets/waike.png
  LV_IMG_DECLARE(ui_img_ditu1_png);      // assets/ditu1.png
  LV_IMG_DECLARE(ui_img_damen_png);      // assets/damen.png
  LV_IMG_DECLARE(ui_img_denghouqu_png);  // assets/denghouqu.png
  LV_IMG_DECLARE(ui_img_jiaofeichu_png); // assets/jiaofeichu.png
  LV_IMG_DECLARE(ui_img_quyaochu_png);   // assets/quyaochu.png
  LV_IMG_DECLARE(ui_img_qiantai_png);    // assets/qiantai.png
  LV_IMG_DECLARE(ui_img_zixun_png);      // assets/zixun.png
  LV_IMG_DECLARE(ui_img_yiceng_png);     // assets/yiceng.png
  LV_IMG_DECLARE(ui_img_sanceng_png);    // assets/sanceng.png
  LV_IMG_DECLARE(ui_img_erceng_png);     // assets/erceng.png
  LV_IMG_DECLARE(ui_img_style1_png);     // assets/style1.png

  LV_FONT_DECLARE(ui_font_CHINESEsize25);

  // SCREEN: ui_LoginRegisteWin
  extern lv_obj_t *ui_errormsg;
  extern lv_obj_t *ui_errorLabel;
  void ui_LoginRegisteWin_screen_init(void);
  extern lv_obj_t *ui_LoginRegisteWin;
  extern lv_obj_t *ui_loginBG;
  extern lv_obj_t *ui_LRContainer;
  extern lv_obj_t *ui_LoginRegiste;
  extern lv_obj_t *ui_username;
  void ui_event_usernameText(lv_event_t *e);
  extern lv_obj_t *ui_usernameText;
  extern lv_obj_t *ui_usernameLabel;
  extern lv_obj_t *ui_password;
  void ui_event_mmText_(lv_event_t *e);
  extern lv_obj_t *ui_mmText_;
  extern lv_obj_t *ui_mmLabel;
  void ui_event_mmX(lv_event_t *e);
  extern lv_obj_t *ui_mmX;
  void ui_event_mmY(lv_event_t *e);
  extern lv_obj_t *ui_mmY;
  extern lv_obj_t *ui_userIDcard;
  void ui_event_userIDcardText_(lv_event_t *e);
  extern lv_obj_t *ui_userIDcardText_;
  extern lv_obj_t *ui_userIDcardLabel;
  void ui_event_shenfenChange(lv_event_t *e);
  extern lv_obj_t *ui_shenfenChange;
  extern lv_obj_t *ui_shenfenPanel;
  extern lv_obj_t *ui_shenfenLabel;
  void ui_event_shenfen(lv_event_t *e);
  extern lv_obj_t *ui_shenfen;
  extern lv_obj_t *ui_doctorCon;
  extern lv_obj_t *ui_doctorText;
  extern lv_obj_t *ui_LRbutton;
  extern lv_obj_t *ui_denglu;
  void ui_event_zhuce(lv_event_t *e);
  extern lv_obj_t *ui_zhuce;
  extern lv_obj_t *ui_loginpng1;
  extern lv_obj_t *ui_loginJINGAO;
  void ui_event_jianpanX(lv_event_t *e);
  extern lv_obj_t *ui_jianpanX;
  extern lv_obj_t *ui_jianpan;
  extern lv_obj_t *ui_jianpanPanel;
  extern lv_obj_t *ui_MSGbg;
  extern lv_obj_t *ui_jianpanLabel;
  extern lv_obj_t *ui_TextdocID;
  extern lv_obj_t *ui____initial_actions0;
  void ui_event_TextdocIDText(lv_event_t *e);

  LV_IMG_DECLARE(ui__temporary_image);
  LV_IMG_DECLARE(ui_img_loginregiste_png); // assets/LoginRegiste.png
  LV_IMG_DECLARE(ui_img_xianshi_png);      // assets/xianshi.png
  LV_IMG_DECLARE(ui_img_yincang_png);      // assets/yincang.png
  LV_IMG_DECLARE(ui_img_659432751);        // assets/denglu (2).png
  LV_IMG_DECLARE(ui_img_1266464991);       // assets/zhuce (2).png
  LV_IMG_DECLARE(ui_img_style1_png);       // assets/style1.png
  LV_IMG_DECLARE(ui_img_back_png);         // assets/back.png
  LV_IMG_DECLARE(ui_img_jxyl_png);         // assets/jxyl.png
  LV_IMG_DECLARE(ui_img_zyk_png);          // assets/zyk.png
  LV_IMG_DECLARE(ui_img_missdoctor_png);   // assets/missdoctor.png

  LV_FONT_DECLARE(ui_font_CHINESEsize25);

  void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
