// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"
#include "../../ui_LoginAndRegiste.h"
void ui_doctorWin_screen_init(void)
{
  DBG_MSG("开始初始化doctorWin_screen_init");
  ui_doctorWin = lv_obj_create(NULL);
  lv_obj_clear_flag(ui_doctorWin, LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_doctorHead = lv_obj_create(ui_doctorWin);
  lv_obj_remove_style_all(ui_doctorHead);
  lv_obj_set_width(ui_doctorHead, 966);
  lv_obj_set_height(ui_doctorHead, 548);
  lv_obj_set_x(ui_doctorHead, 1);
  lv_obj_set_y(ui_doctorHead, -187);
  lv_obj_set_align(ui_doctorHead, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_doctorHead, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_head = lv_obj_create(ui_doctorHead);
  lv_obj_set_width(ui_head, 947);
  lv_obj_set_height(ui_head, 73);
  lv_obj_set_x(ui_head, 5);
  lv_obj_set_y(ui_head, -64);
  lv_obj_set_align(ui_head, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_head, LV_OBJ_FLAG_SCROLLABLE); /// Flags
  lv_obj_set_style_radius(ui_head, 25, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_fanhui_goWINditu123 = lv_imgbtn_create(ui_head);
  lv_imgbtn_set_src(ui_fanhui_goWINditu123, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_back_png, NULL);
  lv_imgbtn_set_src(ui_fanhui_goWINditu123, LV_IMGBTN_STATE_PRESSED, NULL, &ui__temporary_image, NULL);
  lv_imgbtn_set_src(ui_fanhui_goWINditu123, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
  lv_imgbtn_set_src(ui_fanhui_goWINditu123, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
  lv_imgbtn_set_src(ui_fanhui_goWINditu123, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
  lv_imgbtn_set_src(ui_fanhui_goWINditu123, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
  lv_obj_set_width(ui_fanhui_goWINditu123, 47);
  lv_obj_set_height(ui_fanhui_goWINditu123, 47);
  lv_obj_set_x(ui_fanhui_goWINditu123, -437);
  lv_obj_set_y(ui_fanhui_goWINditu123, 0);
  lv_obj_set_align(ui_fanhui_goWINditu123, LV_ALIGN_CENTER);

  /*
    ui_DOCtime = lv_label_create(ui_head);
    lv_obj_set_width(ui_DOCtime, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_DOCtime, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_DOCtime, -318);
    lv_obj_set_y(ui_DOCtime, -1);
    lv_obj_set_align(ui_DOCtime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DOCtime, "2026/2/3 \n12:45");
    lv_obj_set_style_text_color(ui_DOCtime, lv_color_hex(0x7E00FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DOCtime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DOCtime, &ui_font_CHINESEsize25, LV_PART_MAIN | LV_STATE_DEFAULT);
   */

  ui_jiuxuanyiliao = lv_img_create(ui_head);
  lv_img_set_src(ui_jiuxuanyiliao, &ui_img_jxyl_png);
  lv_obj_set_height(ui_jiuxuanyiliao, 114);
  lv_obj_set_width(ui_jiuxuanyiliao, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_jiuxuanyiliao, 70);
  lv_obj_set_y(ui_jiuxuanyiliao, -6);
  lv_obj_set_align(ui_jiuxuanyiliao, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_jiuxuanyiliao, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
  lv_obj_clear_flag(ui_jiuxuanyiliao, LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_JXYLzyk = lv_img_create(ui_head);
  lv_img_set_src(ui_JXYLzyk, &ui_img_jxylzyk_png);
  lv_obj_set_width(ui_JXYLzyk, LV_SIZE_CONTENT);  /// 200
  lv_obj_set_height(ui_JXYLzyk, LV_SIZE_CONTENT); /// 100
  lv_obj_set_x(ui_JXYLzyk, 373);
  lv_obj_set_y(ui_JXYLzyk, -4);
  lv_obj_set_align(ui_JXYLzyk, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_JXYLzyk, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST); /// Flags
  lv_obj_clear_flag(ui_JXYLzyk, LV_OBJ_FLAG_SCROLLABLE);                     /// Flags

  ui_JXYLkfk = lv_img_create(ui_head);
  lv_img_set_src(ui_JXYLkfk, &ui_img_jxylkfk_png);
  lv_obj_set_width(ui_JXYLkfk, LV_SIZE_CONTENT);  /// 200
  lv_obj_set_height(ui_JXYLkfk, LV_SIZE_CONTENT); /// 100
  lv_obj_set_x(ui_JXYLkfk, 370);
  lv_obj_set_y(ui_JXYLkfk, -2);
  lv_obj_set_align(ui_JXYLkfk, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_JXYLkfk, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST); /// Flags
  lv_obj_clear_flag(ui_JXYLkfk, LV_OBJ_FLAG_SCROLLABLE);                     /// Flags

  ui_JXYLnk = lv_img_create(ui_head);
  lv_img_set_src(ui_JXYLnk, &ui_img_jxylnk_png);
  lv_obj_set_width(ui_JXYLnk, LV_SIZE_CONTENT);  /// 200
  lv_obj_set_height(ui_JXYLnk, LV_SIZE_CONTENT); /// 100
  lv_obj_set_x(ui_JXYLnk, 374);
  lv_obj_set_y(ui_JXYLnk, -4);
  lv_obj_set_align(ui_JXYLnk, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_JXYLnk, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST); /// Flags
  lv_obj_clear_flag(ui_JXYLnk, LV_OBJ_FLAG_SCROLLABLE);                     /// Flags

  ui_JXYLwk = lv_img_create(ui_head);
  lv_img_set_src(ui_JXYLwk, &ui_img_jxylwk_png);
  lv_obj_set_width(ui_JXYLwk, LV_SIZE_CONTENT);  /// 200
  lv_obj_set_height(ui_JXYLwk, LV_SIZE_CONTENT); /// 100
  lv_obj_set_x(ui_JXYLwk, 379);
  lv_obj_set_y(ui_JXYLwk, 0);
  lv_obj_set_align(ui_JXYLwk, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_JXYLwk, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST); /// Flags
  lv_obj_clear_flag(ui_JXYLwk, LV_OBJ_FLAG_SCROLLABLE);                     /// Flags

  ui_doctorinfo = lv_obj_create(ui_doctorWin);
  lv_obj_remove_style_all(ui_doctorinfo);
  lv_obj_set_width(ui_doctorinfo, 283);
  lv_obj_set_height(ui_doctorinfo, 478);
  lv_obj_set_x(ui_doctorinfo, -326);
  lv_obj_set_y(ui_doctorinfo, 33);
  lv_obj_set_align(ui_doctorinfo, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_doctorinfo, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags
  lv_obj_set_style_radius(ui_doctorinfo, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_color(ui_doctorinfo, lv_color_hex(0x01A0FF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_doctorinfo, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_doctorPNG = lv_obj_create(ui_doctorinfo);
  lv_obj_remove_style_all(ui_doctorPNG);
  lv_obj_set_width(ui_doctorPNG, 254);
  lv_obj_set_height(ui_doctorPNG, 273);
  lv_obj_set_x(ui_doctorPNG, 0);
  lv_obj_set_y(ui_doctorPNG, -99);
  lv_obj_set_align(ui_doctorPNG, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_doctorPNG, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_doctorPNG1 = lv_obj_create(ui_doctorPNG);
  lv_obj_set_width(ui_doctorPNG1, 220);
  lv_obj_set_height(ui_doctorPNG1, 243);
  lv_obj_set_x(ui_doctorPNG1, 1);
  lv_obj_set_y(ui_doctorPNG1, 3);
  lv_obj_set_align(ui_doctorPNG1, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_doctorPNG1, LV_OBJ_FLAG_SCROLLABLE); /// Flags
  lv_obj_set_style_radius(ui_doctorPNG1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_Image3 = lv_img_create(ui_doctorPNG1);
  lv_img_set_src(ui_Image3, &ui_img_missdoctor_png);
  lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_Image3, 4);
  lv_obj_set_y(ui_Image3, 8);
  lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
  lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE); /// Flags
  lv_img_set_zoom(ui_Image3, 400);

  ui_doctorgaishu = lv_obj_create(ui_doctorinfo);
  lv_obj_remove_style_all(ui_doctorgaishu);
  lv_obj_set_width(ui_doctorgaishu, 247);
  lv_obj_set_height(ui_doctorgaishu, 175);
  lv_obj_set_x(ui_doctorgaishu, 0);
  lv_obj_set_y(ui_doctorgaishu, 133);
  lv_obj_set_align(ui_doctorgaishu, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_doctorgaishu, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags
  lv_obj_set_style_radius(ui_doctorgaishu, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_color(ui_doctorgaishu, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_doctorgaishu, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_shanchangINFO = lv_obj_create(ui_doctorgaishu);
  lv_obj_set_width(ui_shanchangINFO, 228);
  lv_obj_set_height(ui_shanchangINFO, 114);
  lv_obj_set_x(ui_shanchangINFO, 1);
  lv_obj_set_y(ui_shanchangINFO, 24);
  lv_obj_set_align(ui_shanchangINFO, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_shanchangINFO, LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_shanchang = lv_label_create(ui_shanchangINFO);
  lv_obj_set_width(ui_shanchang, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_shanchang, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_shanchang, -4);
  lv_obj_set_y(ui_shanchang, 30);

  lv_obj_set_align(ui_shanchang, LV_ALIGN_CENTER);
  // 原打算写医生擅长,后考虑改为医生姓名展示 line:471
  lv_obj_set_style_text_color(ui_shanchang, lv_color_hex(0x6600FF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_shanchang, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_letter_space(ui_shanchang, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_shanchang, &ui_font_CHINESEsize25, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_keshiIDlabel = lv_label_create(ui_doctorgaishu);
  lv_obj_set_width(ui_keshiIDlabel, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_keshiIDlabel, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_keshiIDlabel, -81);
  lv_obj_set_y(ui_keshiIDlabel, -62);
  lv_obj_set_align(ui_keshiIDlabel, LV_ALIGN_CENTER);
  // 显示科室门牌号 line:464
  lv_obj_set_style_text_color(ui_keshiIDlabel, lv_color_hex(0x4300FA), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_keshiIDlabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_keshiIDlabel, &ui_font_CHINESEsize25, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_zhiweiLabel = lv_label_create(ui_doctorgaishu);
  lv_obj_set_width(ui_zhiweiLabel, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_zhiweiLabel, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_zhiweiLabel, 25);
  lv_obj_set_y(ui_zhiweiLabel, -62);
  lv_obj_set_align(ui_zhiweiLabel, LV_ALIGN_CENTER);
  lv_label_set_text(ui_zhiweiLabel, "室      主治医师");
  lv_obj_set_style_text_color(ui_zhiweiLabel, lv_color_hex(0x3A00FF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_zhiweiLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_zhiweiLabel, &ui_font_CHINESEsize25, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_jianjieANDhouzhen = lv_tabview_create(ui_doctorWin, LV_DIR_LEFT, 100);
  lv_obj_set_width(ui_jianjieANDhouzhen, 675);
  lv_obj_set_height(ui_jianjieANDhouzhen, 472);
  lv_obj_set_x(ui_jianjieANDhouzhen, 171);
  lv_obj_set_y(ui_jianjieANDhouzhen, 31);
  lv_obj_set_align(ui_jianjieANDhouzhen, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_jianjieANDhouzhen, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags

  lv_obj_set_style_text_color(lv_tabview_get_tab_btns(ui_jianjieANDhouzhen), lv_color_hex(0x6900FF),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(lv_tabview_get_tab_btns(ui_jianjieANDhouzhen), 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(lv_tabview_get_tab_btns(ui_jianjieANDhouzhen), &ui_font_CHINESEsize25,
                             LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_radius(lv_tabview_get_tab_btns(ui_jianjieANDhouzhen), 20, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_color(lv_tabview_get_tab_btns(ui_jianjieANDhouzhen), lv_color_hex(0xFFFFFF),
                            LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(lv_tabview_get_tab_btns(ui_jianjieANDhouzhen), 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_DOCjianjie = lv_tabview_add_tab(ui_jianjieANDhouzhen, "医\n生\n简\n介");
  lv_obj_clear_flag(ui_DOCjianjie, LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_dctXiangxijieshaoContainer = lv_obj_create(ui_DOCjianjie);
  lv_obj_remove_style_all(ui_dctXiangxijieshaoContainer);
  lv_obj_set_width(ui_dctXiangxijieshaoContainer, 549);
  lv_obj_set_height(ui_dctXiangxijieshaoContainer, 481);
  lv_obj_set_x(ui_dctXiangxijieshaoContainer, 10);
  lv_obj_set_y(ui_dctXiangxijieshaoContainer, 7);
  lv_obj_set_align(ui_dctXiangxijieshaoContainer, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_dctXiangxijieshaoContainer,
                    LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags

  ui_doctorxiangxijieshao = lv_obj_create(ui_dctXiangxijieshaoContainer);
  lv_obj_set_width(ui_doctorxiangxijieshao, 534);
  lv_obj_set_height(ui_doctorxiangxijieshao, 429);
  lv_obj_set_x(ui_doctorxiangxijieshao, -10);
  lv_obj_set_y(ui_doctorxiangxijieshao, -12);
  lv_obj_set_align(ui_doctorxiangxijieshao, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_doctorxiangxijieshao, LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_DOCxiangxijieshaoText = lv_textarea_create(ui_doctorxiangxijieshao);
  lv_obj_set_width(ui_DOCxiangxijieshaoText, 502);
  lv_obj_set_height(ui_DOCxiangxijieshaoText, 386);
  lv_obj_set_x(ui_DOCxiangxijieshaoText, 3);
  lv_obj_set_y(ui_DOCxiangxijieshaoText, 3);
  lv_obj_set_align(ui_DOCxiangxijieshaoText, LV_ALIGN_CENTER);
  // 这一行原是医生简介,已剪切到ui.c   line:481
  lv_textarea_set_placeholder_text(ui_DOCxiangxijieshaoText, "Placeholder...");
  lv_obj_set_style_text_color(ui_DOCxiangxijieshaoText, lv_color_hex(0x6800FB), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_DOCxiangxijieshaoText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_DOCxiangxijieshaoText, &ui_font_CHINESEsize25, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_houzhenqu = lv_tabview_add_tab(ui_jianjieANDhouzhen, "侯\n诊\n区");
  lv_obj_clear_flag(ui_houzhenqu, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_MOMENTUM); /// Flags

  ui_daizhenzhong = lv_obj_create(ui_houzhenqu);
  lv_obj_set_width(ui_daizhenzhong, 291);
  lv_obj_set_height(ui_daizhenzhong, 449);
  lv_obj_set_x(ui_daizhenzhong, 117);
  lv_obj_set_y(ui_daizhenzhong, -1);
  lv_obj_set_align(ui_daizhenzhong, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_daizhenzhong, LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_daizhenzhongText = lv_label_create(ui_daizhenzhong);
  lv_obj_set_width(ui_daizhenzhongText, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_daizhenzhongText, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_daizhenzhongText, -2);
  lv_obj_set_y(ui_daizhenzhongText, -209);
  lv_obj_set_align(ui_daizhenzhongText, LV_ALIGN_CENTER);
  lv_label_set_text(ui_daizhenzhongText, "\n待诊中...");
  lv_obj_set_style_text_color(ui_daizhenzhongText, lv_color_hex(0x7700FF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_daizhenzhongText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_daizhenzhongText, &ui_font_CHINESEsize25, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_AMandPM = lv_obj_create(ui_daizhenzhong);
  lv_obj_set_width(ui_AMandPM, 255);
  lv_obj_set_height(ui_AMandPM, 392);
  lv_obj_set_x(ui_AMandPM, -1);
  lv_obj_set_y(ui_AMandPM, 21);
  lv_obj_set_align(ui_AMandPM, LV_ALIGN_CENTER);
  lv_obj_set_align(ui_AMandPM, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_AMandPM, LV_OBJ_FLAG_SCROLLABLE); /// Flags
  lv_obj_set_style_radius(ui_AMandPM, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_color(ui_AMandPM, lv_color_hex(0x01C9FF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_AMandPM, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  DBG_PRINT();

  ui_AMlist = lv_obj_create(ui_AMandPM);
  lv_obj_set_width(ui_AMlist, 245);
  lv_obj_set_height(ui_AMlist, 143);
  lv_obj_set_x(ui_AMlist, 0);
  lv_obj_set_y(ui_AMlist, -76);
  lv_obj_set_align(ui_AMlist, LV_ALIGN_CENTER);

  ui_AMbinghuanlist = lv_label_create(ui_AMlist);
  lv_obj_set_width(ui_AMbinghuanlist, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_AMbinghuanlist, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_AMbinghuanlist, 4);
  lv_obj_set_y(ui_AMbinghuanlist, 0);
  lv_obj_set_align(ui_AMbinghuanlist, LV_ALIGN_OUT_TOP_MID);
  lv_obj_clear_flag(ui_AMbinghuanlist, LV_OBJ_FLAG_SCROLLABLE);

  // 早上的病患列表
  lv_obj_set_style_text_color(ui_AMbinghuanlist, lv_color_hex(0x3F03FC), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_AMbinghuanlist, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_letter_space(ui_AMbinghuanlist, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_line_space(ui_AMbinghuanlist, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_AMbinghuanlist, &ui_font_CHINESEsize25, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_AMtime = lv_label_create(ui_AMandPM);
  lv_obj_set_width(ui_AMtime, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_AMtime, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_AMtime, 1);
  lv_obj_set_y(ui_AMtime, -167);
  lv_obj_set_align(ui_AMtime, LV_ALIGN_CENTER);
  lv_label_set_text(ui_AMtime, "上午 8:30-11:30");
  lv_obj_set_style_text_color(ui_AMtime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_AMtime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_letter_space(ui_AMtime, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_line_space(ui_AMtime, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_AMtime, &ui_font_CHINESEsize25, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_PMlist = lv_obj_create(ui_AMandPM);
  lv_obj_set_width(ui_PMlist, 245);
  lv_obj_set_height(ui_PMlist, 143);
  lv_obj_set_x(ui_PMlist, 0);
  lv_obj_set_y(ui_PMlist, 112);
  lv_obj_set_align(ui_PMlist, LV_ALIGN_CENTER);

  ui_PMbinghuanlist = lv_label_create(ui_PMlist);
  lv_obj_set_width(ui_PMbinghuanlist, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_PMbinghuanlist, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_PMbinghuanlist, 4);
  lv_obj_set_y(ui_PMbinghuanlist, 0);
  lv_obj_set_align(ui_PMbinghuanlist, LV_ALIGN_OUT_TOP_MID);
  lv_obj_clear_flag(ui_PMbinghuanlist, LV_OBJ_FLAG_SCROLLABLE);

  // 下午的候诊病患列表
  lv_obj_set_style_text_color(ui_PMbinghuanlist, lv_color_hex(0x3F03FC), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_PMbinghuanlist, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_letter_space(ui_PMbinghuanlist, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_line_space(ui_PMbinghuanlist, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_PMbinghuanlist, &ui_font_CHINESEsize25, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_PMtime = lv_label_create(ui_AMandPM);
  lv_obj_set_width(ui_PMtime, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_PMtime, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_PMtime, -2);
  lv_obj_set_y(ui_PMtime, 18);
  lv_obj_set_align(ui_PMtime, LV_ALIGN_CENTER);
  lv_label_set_text(ui_PMtime, "下午 2:00-17:30");
  lv_obj_set_style_text_color(ui_PMtime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_PMtime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_letter_space(ui_PMtime, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_line_space(ui_PMtime, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_PMtime, &ui_font_CHINESEsize25, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_jiuzhenzhong = lv_obj_create(ui_houzhenqu);
  lv_obj_set_width(ui_jiuzhenzhong, 230);
  lv_obj_set_height(ui_jiuzhenzhong, 169);
  lv_obj_set_x(ui_jiuzhenzhong, -158);
  lv_obj_set_y(ui_jiuzhenzhong, -138);
  lv_obj_set_align(ui_jiuzhenzhong, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_jiuzhenzhong, LV_OBJ_FLAG_SCROLLABLE); /// Flags
  lv_obj_set_style_bg_color(ui_jiuzhenzhong, lv_color_hex(0x01C9FF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_jiuzhenzhong, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_jiuzhenzhongText = lv_label_create(ui_jiuzhenzhong);
  lv_obj_set_width(ui_jiuzhenzhongText, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_jiuzhenzhongText, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_jiuzhenzhongText, -1);
  lv_obj_set_y(ui_jiuzhenzhongText, -73);
  lv_obj_set_align(ui_jiuzhenzhongText, LV_ALIGN_CENTER);
  lv_label_set_text(ui_jiuzhenzhongText, "\n就诊中...");
  lv_obj_set_style_text_color(ui_jiuzhenzhongText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_jiuzhenzhongText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_jiuzhenzhongText, &ui_font_CHINESEsize25, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_jiuzhenzhongDropdown = lv_dropdown_create(ui_jiuzhenzhong);
  lv_dropdown_set_options(ui_jiuzhenzhongDropdown, "-o-");
  lv_dropdown_set_text(ui_jiuzhenzhongDropdown, " ");
  lv_obj_set_width(ui_jiuzhenzhongDropdown, 41);
  lv_obj_set_height(ui_jiuzhenzhongDropdown, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_jiuzhenzhongDropdown, 91);
  lv_obj_set_y(ui_jiuzhenzhongDropdown, -60);
  lv_obj_set_align(ui_jiuzhenzhongDropdown, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_jiuzhenzhongDropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
  lv_obj_set_style_text_color(ui_jiuzhenzhongDropdown, lv_color_hex(0x8701F6), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_jiuzhenzhongDropdown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_set_style_text_color(ui_jiuzhenzhongDropdown, lv_color_hex(0x8302F9), LV_PART_INDICATOR | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_jiuzhenzhongDropdown, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

  ui_binghuanNAME = lv_obj_create(ui_jiuzhenzhong);
  lv_obj_set_width(ui_binghuanNAME, 216);
  lv_obj_set_height(ui_binghuanNAME, 50);
  lv_obj_set_x(ui_binghuanNAME, 0);
  lv_obj_set_y(ui_binghuanNAME, -15);
  lv_obj_set_align(ui_binghuanNAME, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_binghuanNAME, LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_binghuanNAMElabel = lv_label_create(ui_binghuanNAME);
  lv_obj_set_width(ui_binghuanNAMElabel, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_binghuanNAMElabel, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_binghuanNAMElabel, -3);
  lv_obj_set_y(ui_binghuanNAMElabel, -3);
  lv_obj_set_align(ui_binghuanNAMElabel, LV_ALIGN_CENTER);
  // 就诊中的病患名字
  lv_obj_set_style_text_color(ui_binghuanNAMElabel, lv_color_hex(0x3F03FC), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_binghuanNAMElabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_letter_space(ui_binghuanNAMElabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_line_space(ui_binghuanNAMElabel, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_binghuanNAMElabel, &ui_font_CHINESEsize25, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_JINGAOlabel = lv_label_create(ui_jiuzhenzhong);
  lv_obj_set_width(ui_JINGAOlabel, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_JINGAOlabel, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_JINGAOlabel, 4);
  lv_obj_set_y(ui_JINGAOlabel, 43);
  lv_obj_set_align(ui_JINGAOlabel, LV_ALIGN_CENTER);
  lv_label_set_text(ui_JINGAOlabel, "病人就诊中...\n   请勿喧哗");
  lv_obj_set_style_text_color(ui_JINGAOlabel, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_JINGAOlabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_JINGAOlabel, &ui_font_CHINESEsize25, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_huhuanzhong = lv_obj_create(ui_houzhenqu);
  lv_obj_set_width(ui_huhuanzhong, 230);
  lv_obj_set_height(ui_huhuanzhong, 265);
  lv_obj_set_x(ui_huhuanzhong, -158);
  lv_obj_set_y(ui_huhuanzhong, 96);
  lv_obj_set_align(ui_huhuanzhong, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_huhuanzhong, LV_OBJ_FLAG_SCROLLABLE); /// Flags
  lv_obj_set_style_bg_color(ui_huhuanzhong, lv_color_hex(0x01C9FF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_huhuanzhong, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_huhuanzhongLABEL = lv_label_create(ui_huhuanzhong);
  lv_obj_set_width(ui_huhuanzhongLABEL, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_huhuanzhongLABEL, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_huhuanzhongLABEL, -1);
  lv_obj_set_y(ui_huhuanzhongLABEL, -110);
  lv_obj_set_align(ui_huhuanzhongLABEL, LV_ALIGN_CENTER);
  lv_label_set_text(ui_huhuanzhongLABEL, "\n呼唤中...");
  lv_obj_set_style_text_color(ui_huhuanzhongLABEL, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_huhuanzhongLABEL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_huhuanzhongLABEL, &ui_font_CHINESEsize25, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_tixing = lv_obj_create(ui_huhuanzhong);
  lv_obj_set_width(ui_tixing, 216);
  lv_obj_set_height(ui_tixing, 190);
  lv_obj_set_x(ui_tixing, 0);
  lv_obj_set_y(ui_tixing, 24);
  lv_obj_set_align(ui_tixing, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_tixing, LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_tixingNAME = lv_label_create(ui_tixing);
  lv_obj_set_width(ui_tixingNAME, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_tixingNAME, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_tixingNAME, 2);
  lv_obj_set_y(ui_tixingNAME, 15);
  lv_obj_set_align(ui_tixingNAME, LV_ALIGN_CENTER);
  // 被呼叫的病患名字
  lv_obj_set_style_text_color(ui_tixingNAME, lv_color_hex(0x3F03FC), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_tixingNAME, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_letter_space(ui_tixingNAME, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_line_space(ui_tixingNAME, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_tixingNAME, &ui_font_CHINESEsize25, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_huhuanzhongDropdown = lv_dropdown_create(ui_huhuanzhong);
  lv_dropdown_set_options(ui_huhuanzhongDropdown, "-o-\n-x-");
  lv_dropdown_set_text(ui_huhuanzhongDropdown, " ");
  lv_obj_set_width(ui_huhuanzhongDropdown, 41);
  lv_obj_set_height(ui_huhuanzhongDropdown, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_huhuanzhongDropdown, 90);
  lv_obj_set_y(ui_huhuanzhongDropdown, -107);
  lv_obj_set_align(ui_huhuanzhongDropdown, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_huhuanzhongDropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
  lv_obj_set_style_text_color(ui_huhuanzhongDropdown, lv_color_hex(0x8701F6), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_huhuanzhongDropdown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_color(ui_huhuanzhongDropdown, lv_color_hex(0x8302F9), LV_PART_INDICATOR | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_huhuanzhongDropdown, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

  //  lv_obj_add_event_cb(ui_neikeButton201, ui_event_doctorPNG1, LV_EVENT_ALL, NULL);
  lv_tabview_set_act(ui_jianjieANDhouzhen, 1, LV_ANIM_OFF); // 设置让页签默认先显示第一层
  DBG_PRINT();
  lv_obj_add_event_cb(ui_fanhui_goWINditu123, ui_event_gotoditu123, LV_EVENT_CLICKED, NULL);
  DBG_PRINT();
  lv_obj_add_event_cb(ui_jiuzhenzhongDropdown, ui_event_jiuzhenzhongDropdown, LV_EVENT_VALUE_CHANGED, NULL);

  lv_obj_add_event_cb(ui_huhuanzhongDropdown, ui_event_huhuanzhongDropdown, LV_EVENT_VALUE_CHANGED, NULL);

  DBG_MSG("ui_doctorWin_screen_init结束初始化");
}
