// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"
#include "../../ui_LoginAndRegiste.h"


void ui_ditu123_screen_init(void)
{
 
 DBG_MSG("开始初始化ditu123_screen_init");
  ui_ditu123 = lv_obj_create(NULL);
  lv_obj_clear_flag(ui_ditu123, LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_DocWinContainer = lv_obj_create(ui_ditu123);
  lv_obj_remove_style_all(ui_DocWinContainer);
  lv_obj_set_width(ui_DocWinContainer, 986);
  lv_obj_set_height(ui_DocWinContainer, 579);
  lv_obj_set_x(ui_DocWinContainer, 0);
  lv_obj_set_y(ui_DocWinContainer, -1);
  lv_obj_set_align(ui_DocWinContainer, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_DocWinContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_DocWinTabView = lv_tabview_create(ui_DocWinContainer, LV_DIR_LEFT, 200);
  lv_obj_set_width(ui_DocWinTabView, 927);
  lv_obj_set_height(ui_DocWinTabView, 453);
  lv_obj_set_x(ui_DocWinTabView, -1);
  lv_obj_set_y(ui_DocWinTabView, 46);
  lv_obj_set_align(ui_DocWinTabView, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_DocWinTabView, LV_OBJ_FLAG_SCROLLABLE); /// Flags
  lv_obj_set_style_radius(ui_DocWinTabView, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_color(ui_DocWinTabView, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_DocWinTabView, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_letter_space(ui_DocWinTabView, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_line_space(ui_DocWinTabView, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_align(ui_DocWinTabView, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_DocWinTabView, &ui_font_CHINESEsize25, LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_set_style_text_color(lv_tabview_get_tab_btns(ui_DocWinTabView), lv_color_hex(0xB800FF),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(lv_tabview_get_tab_btns(ui_DocWinTabView), 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_align(lv_tabview_get_tab_btns(ui_DocWinTabView), LV_TEXT_ALIGN_LEFT,
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(lv_tabview_get_tab_btns(ui_DocWinTabView), &ui_font_CHINESEsize25,
                             LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_ceng3 = lv_tabview_add_tab(ui_DocWinTabView, "三层");

  ui_ContainerCeng3 = lv_obj_create(ui_ceng3);
  lv_obj_remove_style_all(ui_ContainerCeng3);
  lv_obj_set_width(ui_ContainerCeng3, 625);
  lv_obj_set_height(ui_ContainerCeng3, 448);
  lv_obj_set_x(ui_ContainerCeng3, 0);
  lv_obj_set_y(ui_ContainerCeng3, 0);
  lv_obj_set_align(ui_ContainerCeng3, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_ContainerCeng3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags
  lv_obj_set_style_bg_img_src(ui_ContainerCeng3, &ui_img_ditu234_png, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_shoufutiPanel3 = lv_obj_create(ui_ContainerCeng3);
  lv_obj_set_width(ui_shoufutiPanel3, 113);
  lv_obj_set_height(ui_shoufutiPanel3, 96);
  lv_obj_set_x(ui_shoufutiPanel3, 173);
  lv_obj_set_y(ui_shoufutiPanel3, 99);
  lv_obj_set_align(ui_shoufutiPanel3, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_shoufutiPanel3, LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_shoufutiX3 = lv_img_create(ui_shoufutiPanel3);
  lv_img_set_src(ui_shoufutiX3, &ui_img_shoufutix_png);
  lv_obj_set_width(ui_shoufutiX3, LV_SIZE_CONTENT);  /// 48
  lv_obj_set_height(ui_shoufutiX3, LV_SIZE_CONTENT); /// 48
  lv_obj_set_x(ui_shoufutiX3, 28);
  lv_obj_set_y(ui_shoufutiX3, 19);
  lv_obj_set_align(ui_shoufutiX3, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_shoufutiX3, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
  lv_obj_clear_flag(ui_shoufutiX3, LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_shoufutiS3 = lv_img_create(ui_shoufutiPanel3);
  lv_img_set_src(ui_shoufutiS3, &ui_img_shoufutiis_png);
  lv_obj_set_width(ui_shoufutiS3, LV_SIZE_CONTENT);  /// 48
  lv_obj_set_height(ui_shoufutiS3, LV_SIZE_CONTENT); /// 48
  lv_obj_set_x(ui_shoufutiS3, 28);
  lv_obj_set_y(ui_shoufutiS3, -22);
  lv_obj_set_align(ui_shoufutiS3, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_shoufutiS3, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
  lv_obj_clear_flag(ui_shoufutiS3, LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_shoufutiText3 = lv_label_create(ui_shoufutiPanel3);
  lv_obj_set_width(ui_shoufutiText3, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_shoufutiText3, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_shoufutiText3, -21);
  lv_obj_set_y(ui_shoufutiText3, -2);
  lv_obj_set_align(ui_shoufutiText3, LV_ALIGN_CENTER);
  lv_label_set_text(ui_shoufutiText3, "手\n扶\n梯");
  lv_obj_set_style_text_color(ui_shoufutiText3, lv_color_hex(0x7700FF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_shoufutiText3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_letter_space(ui_shoufutiText3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_line_space(ui_shoufutiText3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_cesuo3 = lv_img_create(ui_ContainerCeng3);
  lv_img_set_src(ui_cesuo3, &ui_img_cesuo_png);
  lv_obj_set_width(ui_cesuo3, LV_SIZE_CONTENT);  /// 48
  lv_obj_set_height(ui_cesuo3, LV_SIZE_CONTENT); /// 48
  lv_obj_set_x(ui_cesuo3, 193);
  lv_obj_set_y(ui_cesuo3, -35);
  lv_obj_set_align(ui_cesuo3, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_cesuo3, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
  lv_obj_clear_flag(ui_cesuo3, LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_sosContainer3 = lv_obj_create(ui_ContainerCeng3);
  lv_obj_remove_style_all(ui_sosContainer3);
  lv_obj_set_width(ui_sosContainer3, 100);
  lv_obj_set_height(ui_sosContainer3, 50);
  lv_obj_set_x(ui_sosContainer3, -201);
  lv_obj_set_y(ui_sosContainer3, -143);
  lv_obj_set_align(ui_sosContainer3, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_sosContainer3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_SOS3 = lv_img_create(ui_sosContainer3);
  lv_img_set_src(ui_SOS3, &ui_img_sostongdao_png);
  lv_obj_set_width(ui_SOS3, LV_SIZE_CONTENT);  /// 48
  lv_obj_set_height(ui_SOS3, LV_SIZE_CONTENT); /// 48
  lv_obj_set_x(ui_SOS3, -23);
  lv_obj_set_y(ui_SOS3, 0);
  lv_obj_set_align(ui_SOS3, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_SOS3, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
  lv_obj_clear_flag(ui_SOS3, LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_SOSlabel3 = lv_label_create(ui_sosContainer3);
  lv_obj_set_width(ui_SOSlabel3, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_SOSlabel3, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_SOSlabel3, 21);
  lv_obj_set_y(ui_SOSlabel3, 1);
  lv_obj_set_align(ui_SOSlabel3, LV_ALIGN_CENTER);
  lv_label_set_text(ui_SOSlabel3, "SOS\n");
  lv_obj_set_style_text_color(ui_SOSlabel3, lv_color_hex(0x6300FF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_SOSlabel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_letter_space(ui_SOSlabel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_line_space(ui_SOSlabel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_SOSlabel3, &ui_font_CHINESEsize25, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_kangfukeContainer = lv_obj_create(ui_ceng3);
  lv_obj_remove_style_all(ui_kangfukeContainer);
  lv_obj_set_width(ui_kangfukeContainer, 382);
  lv_obj_set_height(ui_kangfukeContainer, 249);
  lv_obj_set_x(ui_kangfukeContainer, 42);
  lv_obj_set_y(ui_kangfukeContainer, -61);
  lv_obj_set_align(ui_kangfukeContainer, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_kangfukeContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_keshi5 = lv_obj_create(ui_kangfukeContainer);
  lv_obj_set_width(ui_keshi5, 345);
  lv_obj_set_height(ui_keshi5, 73);
  lv_obj_set_x(ui_keshi5, 7);
  lv_obj_set_y(ui_keshi5, -83);
  lv_obj_set_align(ui_keshi5, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_keshi5, LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_kangfukeButton306 = lv_btn_create(ui_keshi5);
  lv_obj_set_width(ui_kangfukeButton306, 85);
  lv_obj_set_height(ui_kangfukeButton306, 50);
  lv_obj_set_x(ui_kangfukeButton306, 111);
  lv_obj_set_y(ui_kangfukeButton306, -2);
  lv_obj_set_align(ui_kangfukeButton306, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_kangfukeButton306, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
  lv_obj_clear_flag(ui_kangfukeButton306, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
  lv_obj_set_style_radius(ui_kangfukeButton306, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_color(ui_kangfukeButton306, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_kangfukeButton306, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_color(ui_kangfukeButton306, lv_color_hex(0x7A00FF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_opa(ui_kangfukeButton306, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_width(ui_kangfukeButton306, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_pad(ui_kangfukeButton306, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_shadow_color(ui_kangfukeButton306, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_shadow_opa(ui_kangfukeButton306, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_kangfuke306 = lv_label_create(ui_keshi5);
  lv_obj_set_width(ui_kangfuke306, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_kangfuke306, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_kangfuke306, 115);
  lv_obj_set_y(ui_kangfuke306, -3);
  lv_obj_set_align(ui_kangfuke306, LV_ALIGN_CENTER);
  lv_label_set_text(ui_kangfuke306, "306室 ");
  lv_obj_set_style_text_color(ui_kangfuke306, lv_color_hex(0x7000FF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_kangfuke306, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_letter_space(ui_kangfuke306, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_line_space(ui_kangfuke306, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_align(ui_kangfuke306, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_kangfuke306, &ui_font_CHINESEsize25, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_kangfukeButton305 = lv_btn_create(ui_keshi5);
  lv_obj_set_width(ui_kangfukeButton305, 85);
  lv_obj_set_height(ui_kangfukeButton305, 50);
  lv_obj_set_x(ui_kangfukeButton305, 3);
  lv_obj_set_y(ui_kangfukeButton305, -2);
  lv_obj_set_align(ui_kangfukeButton305, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_kangfukeButton305, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
  lv_obj_clear_flag(ui_kangfukeButton305, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
  lv_obj_set_style_radius(ui_kangfukeButton305, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_color(ui_kangfukeButton305, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_kangfukeButton305, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_color(ui_kangfukeButton305, lv_color_hex(0x7A00FF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_opa(ui_kangfukeButton305, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_width(ui_kangfukeButton305, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_pad(ui_kangfukeButton305, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_shadow_color(ui_kangfukeButton305, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_shadow_opa(ui_kangfukeButton305, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_kangfuke305 = lv_label_create(ui_keshi5);
  lv_obj_set_width(ui_kangfuke305, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_kangfuke305, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_kangfuke305, 2);
  lv_obj_set_y(ui_kangfuke305, -3);
  lv_obj_set_align(ui_kangfuke305, LV_ALIGN_CENTER);
  lv_label_set_text(ui_kangfuke305, "305室 ");
  lv_obj_set_style_text_color(ui_kangfuke305, lv_color_hex(0x7000FF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_kangfuke305, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_letter_space(ui_kangfuke305, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_line_space(ui_kangfuke305, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_align(ui_kangfuke305, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_kangfuke305, &ui_font_CHINESEsize25, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_kangfukeButton304 = lv_btn_create(ui_keshi5);
  lv_obj_set_width(ui_kangfukeButton304, 85);
  lv_obj_set_height(ui_kangfukeButton304, 50);
  lv_obj_set_x(ui_kangfukeButton304, -108);
  lv_obj_set_y(ui_kangfukeButton304, -2);
  lv_obj_set_align(ui_kangfukeButton304, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_kangfukeButton304, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
  lv_obj_clear_flag(ui_kangfukeButton304, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
  lv_obj_set_style_radius(ui_kangfukeButton304, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_color(ui_kangfukeButton304, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_kangfukeButton304, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_color(ui_kangfukeButton304, lv_color_hex(0x7A00FF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_opa(ui_kangfukeButton304, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_width(ui_kangfukeButton304, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_pad(ui_kangfukeButton304, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_shadow_color(ui_kangfukeButton304, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_shadow_opa(ui_kangfukeButton304, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_kangfuke304 = lv_label_create(ui_keshi5);
  lv_obj_set_width(ui_kangfuke304, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_kangfuke304, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_kangfuke304, -108);
  lv_obj_set_y(ui_kangfuke304, -4);
  lv_obj_set_align(ui_kangfuke304, LV_ALIGN_CENTER);
  lv_label_set_text(ui_kangfuke304, "304室 ");
  lv_obj_set_style_text_color(ui_kangfuke304, lv_color_hex(0x7000FF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_kangfuke304, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_letter_space(ui_kangfuke304, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_line_space(ui_kangfuke304, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_align(ui_kangfuke304, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_kangfuke304, &ui_font_CHINESEsize25, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_kangfukeLabel4 = lv_label_create(ui_kangfukeContainer);
  lv_obj_set_width(ui_kangfukeLabel4, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_kangfukeLabel4, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_kangfukeLabel4, -32);
  lv_obj_set_y(ui_kangfukeLabel4, 37);
  lv_obj_set_align(ui_kangfukeLabel4, LV_ALIGN_CENTER);
  lv_label_set_text(ui_kangfukeLabel4, "康复科");
  lv_obj_set_style_text_color(ui_kangfukeLabel4, lv_color_hex(0x6300FF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_kangfukeLabel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_letter_space(ui_kangfukeLabel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_line_space(ui_kangfukeLabel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_kangfukeLabel4, &ui_font_CHINESEsize25, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_kangfuke = lv_img_create(ui_kangfukeContainer);
  lv_img_set_src(ui_kangfuke, &ui_img_kangfuke_png);
  lv_obj_set_width(ui_kangfuke, LV_SIZE_CONTENT);  /// 48
  lv_obj_set_height(ui_kangfuke, LV_SIZE_CONTENT); /// 48
  lv_obj_set_x(ui_kangfuke, -33);
  lv_obj_set_y(ui_kangfuke, 5);
  lv_obj_set_align(ui_kangfuke, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_kangfuke, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
  lv_obj_clear_flag(ui_kangfuke, LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_neikeContainer1 = lv_obj_create(ui_ceng3);
  lv_obj_remove_style_all(ui_neikeContainer1);
  lv_obj_set_width(ui_neikeContainer1, 174);
  lv_obj_set_height(ui_neikeContainer1, 244);
  lv_obj_set_x(ui_neikeContainer1, -158);
  lv_obj_set_y(ui_neikeContainer1, 35);
  lv_obj_set_align(ui_neikeContainer1, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_neikeContainer1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_keshi3 = lv_obj_create(ui_neikeContainer1);
  lv_obj_set_width(ui_keshi3, 94);
  lv_obj_set_height(ui_keshi3, 229);
  lv_obj_set_x(ui_keshi3, -35);
  lv_obj_set_y(ui_keshi3, 2);
  lv_obj_set_align(ui_keshi3, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_keshi3, LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_zhongyikeButton303 = lv_btn_create(ui_keshi3);
  lv_obj_set_width(ui_zhongyikeButton303, 85);
  lv_obj_set_height(ui_zhongyikeButton303, 50);
  lv_obj_set_x(ui_zhongyikeButton303, 0);
  lv_obj_set_y(ui_zhongyikeButton303, -70);
  lv_obj_set_align(ui_zhongyikeButton303, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_zhongyikeButton303, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
  lv_obj_clear_flag(ui_zhongyikeButton303, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
  lv_obj_set_style_radius(ui_zhongyikeButton303, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_color(ui_zhongyikeButton303, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_zhongyikeButton303, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_color(ui_zhongyikeButton303, lv_color_hex(0x7A00FF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_opa(ui_zhongyikeButton303, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_width(ui_zhongyikeButton303, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_pad(ui_zhongyikeButton303, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_shadow_color(ui_zhongyikeButton303, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_shadow_opa(ui_zhongyikeButton303, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_zhongyikeLabel303 = lv_label_create(ui_keshi3);
  lv_obj_set_width(ui_zhongyikeLabel303, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_zhongyikeLabel303, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_zhongyikeLabel303, 3);
  lv_obj_set_y(ui_zhongyikeLabel303, -69);
  lv_obj_set_align(ui_zhongyikeLabel303, LV_ALIGN_CENTER);
  lv_label_set_text(ui_zhongyikeLabel303, "303室 ");
  lv_obj_set_style_text_color(ui_zhongyikeLabel303, lv_color_hex(0x7000FF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_zhongyikeLabel303, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_letter_space(ui_zhongyikeLabel303, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_line_space(ui_zhongyikeLabel303, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_align(ui_zhongyikeLabel303, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_zhongyikeLabel303, &ui_font_CHINESEsize25, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_zhongyikeButton302 = lv_btn_create(ui_keshi3);
  lv_obj_set_width(ui_zhongyikeButton302, 85);
  lv_obj_set_height(ui_zhongyikeButton302, 50);
  lv_obj_set_x(ui_zhongyikeButton302, -1);
  lv_obj_set_y(ui_zhongyikeButton302, 1);
  lv_obj_set_align(ui_zhongyikeButton302, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_zhongyikeButton302, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
  lv_obj_clear_flag(ui_zhongyikeButton302, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
  lv_obj_set_style_radius(ui_zhongyikeButton302, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_color(ui_zhongyikeButton302, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_zhongyikeButton302, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_color(ui_zhongyikeButton302, lv_color_hex(0x7A00FF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_opa(ui_zhongyikeButton302, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_width(ui_zhongyikeButton302, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_pad(ui_zhongyikeButton302, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_shadow_color(ui_zhongyikeButton302, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_shadow_opa(ui_zhongyikeButton302, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_zhongyikeLabel302 = lv_label_create(ui_keshi3);
  lv_obj_set_width(ui_zhongyikeLabel302, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_zhongyikeLabel302, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_zhongyikeLabel302, 3);
  lv_obj_set_y(ui_zhongyikeLabel302, 2);
  lv_obj_set_align(ui_zhongyikeLabel302, LV_ALIGN_CENTER);
  lv_label_set_text(ui_zhongyikeLabel302, "302室 ");
  lv_obj_set_style_text_color(ui_zhongyikeLabel302, lv_color_hex(0x7000FF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_zhongyikeLabel302, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_letter_space(ui_zhongyikeLabel302, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_line_space(ui_zhongyikeLabel302, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_align(ui_zhongyikeLabel302, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_zhongyikeLabel302, &ui_font_CHINESEsize25, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_zhongyikeButton301 = lv_btn_create(ui_keshi3);
  lv_obj_set_width(ui_zhongyikeButton301, 85);
  lv_obj_set_height(ui_zhongyikeButton301, 50);
  lv_obj_set_x(ui_zhongyikeButton301, -1);
  lv_obj_set_y(ui_zhongyikeButton301, 74);
  lv_obj_set_align(ui_zhongyikeButton301, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_zhongyikeButton301, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
  lv_obj_clear_flag(ui_zhongyikeButton301, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
  lv_obj_set_style_radius(ui_zhongyikeButton301, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_color(ui_zhongyikeButton301, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_zhongyikeButton301, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_color(ui_zhongyikeButton301, lv_color_hex(0x7A00FF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_opa(ui_zhongyikeButton301, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_width(ui_zhongyikeButton301, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_pad(ui_zhongyikeButton301, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_shadow_color(ui_zhongyikeButton301, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_shadow_opa(ui_zhongyikeButton301, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_zhongyikeLabel301 = lv_label_create(ui_keshi3);
  lv_obj_set_width(ui_zhongyikeLabel301, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_zhongyikeLabel301, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_zhongyikeLabel301, 2);
  lv_obj_set_y(ui_zhongyikeLabel301, 74);
  lv_obj_set_align(ui_zhongyikeLabel301, LV_ALIGN_CENTER);
  lv_label_set_text(ui_zhongyikeLabel301, "301室 ");
  lv_obj_set_style_text_color(ui_zhongyikeLabel301, lv_color_hex(0x7000FF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_zhongyikeLabel301, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_letter_space(ui_zhongyikeLabel301, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_line_space(ui_zhongyikeLabel301, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_align(ui_zhongyikeLabel301, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_zhongyikeLabel301, &ui_font_CHINESEsize25, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_zhongyikeLabel4 = lv_label_create(ui_neikeContainer1);
  lv_obj_set_width(ui_zhongyikeLabel4, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_zhongyikeLabel4, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_zhongyikeLabel4, 51);
  lv_obj_set_y(ui_zhongyikeLabel4, 36);
  lv_obj_set_align(ui_zhongyikeLabel4, LV_ALIGN_CENTER);
  lv_label_set_text(ui_zhongyikeLabel4, "中医科");
  lv_obj_set_style_text_color(ui_zhongyikeLabel4, lv_color_hex(0x6300FF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_zhongyikeLabel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_letter_space(ui_zhongyikeLabel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_line_space(ui_zhongyikeLabel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_zhongyikeLabel4, &ui_font_CHINESEsize25, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_neike1 = lv_img_create(ui_neikeContainer1);
  lv_img_set_src(ui_neike1, &ui_img_zhongyike_png);
  lv_obj_set_width(ui_neike1, LV_SIZE_CONTENT);  /// 48
  lv_obj_set_height(ui_neike1, LV_SIZE_CONTENT); /// 48
  lv_obj_set_x(ui_neike1, 51);
  lv_obj_set_y(ui_neike1, -25);
  lv_obj_set_align(ui_neike1, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_neike1, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
  lv_obj_clear_flag(ui_neike1, LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_houzhenquPanel3 = lv_obj_create(ui_ceng3);
  lv_obj_set_width(ui_houzhenquPanel3, 138);
  lv_obj_set_height(ui_houzhenquPanel3, 113);
  lv_obj_set_x(ui_houzhenquPanel3, 21);
  lv_obj_set_y(ui_houzhenquPanel3, 77);
  lv_obj_set_align(ui_houzhenquPanel3, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_houzhenquPanel3, LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_houzhenqu3 = lv_img_create(ui_houzhenquPanel3);
  lv_img_set_src(ui_houzhenqu3, &ui_img_denghouqu_png);
  lv_obj_set_width(ui_houzhenqu3, LV_SIZE_CONTENT);  /// 52
  lv_obj_set_height(ui_houzhenqu3, LV_SIZE_CONTENT); /// 48
  lv_obj_set_x(ui_houzhenqu3, -6);
  lv_obj_set_y(ui_houzhenqu3, -20);
  lv_obj_set_align(ui_houzhenqu3, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_houzhenqu3, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
  lv_obj_clear_flag(ui_houzhenqu3, LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_houzhenquLabel3 = lv_label_create(ui_houzhenquPanel3);
  lv_obj_set_width(ui_houzhenquLabel3, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_houzhenquLabel3, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_houzhenquLabel3, -1);
  lv_obj_set_y(ui_houzhenquLabel3, 27);
  lv_obj_set_align(ui_houzhenquLabel3, LV_ALIGN_CENTER);
  lv_label_set_text(ui_houzhenquLabel3, "候诊区");
  lv_obj_set_style_text_color(ui_houzhenquLabel3, lv_color_hex(0x6300FF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_houzhenquLabel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_letter_space(ui_houzhenquLabel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_line_space(ui_houzhenquLabel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_align(ui_houzhenquLabel3, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_houzhenquLabel3, &ui_font_CHINESEsize25, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_ceng2 = lv_tabview_add_tab(ui_DocWinTabView, "二层");
  lv_obj_set_style_bg_img_src(ui_ceng2, &ui_img_ditu234_png, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_ContainerCeng2 = lv_obj_create(ui_ceng2);
  lv_obj_remove_style_all(ui_ContainerCeng2);
  lv_obj_set_width(ui_ContainerCeng2, 625);
  lv_obj_set_height(ui_ContainerCeng2, 448);
  lv_obj_set_x(ui_ContainerCeng2, 0);
  lv_obj_set_y(ui_ContainerCeng2, 0);
  lv_obj_set_align(ui_ContainerCeng2, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_ContainerCeng2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_shoufutiPanel2 = lv_obj_create(ui_ContainerCeng2);
  lv_obj_set_width(ui_shoufutiPanel2, 113);
  lv_obj_set_height(ui_shoufutiPanel2, 96);
  lv_obj_set_x(ui_shoufutiPanel2, 173);
  lv_obj_set_y(ui_shoufutiPanel2, 99);
  lv_obj_set_align(ui_shoufutiPanel2, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_shoufutiPanel2, LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_shoufutiX2 = lv_img_create(ui_shoufutiPanel2);
  lv_img_set_src(ui_shoufutiX2, &ui_img_shoufutix_png);
  lv_obj_set_width(ui_shoufutiX2, LV_SIZE_CONTENT);  /// 48
  lv_obj_set_height(ui_shoufutiX2, LV_SIZE_CONTENT); /// 48
  lv_obj_set_x(ui_shoufutiX2, 28);
  lv_obj_set_y(ui_shoufutiX2, 19);
  lv_obj_set_align(ui_shoufutiX2, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_shoufutiX2, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
  lv_obj_clear_flag(ui_shoufutiX2, LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_shoufutiS2 = lv_img_create(ui_shoufutiPanel2);
  lv_img_set_src(ui_shoufutiS2, &ui_img_shoufutiis_png);
  lv_obj_set_width(ui_shoufutiS2, LV_SIZE_CONTENT);  /// 48
  lv_obj_set_height(ui_shoufutiS2, LV_SIZE_CONTENT); /// 48
  lv_obj_set_x(ui_shoufutiS2, 28);
  lv_obj_set_y(ui_shoufutiS2, -22);
  lv_obj_set_align(ui_shoufutiS2, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_shoufutiS2, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
  lv_obj_clear_flag(ui_shoufutiS2, LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_shoufutiText2 = lv_label_create(ui_shoufutiPanel2);
  lv_obj_set_width(ui_shoufutiText2, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_shoufutiText2, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_shoufutiText2, -21);
  lv_obj_set_y(ui_shoufutiText2, -2);
  lv_obj_set_align(ui_shoufutiText2, LV_ALIGN_CENTER);
  lv_label_set_text(ui_shoufutiText2, "手\n扶\n梯");
  lv_obj_set_style_text_color(ui_shoufutiText2, lv_color_hex(0x7700FF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_shoufutiText2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_letter_space(ui_shoufutiText2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_line_space(ui_shoufutiText2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_waikeContainer = lv_obj_create(ui_ContainerCeng2);
  lv_obj_remove_style_all(ui_waikeContainer);
  lv_obj_set_width(ui_waikeContainer, 342);
  lv_obj_set_height(ui_waikeContainer, 249);
  lv_obj_set_x(ui_waikeContainer, 56);
  lv_obj_set_y(ui_waikeContainer, -57);
  lv_obj_set_align(ui_waikeContainer, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_waikeContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_keshi1 = lv_obj_create(ui_waikeContainer);
  lv_obj_set_width(ui_keshi1, 345);
  lv_obj_set_height(ui_keshi1, 73);
  lv_obj_set_x(ui_keshi1, 7);
  lv_obj_set_y(ui_keshi1, -83);
  lv_obj_set_align(ui_keshi1, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_keshi1, LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_waikeButton206 = lv_btn_create(ui_keshi1);
  lv_obj_set_width(ui_waikeButton206, 85);
  lv_obj_set_height(ui_waikeButton206, 50);
  lv_obj_set_x(ui_waikeButton206, 111);
  lv_obj_set_y(ui_waikeButton206, -2);
  lv_obj_set_align(ui_waikeButton206, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_waikeButton206, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
  lv_obj_clear_flag(ui_waikeButton206, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
  lv_obj_set_style_radius(ui_waikeButton206, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_color(ui_waikeButton206, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_waikeButton206, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_color(ui_waikeButton206, lv_color_hex(0x7A00FF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_opa(ui_waikeButton206, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_width(ui_waikeButton206, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_pad(ui_waikeButton206, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_shadow_color(ui_waikeButton206, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_shadow_opa(ui_waikeButton206, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_waikeLabel206 = lv_label_create(ui_keshi1);
  lv_obj_set_width(ui_waikeLabel206, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_waikeLabel206, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_waikeLabel206, 113);
  lv_obj_set_y(ui_waikeLabel206, -1);
  lv_obj_set_align(ui_waikeLabel206, LV_ALIGN_CENTER);
  lv_label_set_text(ui_waikeLabel206, "206室 ");
  lv_obj_set_style_text_color(ui_waikeLabel206, lv_color_hex(0x7000FF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_waikeLabel206, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_letter_space(ui_waikeLabel206, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_line_space(ui_waikeLabel206, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_align(ui_waikeLabel206, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_waikeLabel206, &ui_font_CHINESEsize25, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_waikeButton205 = lv_btn_create(ui_keshi1);
  lv_obj_set_width(ui_waikeButton205, 85);
  lv_obj_set_height(ui_waikeButton205, 50);
  lv_obj_set_x(ui_waikeButton205, 3);
  lv_obj_set_y(ui_waikeButton205, -2);
  lv_obj_set_align(ui_waikeButton205, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_waikeButton205, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
  lv_obj_clear_flag(ui_waikeButton205, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
  lv_obj_set_style_radius(ui_waikeButton205, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_color(ui_waikeButton205, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_waikeButton205, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_color(ui_waikeButton205, lv_color_hex(0x7A00FF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_opa(ui_waikeButton205, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_width(ui_waikeButton205, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_pad(ui_waikeButton205, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_shadow_color(ui_waikeButton205, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_shadow_opa(ui_waikeButton205, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_waikeLabel205 = lv_label_create(ui_keshi1);
  lv_obj_set_width(ui_waikeLabel205, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_waikeLabel205, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_waikeLabel205, 7);
  lv_obj_set_y(ui_waikeLabel205, -2);
  lv_obj_set_align(ui_waikeLabel205, LV_ALIGN_CENTER);
  lv_label_set_text(ui_waikeLabel205, "205室 ");
  lv_obj_set_style_text_color(ui_waikeLabel205, lv_color_hex(0x7000FF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_waikeLabel205, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_letter_space(ui_waikeLabel205, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_line_space(ui_waikeLabel205, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_align(ui_waikeLabel205, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_waikeLabel205, &ui_font_CHINESEsize25, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_waikeButton204 = lv_btn_create(ui_keshi1);
  lv_obj_set_width(ui_waikeButton204, 85);
  lv_obj_set_height(ui_waikeButton204, 50);
  lv_obj_set_x(ui_waikeButton204, -108);
  lv_obj_set_y(ui_waikeButton204, -2);
  lv_obj_set_align(ui_waikeButton204, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_waikeButton204, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
  lv_obj_clear_flag(ui_waikeButton204, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
  lv_obj_set_style_radius(ui_waikeButton204, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_color(ui_waikeButton204, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_waikeButton204, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_color(ui_waikeButton204, lv_color_hex(0x7A00FF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_opa(ui_waikeButton204, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_width(ui_waikeButton204, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_pad(ui_waikeButton204, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_shadow_color(ui_waikeButton204, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_shadow_opa(ui_waikeButton204, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_waikeLabel204 = lv_label_create(ui_keshi1);
  lv_obj_set_width(ui_waikeLabel204, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_waikeLabel204, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_waikeLabel204, -100);
  lv_obj_set_y(ui_waikeLabel204, -3);
  lv_obj_set_align(ui_waikeLabel204, LV_ALIGN_CENTER);
  lv_label_set_text(ui_waikeLabel204, "204室 ");
  lv_obj_set_style_text_color(ui_waikeLabel204, lv_color_hex(0x7000FF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_waikeLabel204, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_letter_space(ui_waikeLabel204, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_line_space(ui_waikeLabel204, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_align(ui_waikeLabel204, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_waikeLabel204, &ui_font_CHINESEsize25, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_waike = lv_img_create(ui_waikeContainer);
  lv_img_set_src(ui_waike, &ui_img_waike_png);
  lv_obj_set_width(ui_waike, LV_SIZE_CONTENT);  /// 48
  lv_obj_set_height(ui_waike, LV_SIZE_CONTENT); /// 48
  lv_obj_set_x(ui_waike, -33);
  lv_obj_set_y(ui_waike, -5);
  lv_obj_set_align(ui_waike, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_waike, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
  lv_obj_clear_flag(ui_waike, LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_waikeLabel = lv_label_create(ui_waikeContainer);
  lv_obj_set_width(ui_waikeLabel, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_waikeLabel, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_waikeLabel, -32);
  lv_obj_set_y(ui_waikeLabel, 37);
  lv_obj_set_align(ui_waikeLabel, LV_ALIGN_CENTER);
  lv_label_set_text(ui_waikeLabel, "外科");
  lv_obj_set_style_text_color(ui_waikeLabel, lv_color_hex(0x6300FF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_waikeLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_letter_space(ui_waikeLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_line_space(ui_waikeLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_waikeLabel, &ui_font_CHINESEsize25, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_sosContainer = lv_obj_create(ui_ContainerCeng2);
  lv_obj_remove_style_all(ui_sosContainer);
  lv_obj_set_width(ui_sosContainer, 100);
  lv_obj_set_height(ui_sosContainer, 50);
  lv_obj_set_x(ui_sosContainer, -201);
  lv_obj_set_y(ui_sosContainer, -143);
  lv_obj_set_align(ui_sosContainer, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_sosContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_SOS = lv_img_create(ui_sosContainer);
  lv_img_set_src(ui_SOS, &ui_img_sostongdao_png);
  lv_obj_set_width(ui_SOS, LV_SIZE_CONTENT);  /// 48
  lv_obj_set_height(ui_SOS, LV_SIZE_CONTENT); /// 48
  lv_obj_set_x(ui_SOS, -23);
  lv_obj_set_y(ui_SOS, 0);
  lv_obj_set_align(ui_SOS, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_SOS, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
  lv_obj_clear_flag(ui_SOS, LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_SOSlabel = lv_label_create(ui_sosContainer);
  lv_obj_set_width(ui_SOSlabel, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_SOSlabel, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_SOSlabel, 21);
  lv_obj_set_y(ui_SOSlabel, 1);
  lv_obj_set_align(ui_SOSlabel, LV_ALIGN_CENTER);
  lv_label_set_text(ui_SOSlabel, "SOS\n");
  lv_obj_set_style_text_color(ui_SOSlabel, lv_color_hex(0x6300FF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_SOSlabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_letter_space(ui_SOSlabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_line_space(ui_SOSlabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_SOSlabel, &ui_font_CHINESEsize25, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_cesuo2 = lv_img_create(ui_ContainerCeng2);
  lv_img_set_src(ui_cesuo2, &ui_img_cesuo_png);
  lv_obj_set_width(ui_cesuo2, LV_SIZE_CONTENT);  /// 48
  lv_obj_set_height(ui_cesuo2, LV_SIZE_CONTENT); /// 48
  lv_obj_set_x(ui_cesuo2, 191);
  lv_obj_set_y(ui_cesuo2, -40);
  lv_obj_set_align(ui_cesuo2, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_cesuo2, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
  lv_obj_clear_flag(ui_cesuo2, LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_neikeContainer = lv_obj_create(ui_ContainerCeng2);
  lv_obj_remove_style_all(ui_neikeContainer);
  lv_obj_set_width(ui_neikeContainer, 174);
  lv_obj_set_height(ui_neikeContainer, 244);
  lv_obj_set_x(ui_neikeContainer, -158);
  lv_obj_set_y(ui_neikeContainer, 35);
  lv_obj_set_align(ui_neikeContainer, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_neikeContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_keshi2 = lv_obj_create(ui_neikeContainer);
  lv_obj_set_width(ui_keshi2, 94);
  lv_obj_set_height(ui_keshi2, 229);
  lv_obj_set_x(ui_keshi2, -35);
  lv_obj_set_y(ui_keshi2, 2);
  lv_obj_set_align(ui_keshi2, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_keshi2, LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_neikeButton203 = lv_btn_create(ui_keshi2);
  lv_obj_set_width(ui_neikeButton203, 85);
  lv_obj_set_height(ui_neikeButton203, 50);
  lv_obj_set_x(ui_neikeButton203, 0);
  lv_obj_set_y(ui_neikeButton203, -70);
  lv_obj_set_align(ui_neikeButton203, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_neikeButton203, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
  lv_obj_clear_flag(ui_neikeButton203, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
  lv_obj_set_style_radius(ui_neikeButton203, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_color(ui_neikeButton203, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_neikeButton203, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_color(ui_neikeButton203, lv_color_hex(0x7A00FF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_opa(ui_neikeButton203, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_width(ui_neikeButton203, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_pad(ui_neikeButton203, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_shadow_color(ui_neikeButton203, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_shadow_opa(ui_neikeButton203, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_neikeLabel203 = lv_label_create(ui_keshi2);
  lv_obj_set_width(ui_neikeLabel203, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_neikeLabel203, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_neikeLabel203, 3);
  lv_obj_set_y(ui_neikeLabel203, -69);
  lv_obj_set_align(ui_neikeLabel203, LV_ALIGN_CENTER);
  lv_label_set_text(ui_neikeLabel203, "203室 ");
  lv_obj_set_style_text_color(ui_neikeLabel203, lv_color_hex(0x7000FF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_neikeLabel203, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_letter_space(ui_neikeLabel203, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_line_space(ui_neikeLabel203, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_align(ui_neikeLabel203, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_neikeLabel203, &ui_font_CHINESEsize25, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_neikeButton202 = lv_btn_create(ui_keshi2);
  lv_obj_set_width(ui_neikeButton202, 85);
  lv_obj_set_height(ui_neikeButton202, 50);
  lv_obj_set_x(ui_neikeButton202, -1);
  lv_obj_set_y(ui_neikeButton202, 1);
  lv_obj_set_align(ui_neikeButton202, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_neikeButton202, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
  lv_obj_clear_flag(ui_neikeButton202, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
  lv_obj_set_style_radius(ui_neikeButton202, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_color(ui_neikeButton202, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_neikeButton202, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_color(ui_neikeButton202, lv_color_hex(0x7A00FF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_opa(ui_neikeButton202, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_width(ui_neikeButton202, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_pad(ui_neikeButton202, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_shadow_color(ui_neikeButton202, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_shadow_opa(ui_neikeButton202, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_neikeLabel202 = lv_label_create(ui_keshi2);
  lv_obj_set_width(ui_neikeLabel202, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_neikeLabel202, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_neikeLabel202, 3);
  lv_obj_set_y(ui_neikeLabel202, 2);
  lv_obj_set_align(ui_neikeLabel202, LV_ALIGN_CENTER);
  lv_label_set_text(ui_neikeLabel202, "202室 ");
  lv_obj_set_style_text_color(ui_neikeLabel202, lv_color_hex(0x7000FF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_neikeLabel202, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_letter_space(ui_neikeLabel202, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_line_space(ui_neikeLabel202, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_align(ui_neikeLabel202, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_neikeLabel202, &ui_font_CHINESEsize25, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_neikeButton201 = lv_btn_create(ui_keshi2);
  lv_obj_set_width(ui_neikeButton201, 85);
  lv_obj_set_height(ui_neikeButton201, 50);
  lv_obj_set_x(ui_neikeButton201, -1);
  lv_obj_set_y(ui_neikeButton201, 74);
  lv_obj_set_align(ui_neikeButton201, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_neikeButton201, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
  lv_obj_clear_flag(ui_neikeButton201, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
  lv_obj_set_style_radius(ui_neikeButton201, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_color(ui_neikeButton201, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_neikeButton201, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_color(ui_neikeButton201, lv_color_hex(0x7A00FF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_opa(ui_neikeButton201, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_width(ui_neikeButton201, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_pad(ui_neikeButton201, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_shadow_color(ui_neikeButton201, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_shadow_opa(ui_neikeButton201, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_neikeLabel1 = lv_label_create(ui_neikeContainer);
  lv_obj_set_width(ui_neikeLabel1, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_neikeLabel1, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_neikeLabel1, 51);
  lv_obj_set_y(ui_neikeLabel1, 36);
  lv_obj_set_align(ui_neikeLabel1, LV_ALIGN_CENTER);
  lv_label_set_text(ui_neikeLabel1, "内科");
  lv_obj_set_style_text_color(ui_neikeLabel1, lv_color_hex(0x6300FF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_neikeLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_letter_space(ui_neikeLabel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_line_space(ui_neikeLabel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_neikeLabel1, &ui_font_CHINESEsize25, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_neikeLabel201 = lv_label_create(ui_neikeContainer);
  lv_obj_set_width(ui_neikeLabel201, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_neikeLabel201, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_neikeLabel201, -33);
  lv_obj_set_y(ui_neikeLabel201, 81);
  lv_obj_set_align(ui_neikeLabel201, LV_ALIGN_CENTER);
  lv_label_set_text(ui_neikeLabel201, "201室 ");
  lv_obj_set_style_text_color(ui_neikeLabel201, lv_color_hex(0x7000FF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_neikeLabel201, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_letter_space(ui_neikeLabel201, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_line_space(ui_neikeLabel201, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_align(ui_neikeLabel201, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_neikeLabel201, &ui_font_CHINESEsize25, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_neike = lv_img_create(ui_neikeContainer);
  lv_img_set_src(ui_neike, &ui_img_neike_png);
  lv_obj_set_width(ui_neike, LV_SIZE_CONTENT);  /// 48
  lv_obj_set_height(ui_neike, LV_SIZE_CONTENT); /// 48
  lv_obj_set_x(ui_neike, 51);
  lv_obj_set_y(ui_neike, -25);
  lv_obj_set_align(ui_neike, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_neike, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
  lv_obj_clear_flag(ui_neike, LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_houzhenquPanel2 = lv_obj_create(ui_ceng2);
  lv_obj_set_width(ui_houzhenquPanel2, 138);
  lv_obj_set_height(ui_houzhenquPanel2, 113);
  lv_obj_set_x(ui_houzhenquPanel2, 14);
  lv_obj_set_y(ui_houzhenquPanel2, 80);
  lv_obj_set_align(ui_houzhenquPanel2, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_houzhenquPanel2, LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_houzhenqu2 = lv_img_create(ui_houzhenquPanel2);
  lv_img_set_src(ui_houzhenqu2, &ui_img_denghouqu_png);
  lv_obj_set_width(ui_houzhenqu2, LV_SIZE_CONTENT);  /// 52
  lv_obj_set_height(ui_houzhenqu2, LV_SIZE_CONTENT); /// 48
  lv_obj_set_x(ui_houzhenqu2, -6);
  lv_obj_set_y(ui_houzhenqu2, -20);
  lv_obj_set_align(ui_houzhenqu2, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_houzhenqu2, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
  lv_obj_clear_flag(ui_houzhenqu2, LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_houzhenquLabel2 = lv_label_create(ui_houzhenquPanel2);
  lv_obj_set_width(ui_houzhenquLabel2, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_houzhenquLabel2, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_houzhenquLabel2, -1);
  lv_obj_set_y(ui_houzhenquLabel2, 27);
  lv_obj_set_align(ui_houzhenquLabel2, LV_ALIGN_CENTER);
  lv_label_set_text(ui_houzhenquLabel2, "候诊区");
  lv_obj_set_style_text_color(ui_houzhenquLabel2, lv_color_hex(0x6300FF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_houzhenquLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_letter_space(ui_houzhenquLabel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_line_space(ui_houzhenquLabel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_align(ui_houzhenquLabel2, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_houzhenquLabel2, &ui_font_CHINESEsize25, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_ceng1 = lv_tabview_add_tab(ui_DocWinTabView, "一层");

  ui_bgContainer = lv_obj_create(ui_ceng1);
  lv_obj_remove_style_all(ui_bgContainer);
  lv_obj_set_width(ui_bgContainer, 696);
  lv_obj_set_height(ui_bgContainer, 448);
  lv_obj_set_x(ui_bgContainer, 0);
  lv_obj_set_y(ui_bgContainer, 0);
  lv_obj_set_align(ui_bgContainer, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_bgContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                                        LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags
  lv_obj_set_style_radius(ui_bgContainer, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_color(ui_bgContainer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_bgContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_img_src(ui_bgContainer, &ui_img_ditu1_png, LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_set_style_radius(ui_bgContainer, 20, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_color(ui_bgContainer, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_bgContainer, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

  ui_damen = lv_img_create(ui_ceng1);
  lv_img_set_src(ui_damen, &ui_img_damen_png);
  lv_obj_set_width(ui_damen, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_damen, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_damen, -13);
  lv_obj_set_y(ui_damen, 178);
  lv_obj_set_align(ui_damen, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_damen, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
  lv_obj_clear_flag(ui_damen, LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_denghouqu1Panel = lv_obj_create(ui_ceng1);
  lv_obj_set_width(ui_denghouqu1Panel, 227);
  lv_obj_set_height(ui_denghouqu1Panel, 147);
  lv_obj_set_x(ui_denghouqu1Panel, -17);
  lv_obj_set_y(ui_denghouqu1Panel, 27);
  lv_obj_set_align(ui_denghouqu1Panel, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_denghouqu1Panel, LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_denghouqu1 = lv_img_create(ui_denghouqu1Panel);
  lv_img_set_src(ui_denghouqu1, &ui_img_denghouqu_png);
  lv_obj_set_width(ui_denghouqu1, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_denghouqu1, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_denghouqu1, -2);
  lv_obj_set_y(ui_denghouqu1, -14);
  lv_obj_set_align(ui_denghouqu1, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_denghouqu1, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
  lv_obj_clear_flag(ui_denghouqu1, LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_Label3 = lv_label_create(ui_denghouqu1Panel);
  lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_Label3, 0);
  lv_obj_set_y(ui_Label3, 31);
  lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
  lv_label_set_text(ui_Label3, "等候区");
  lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0x7000FF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_letter_space(ui_Label3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_line_space(ui_Label3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_align(ui_Label3, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_Label3, &ui_font_CHINESEsize25, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_jiaofeichuPanel1 = lv_obj_create(ui_ceng1);
  lv_obj_set_width(ui_jiaofeichuPanel1, 69);
  lv_obj_set_height(ui_jiaofeichuPanel1, 265);
  lv_obj_set_x(ui_jiaofeichuPanel1, -215);
  lv_obj_set_y(ui_jiaofeichuPanel1, 33);
  lv_obj_set_align(ui_jiaofeichuPanel1, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_jiaofeichuPanel1, LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_jiaofeiLabel = lv_label_create(ui_jiaofeichuPanel1);
  lv_obj_set_width(ui_jiaofeiLabel, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_jiaofeiLabel, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_jiaofeiLabel, 2);
  lv_obj_set_y(ui_jiaofeiLabel, 108);
  lv_obj_set_align(ui_jiaofeiLabel, LV_ALIGN_CENTER);
  lv_label_set_text(ui_jiaofeiLabel, "缴费");
  lv_obj_set_style_text_color(ui_jiaofeiLabel, lv_color_hex(0x7000FF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_jiaofeiLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_letter_space(ui_jiaofeiLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_line_space(ui_jiaofeiLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_align(ui_jiaofeiLabel, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_jiaofeiLabel, &ui_font_CHINESEsize25, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_jiaofei = lv_img_create(ui_jiaofeichuPanel1);
  lv_img_set_src(ui_jiaofei, &ui_img_jiaofeichu_png);
  lv_obj_set_width(ui_jiaofei, LV_SIZE_CONTENT);  /// 48
  lv_obj_set_height(ui_jiaofei, LV_SIZE_CONTENT); /// 48
  lv_obj_set_x(ui_jiaofei, 1);
  lv_obj_set_y(ui_jiaofei, 59);
  lv_obj_set_align(ui_jiaofei, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_jiaofei, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
  lv_obj_clear_flag(ui_jiaofei, LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_quyaochu = lv_img_create(ui_ceng1);
  lv_img_set_src(ui_quyaochu, &ui_img_quyaochu_png);
  lv_obj_set_width(ui_quyaochu, LV_SIZE_CONTENT);  /// 48
  lv_obj_set_height(ui_quyaochu, LV_SIZE_CONTENT); /// 48
  lv_obj_set_x(ui_quyaochu, -213);
  lv_obj_set_y(ui_quyaochu, -37);
  lv_obj_set_align(ui_quyaochu, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_quyaochu, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
  lv_obj_clear_flag(ui_quyaochu, LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_quyaoLabel = lv_label_create(ui_ceng1);
  lv_obj_set_width(ui_quyaoLabel, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_quyaoLabel, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_quyaoLabel, -214);
  lv_obj_set_y(ui_quyaoLabel, 3);
  lv_obj_set_align(ui_quyaoLabel, LV_ALIGN_CENTER);
  lv_label_set_text(ui_quyaoLabel, "取药");
  lv_obj_set_style_text_color(ui_quyaoLabel, lv_color_hex(0x6600FF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_quyaoLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_letter_space(ui_quyaoLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_line_space(ui_quyaoLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_quyaoLabel, &ui_font_CHINESEsize25, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_zixunquPanel = lv_obj_create(ui_ceng1);
  lv_obj_set_width(ui_zixunquPanel, 245);
  lv_obj_set_height(ui_zixunquPanel, 74);
  lv_obj_set_x(ui_zixunquPanel, -3);
  lv_obj_set_y(ui_zixunquPanel, -133);
  lv_obj_set_align(ui_zixunquPanel, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_zixunquPanel, LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_zixun1 = lv_img_create(ui_zixunquPanel);
  lv_img_set_src(ui_zixun1, &ui_img_qiantai_png);
  lv_obj_set_width(ui_zixun1, LV_SIZE_CONTENT);  /// 48
  lv_obj_set_height(ui_zixun1, LV_SIZE_CONTENT); /// 48
  lv_obj_set_x(ui_zixun1, -47);
  lv_obj_set_y(ui_zixun1, -14);
  lv_obj_set_align(ui_zixun1, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_zixun1, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
  lv_obj_clear_flag(ui_zixun1, LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_zixun2 = lv_img_create(ui_zixunquPanel);
  lv_img_set_src(ui_zixun2, &ui_img_qiantai_png);
  lv_obj_set_width(ui_zixun2, LV_SIZE_CONTENT);  /// 48
  lv_obj_set_height(ui_zixun2, LV_SIZE_CONTENT); /// 48
  lv_obj_set_x(ui_zixun2, 40);
  lv_obj_set_y(ui_zixun2, -14);
  lv_obj_set_align(ui_zixun2, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_zixun2, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
  lv_obj_clear_flag(ui_zixun2, LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_zixun3 = lv_img_create(ui_zixunquPanel);
  lv_img_set_src(ui_zixun3, &ui_img_qiantai_png);
  lv_obj_set_width(ui_zixun3, LV_SIZE_CONTENT);  /// 48
  lv_obj_set_height(ui_zixun3, LV_SIZE_CONTENT); /// 48
  lv_obj_set_x(ui_zixun3, -2);
  lv_obj_set_y(ui_zixun3, -14);
  lv_obj_set_align(ui_zixun3, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_zixun3, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
  lv_obj_clear_flag(ui_zixun3, LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_zixunquLabel = lv_label_create(ui_zixunquPanel);
  lv_obj_set_width(ui_zixunquLabel, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_zixunquLabel, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_zixunquLabel, -3);
  lv_obj_set_y(ui_zixunquLabel, 18);
  lv_obj_set_align(ui_zixunquLabel, LV_ALIGN_CENTER);
  lv_label_set_text(ui_zixunquLabel, "咨询区");
  lv_obj_set_style_text_color(ui_zixunquLabel, lv_color_hex(0x5F00FF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_zixunquLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_guahaoPanel = lv_obj_create(ui_ceng1);
  lv_obj_set_width(ui_guahaoPanel, 100);
  lv_obj_set_height(ui_guahaoPanel, 192);
  lv_obj_set_x(ui_guahaoPanel, 189);
  lv_obj_set_y(ui_guahaoPanel, -68);
  lv_obj_set_align(ui_guahaoPanel, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_guahaoPanel, LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_guahaoLabel = lv_label_create(ui_guahaoPanel);
  lv_obj_set_width(ui_guahaoLabel, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_guahaoLabel, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_guahaoLabel, 1);
  lv_obj_set_y(ui_guahaoLabel, 73);
  lv_obj_set_align(ui_guahaoLabel, LV_ALIGN_CENTER);
  lv_label_set_text(ui_guahaoLabel, "挂号");
  lv_obj_set_style_text_color(ui_guahaoLabel, lv_color_hex(0x4700FF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_guahaoLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_letter_space(ui_guahaoLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_line_space(ui_guahaoLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_guahaoButton = lv_btn_create(ui_guahaoPanel);
  lv_obj_set_width(ui_guahaoButton, 68);
  lv_obj_set_height(ui_guahaoButton, 50);
  lv_obj_set_x(ui_guahaoButton, 1);
  lv_obj_set_y(ui_guahaoButton, 30);
  lv_obj_set_align(ui_guahaoButton, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_guahaoButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
  lv_obj_clear_flag(ui_guahaoButton, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
  lv_obj_set_style_radius(ui_guahaoButton, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_color(ui_guahaoButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_guahaoButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_img_src(ui_guahaoButton, &ui_img_guahao_png, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_color(ui_guahaoButton, lv_color_hex(0x7A00FF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_opa(ui_guahaoButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_width(ui_guahaoButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_pad(ui_guahaoButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_shadow_color(ui_guahaoButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_shadow_opa(ui_guahaoButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_cesuo1 = lv_img_create(ui_ceng1);
  lv_img_set_src(ui_cesuo1, &ui_img_cesuo_png);
  lv_obj_set_width(ui_cesuo1, LV_SIZE_CONTENT);  /// 48
  lv_obj_set_height(ui_cesuo1, LV_SIZE_CONTENT); /// 48
  lv_obj_set_x(ui_cesuo1, -216);
  lv_obj_set_y(ui_cesuo1, -145);
  lv_obj_set_align(ui_cesuo1, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_cesuo1, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
  lv_obj_clear_flag(ui_cesuo1, LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_shoufutiPanel1 = lv_obj_create(ui_ceng1);
  lv_obj_set_width(ui_shoufutiPanel1, 113);
  lv_obj_set_height(ui_shoufutiPanel1, 96);
  lv_obj_set_x(ui_shoufutiPanel1, 176);
  lv_obj_set_y(ui_shoufutiPanel1, 109);
  lv_obj_set_align(ui_shoufutiPanel1, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_shoufutiPanel1, LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_shoufutiX1 = lv_img_create(ui_shoufutiPanel1);
  lv_img_set_src(ui_shoufutiX1, &ui_img_shoufutix_png);
  lv_obj_set_width(ui_shoufutiX1, LV_SIZE_CONTENT);  /// 48
  lv_obj_set_height(ui_shoufutiX1, LV_SIZE_CONTENT); /// 48
  lv_obj_set_x(ui_shoufutiX1, 28);
  lv_obj_set_y(ui_shoufutiX1, 19);
  lv_obj_set_align(ui_shoufutiX1, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_shoufutiX1, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
  lv_obj_clear_flag(ui_shoufutiX1, LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_shoufutiS1 = lv_img_create(ui_shoufutiPanel1);
  lv_img_set_src(ui_shoufutiS1, &ui_img_shoufutiis_png);
  lv_obj_set_width(ui_shoufutiS1, LV_SIZE_CONTENT);  /// 48
  lv_obj_set_height(ui_shoufutiS1, LV_SIZE_CONTENT); /// 48
  lv_obj_set_x(ui_shoufutiS1, 28);
  lv_obj_set_y(ui_shoufutiS1, -22);
  lv_obj_set_align(ui_shoufutiS1, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_shoufutiS1, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
  lv_obj_clear_flag(ui_shoufutiS1, LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_shoufutiText1 = lv_label_create(ui_shoufutiPanel1);
  lv_obj_set_width(ui_shoufutiText1, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_shoufutiText1, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_shoufutiText1, -21);
  lv_obj_set_y(ui_shoufutiText1, -2);
  lv_obj_set_align(ui_shoufutiText1, LV_ALIGN_CENTER);
  lv_label_set_text(ui_shoufutiText1, "手\n扶\n梯");
  lv_obj_set_style_text_color(ui_shoufutiText1, lv_color_hex(0x7700FF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_shoufutiText1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_letter_space(ui_shoufutiText1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_line_space(ui_shoufutiText1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_sosContainer1 = lv_obj_create(ui_ceng1);
  lv_obj_remove_style_all(ui_sosContainer1);
  lv_obj_set_width(ui_sosContainer1, 100);
  lv_obj_set_height(ui_sosContainer1, 83);
  lv_obj_set_x(ui_sosContainer1, 201);
  lv_obj_set_y(ui_sosContainer1, -128);
  lv_obj_set_align(ui_sosContainer1, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_sosContainer1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_SOS1 = lv_img_create(ui_sosContainer1);
  lv_img_set_src(ui_SOS1, &ui_img_sostongdao_png);
  lv_obj_set_width(ui_SOS1, LV_SIZE_CONTENT);  /// 48
  lv_obj_set_height(ui_SOS1, LV_SIZE_CONTENT); /// 48
  lv_obj_set_x(ui_SOS1, -10);
  lv_obj_set_y(ui_SOS1, -10);
  lv_obj_set_align(ui_SOS1, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_SOS1, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
  lv_obj_clear_flag(ui_SOS1, LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_SOSlabel1 = lv_label_create(ui_sosContainer1);
  lv_obj_set_width(ui_SOSlabel1, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_SOSlabel1, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_SOSlabel1, -10);
  lv_obj_set_y(ui_SOSlabel1, 39);
  lv_obj_set_align(ui_SOSlabel1, LV_ALIGN_CENTER);
  lv_label_set_text(ui_SOSlabel1, "SOS\n");
  lv_obj_set_style_text_color(ui_SOSlabel1, lv_color_hex(0x6300FF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_SOSlabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_letter_space(ui_SOSlabel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_line_space(ui_SOSlabel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_SOSlabel1, &ui_font_CHINESEsize25, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_head2 = lv_obj_create(ui_ditu123);
  lv_obj_set_width(ui_head2, 947);
  lv_obj_set_height(ui_head2, 73);
  lv_obj_set_x(ui_head2, -8);
  lv_obj_set_y(ui_head2, -244);
  lv_obj_set_align(ui_head2, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_head2, LV_OBJ_FLAG_SCROLLABLE); /// Flags
  lv_obj_set_style_radius(ui_head2, 25, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_fanhuilogin = lv_imgbtn_create(ui_head2);
  lv_imgbtn_set_src(ui_fanhuilogin, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_back_png, NULL);
  lv_imgbtn_set_src(ui_fanhuilogin, LV_IMGBTN_STATE_PRESSED, NULL, &ui__temporary_image, NULL);
  lv_imgbtn_set_src(ui_fanhuilogin, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
  lv_imgbtn_set_src(ui_fanhuilogin, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
  lv_imgbtn_set_src(ui_fanhuilogin, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
  lv_imgbtn_set_src(ui_fanhuilogin, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
  lv_obj_set_width(ui_fanhuilogin, 47);
  lv_obj_set_height(ui_fanhuilogin, 47);
  lv_obj_set_x(ui_fanhuilogin, -437);
  lv_obj_set_y(ui_fanhuilogin, 0);
  lv_obj_set_align(ui_fanhuilogin, LV_ALIGN_CENTER);

  /*     ui_dituTIME = lv_label_create(ui_head2);
      lv_obj_set_width(ui_dituTIME, LV_SIZE_CONTENT);  /// 1
      lv_obj_set_height(ui_dituTIME, LV_SIZE_CONTENT); /// 1
      lv_obj_set_x(ui_dituTIME, -318);
      lv_obj_set_y(ui_dituTIME, -1);
      lv_obj_set_align(ui_dituTIME, LV_ALIGN_CENTER);
      lv_label_set_text(ui_dituTIME, "2026/2/3 \n12:45");
      lv_obj_set_style_text_color(ui_dituTIME, lv_color_hex(0x7E00FF), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_text_font(ui_dituTIME, &ui_font_CHINESEsize25, LV_PART_MAIN | LV_STATE_DEFAULT);
      lv_obj_set_style_text_opa(ui_dituTIME, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
     */

  ui_jiuxuanyiliao2 = lv_img_create(ui_head2);
  lv_img_set_src(ui_jiuxuanyiliao2, &ui_img_jxyl_png);
  lv_obj_set_height(ui_jiuxuanyiliao2, 114);
  lv_obj_set_width(ui_jiuxuanyiliao2, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_jiuxuanyiliao2, 79);
  lv_obj_set_y(ui_jiuxuanyiliao2, -6);
  lv_obj_set_align(ui_jiuxuanyiliao2, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_jiuxuanyiliao2, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
  lv_obj_clear_flag(ui_jiuxuanyiliao2, LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_JXYLceng1 = lv_img_create(ui_head2);
  lv_img_set_src(ui_JXYLceng1, &ui_img_yiceng_png);
  lv_obj_set_width(ui_JXYLceng1, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_JXYLceng1, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_JXYLceng1, 377);
  lv_obj_set_y(ui_JXYLceng1, -1);
  lv_obj_set_align(ui_JXYLceng1, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_JXYLceng1, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
  lv_obj_clear_flag(ui_JXYLceng1, LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_JXYLceng3 = lv_img_create(ui_head2);
  lv_img_set_src(ui_JXYLceng3, &ui_img_sanceng_png);
  lv_obj_set_width(ui_JXYLceng3, LV_SIZE_CONTENT);  /// 2730
  lv_obj_set_height(ui_JXYLceng3, LV_SIZE_CONTENT); /// 1535
  lv_obj_set_x(ui_JXYLceng3, 372);
  lv_obj_set_y(ui_JXYLceng3, 3);
  lv_obj_set_align(ui_JXYLceng3, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_JXYLceng3, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST); /// Flags
  lv_obj_clear_flag(ui_JXYLceng3, LV_OBJ_FLAG_SCROLLABLE);                     /// Flags

  ui_JXYLceng2 = lv_img_create(ui_head2);
  lv_img_set_src(ui_JXYLceng2, &ui_img_erceng_png);
  lv_obj_set_width(ui_JXYLceng2, LV_SIZE_CONTENT);  /// 200
  lv_obj_set_height(ui_JXYLceng2, LV_SIZE_CONTENT); /// 100
  lv_obj_set_x(ui_JXYLceng2, 358);
  lv_obj_set_y(ui_JXYLceng2, 0);
  lv_obj_set_align(ui_JXYLceng2, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_JXYLceng2, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST); /// Flags
  lv_obj_clear_flag(ui_JXYLceng2, LV_OBJ_FLAG_SCROLLABLE);                     /// Flags

  //返回登录
  lv_obj_add_event_cb(ui_fanhuilogin, ui_event_gotologin, LV_EVENT_CLICKED, NULL);

  // 页签
  lv_tabview_set_act(ui_DocWinTabView, 2, LV_ANIM_OFF); // 设置让页签默认先显示第一层
  lv_obj_add_event_cb(ui_DocWinTabView, ui_DocWinTabView_event_handler, LV_EVENT_VALUE_CHANGED, NULL);

  // 内科
  lv_obj_add_event_cb(ui_neikeButton201, ui_event_goWINdoc, LV_EVENT_CLICKED, "201");
  lv_obj_add_event_cb(ui_neikeButton202, ui_event_goWINdoc, LV_EVENT_CLICKED, "202");
  lv_obj_add_event_cb(ui_neikeButton203, ui_event_goWINdoc, LV_EVENT_CLICKED, "203");

  // 外科
  lv_obj_add_event_cb(ui_waikeButton204, ui_event_goWINdoc, LV_EVENT_CLICKED, "204");
  lv_obj_add_event_cb(ui_waikeButton205, ui_event_goWINdoc, LV_EVENT_CLICKED, "205");
  lv_obj_add_event_cb(ui_waikeButton206, ui_event_goWINdoc, LV_EVENT_CLICKED, "206");

  // 中医科
  lv_obj_add_event_cb(ui_zhongyikeButton301, ui_event_goWINdoc, LV_EVENT_CLICKED, "301");
  lv_obj_add_event_cb(ui_zhongyikeButton302, ui_event_goWINdoc, LV_EVENT_CLICKED, "302");
  lv_obj_add_event_cb(ui_zhongyikeButton303, ui_event_goWINdoc, LV_EVENT_CLICKED, "303");

  // 康复科
  lv_obj_add_event_cb(ui_kangfukeButton304, ui_event_goWINdoc, LV_EVENT_CLICKED, "304");
  lv_obj_add_event_cb(ui_kangfukeButton305, ui_event_goWINdoc, LV_EVENT_CLICKED, "305");
  lv_obj_add_event_cb(ui_kangfukeButton306, ui_event_goWINdoc, LV_EVENT_CLICKED, "306");



  DBG_MSG("ui_ditu123.c init结束初始化");
}
 