// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"
#include "../../ui_LoginAndRegiste.h"
void ui_guahaoWin_screen_init(void)
{
  DBG_MSG("开始初始化ui_guahaoWin_screen_init");
  ui_guahaoWin = lv_obj_create(NULL);
  lv_obj_clear_flag(ui_guahaoWin, LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_Container1 = lv_obj_create(ui_guahaoWin);
  lv_obj_remove_style_all(ui_Container1);
  lv_obj_set_width(ui_Container1, 1001);
  lv_obj_set_height(ui_Container1, 568);
  lv_obj_set_x(ui_Container1, 12);
  lv_obj_set_y(ui_Container1, -4);
  lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_TabView1 = lv_tabview_create(ui_Container1, LV_DIR_LEFT, 200);
  lv_obj_set_width(ui_TabView1, 984);
  lv_obj_set_height(ui_TabView1, 451);
  lv_obj_set_x(ui_TabView1, -3);
  lv_obj_set_y(ui_TabView1, 60);
  lv_obj_set_align(ui_TabView1, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_TabView1, LV_OBJ_FLAG_SCROLLABLE); /// Flags

  lv_obj_set_style_text_color(lv_tabview_get_tab_btns(ui_TabView1), lv_color_hex(0x6900FD),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(lv_tabview_get_tab_btns(ui_TabView1), 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_letter_space(lv_tabview_get_tab_btns(ui_TabView1), 40, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_line_space(lv_tabview_get_tab_btns(ui_TabView1), 40, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(lv_tabview_get_tab_btns(ui_TabView1), &ui_font_CHINESEsize25,
                             LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_color(lv_tabview_get_tab_btns(ui_TabView1), lv_color_hex(0x7A00FE),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_opa(lv_tabview_get_tab_btns(ui_TabView1), 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_width(lv_tabview_get_tab_btns(ui_TabView1), 10, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_side(lv_tabview_get_tab_btns(ui_TabView1), LV_BORDER_SIDE_LEFT,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_color(lv_tabview_get_tab_btns(ui_TabView1), lv_color_hex(0x520AF5),
                                 LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_opa(lv_tabview_get_tab_btns(ui_TabView1), 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_width(lv_tabview_get_tab_btns(ui_TabView1), 5, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_pad(lv_tabview_get_tab_btns(ui_TabView1), 0, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_yiceng = lv_tabview_add_tab(ui_TabView1, "三层\n科室");
  lv_obj_clear_flag(ui_yiceng, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                                   LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags

  ui_ceng1Panel = lv_obj_create(ui_yiceng);
  lv_obj_set_width(ui_ceng1Panel, 552);
  lv_obj_set_height(ui_ceng1Panel, 428);
  lv_obj_set_x(ui_ceng1Panel, 64);
  lv_obj_set_y(ui_ceng1Panel, 1);
  lv_obj_set_align(ui_ceng1Panel, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_ceng1Panel, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                                       LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags
  lv_obj_set_style_outline_color(ui_ceng1Panel, lv_color_hex(0x6500FD), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_opa(ui_ceng1Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_width(ui_ceng1Panel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_pad(ui_ceng1Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_DocPanelCeng1 = lv_obj_create(ui_ceng1Panel);
  lv_obj_set_width(ui_DocPanelCeng1, 196);
  lv_obj_set_height(ui_DocPanelCeng1, 252);
  lv_obj_set_x(ui_DocPanelCeng1, -137);
  lv_obj_set_y(ui_DocPanelCeng1, -60);
  lv_obj_set_align(ui_DocPanelCeng1, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_DocPanelCeng1, LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_GHdocImageCeng1 = lv_img_create(ui_DocPanelCeng1);
  lv_img_set_src(ui_GHdocImageCeng1, &ui_img_missdoctor_png);
  lv_obj_set_width(ui_GHdocImageCeng1, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_GHdocImageCeng1, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_GHdocImageCeng1, -1);
  lv_obj_set_y(ui_GHdocImageCeng1, -26);
  lv_obj_set_align(ui_GHdocImageCeng1, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_GHdocImageCeng1, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
  lv_obj_clear_flag(ui_GHdocImageCeng1, LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_GHdocnameCeng1 = lv_label_create(ui_DocPanelCeng1);
  lv_obj_set_width(ui_GHdocnameCeng1, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_GHdocnameCeng1, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_GHdocnameCeng1, -2);
  lv_obj_set_y(ui_GHdocnameCeng1, 100);
  lv_obj_set_align(ui_GHdocnameCeng1, LV_ALIGN_CENTER);
  lv_label_set_text(ui_GHdocnameCeng1, "姓名");
  lv_obj_set_style_text_color(ui_GHdocnameCeng1, lv_color_hex(0x2C00FF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_GHdocnameCeng1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_GHdocnameCeng1, &ui_font_CHINESEsize25, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_GHceng1countContainerCeng1 = lv_obj_create(ui_ceng1Panel);
  lv_obj_remove_style_all(ui_GHceng1countContainerCeng1);
  lv_obj_set_width(ui_GHceng1countContainerCeng1, 208);
  lv_obj_set_height(ui_GHceng1countContainerCeng1, 68);
  lv_obj_set_x(ui_GHceng1countContainerCeng1, -131);
  lv_obj_set_y(ui_GHceng1countContainerCeng1, 108);
  lv_obj_set_align(ui_GHceng1countContainerCeng1, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_GHceng1countContainerCeng1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_GHdzzLabelCeng2 = lv_label_create(ui_GHceng1countContainerCeng1);
  lv_obj_set_width(ui_GHdzzLabelCeng2, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_GHdzzLabelCeng2, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_GHdzzLabelCeng2, 73);
  lv_obj_set_y(ui_GHdzzLabelCeng2, -5);
  lv_obj_set_align(ui_GHdzzLabelCeng2, LV_ALIGN_CENTER);
  lv_label_set_text(ui_GHdzzLabelCeng2, "人");
  lv_obj_set_style_text_color(ui_GHdzzLabelCeng2, lv_color_hex(0x6600FF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_GHdzzLabelCeng2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_GHdzzLabelCeng2, &ui_font_CHINESEsize25, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_GHdzzLabelCeng1 = lv_label_create(ui_GHceng1countContainerCeng1);
  lv_obj_set_width(ui_GHdzzLabelCeng1, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_GHdzzLabelCeng1, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_GHdzzLabelCeng1, -50);
  lv_obj_set_y(ui_GHdzzLabelCeng1, -8);
  lv_obj_set_align(ui_GHdzzLabelCeng1, LV_ALIGN_CENTER);
  lv_label_set_text(ui_GHdzzLabelCeng1, "预约人数:");
  lv_obj_set_style_text_color(ui_GHdzzLabelCeng1, lv_color_hex(0x6600FF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_GHdzzLabelCeng1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_GHdzzLabelCeng1, &ui_font_CHINESEsize25, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_GHcountLabelCeng1 = lv_label_create(ui_GHceng1countContainerCeng1);
  lv_obj_set_width(ui_GHcountLabelCeng1, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_GHcountLabelCeng1, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_GHcountLabelCeng1, 27);
  lv_obj_set_y(ui_GHcountLabelCeng1, -7);
  lv_obj_set_align(ui_GHcountLabelCeng1, LV_ALIGN_CENTER);
  lv_label_set_text(ui_GHcountLabelCeng1, "0");
  lv_obj_set_style_text_color(ui_GHcountLabelCeng1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_GHcountLabelCeng1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_GHcountLabelCeng1, &ui_font_CHINESEsize25, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_ImageCeng1 = lv_img_create(ui_ceng1Panel);
  lv_img_set_src(ui_ImageCeng1, &ui_img_style1_png);
  lv_obj_set_width(ui_ImageCeng1, LV_SIZE_CONTENT);  /// 150
  lv_obj_set_height(ui_ImageCeng1, LV_SIZE_CONTENT); /// 33
  lv_obj_set_x(ui_ImageCeng1, 119);
  lv_obj_set_y(ui_ImageCeng1, -180);
  lv_obj_set_align(ui_ImageCeng1, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_ImageCeng1, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
  lv_obj_clear_flag(ui_ImageCeng1, LV_OBJ_FLAG_SCROLLABLE); /// Flags
  lv_img_set_zoom(ui_ImageCeng1, 500);

  ui_LabelselectCeng1 = lv_label_create(ui_ImageCeng1);
  lv_obj_set_width(ui_LabelselectCeng1, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_LabelselectCeng1, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_LabelselectCeng1, 2);
  lv_obj_set_y(ui_LabelselectCeng1, -2);
  lv_obj_set_align(ui_LabelselectCeng1, LV_ALIGN_CENTER);
  lv_label_set_text(ui_LabelselectCeng1, "选择预约时间");
  lv_obj_set_style_text_color(ui_LabelselectCeng1, lv_color_hex(0xA000FF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_LabelselectCeng1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_LabelselectCeng1, &ui_font_CHINESEsize25, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_RollerTimeCeng1 = lv_roller_create(ui_ceng1Panel);
  lv_roller_set_options(ui_RollerTimeCeng1,
                        "8:00~9:00\n9:00~10:00\n10:00~11:00\n休息\n13:00~14:00\n14:00~15:00\n15:00~16:00\n16:00~17:00\n17:00~18:00",
                        LV_ROLLER_MODE_INFINITE);
  lv_obj_set_height(ui_RollerTimeCeng1, 329);
  lv_obj_set_width(ui_RollerTimeCeng1, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_RollerTimeCeng1, 119);
  lv_obj_set_y(ui_RollerTimeCeng1, 26);
  lv_obj_set_align(ui_RollerTimeCeng1, LV_ALIGN_CENTER);
  lv_obj_set_style_text_color(ui_RollerTimeCeng1, lv_color_hex(0x4400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_RollerTimeCeng1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_RollerTimeCeng1, &ui_font_CHINESEsize25, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_ButtonCeng1 = lv_btn_create(ui_ceng1Panel);
  lv_obj_set_width(ui_ButtonCeng1, 206);
  lv_obj_set_height(ui_ButtonCeng1, 50);
  lv_obj_set_x(ui_ButtonCeng1, -136);
  lv_obj_set_y(ui_ButtonCeng1, 162);
  lv_obj_set_align(ui_ButtonCeng1, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_ButtonCeng1, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
  lv_obj_clear_flag(ui_ButtonCeng1, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
  lv_obj_set_style_bg_img_src(ui_ButtonCeng1, &ui_img_tijiao_png, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_color(ui_ButtonCeng1, lv_color_hex(0x9C07A4), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_opa(ui_ButtonCeng1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_width(ui_ButtonCeng1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_RollerCeng1 = lv_roller_create(ui_yiceng);
  lv_roller_set_options(ui_RollerCeng1,
                        "中医科301室\n中医科302室\n中医科303室\n康复科304室\n康复科305室\n康复科306室", LV_ROLLER_MODE_INFINITE);
  lv_obj_set_height(ui_RollerCeng1, 403);
  lv_obj_set_width(ui_RollerCeng1, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_RollerCeng1, -286);
  lv_obj_set_y(ui_RollerCeng1, -1);
  lv_obj_set_align(ui_RollerCeng1, LV_ALIGN_CENTER);
  lv_obj_set_style_text_color(ui_RollerCeng1, lv_color_hex(0x7300FD), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_RollerCeng1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_letter_space(ui_RollerCeng1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_line_space(ui_RollerCeng1, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_align(ui_RollerCeng1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_RollerCeng1, &ui_font_CHINESEsize25, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_color(ui_RollerCeng1, lv_color_hex(0xB000F9), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_opa(ui_RollerCeng1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_width(ui_RollerCeng1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_pad(ui_RollerCeng1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_shadow_color(ui_RollerCeng1, lv_color_hex(0x7E00FF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_shadow_opa(ui_RollerCeng1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_shadow_width(ui_RollerCeng1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_shadow_spread(ui_RollerCeng1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_set_style_outline_color(ui_RollerCeng1, lv_color_hex(0x6600FF), LV_PART_SELECTED | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_opa(ui_RollerCeng1, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_width(ui_RollerCeng1, 10, LV_PART_SELECTED | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_pad(ui_RollerCeng1, 2, LV_PART_SELECTED | LV_STATE_DEFAULT);

  ui_erceng = lv_tabview_add_tab(ui_TabView1, "二层\n科室");

  ui_ceng2Panel = lv_obj_create(ui_erceng);
  lv_obj_set_width(ui_ceng2Panel, 552);
  lv_obj_set_height(ui_ceng2Panel, 428);
  lv_obj_set_x(ui_ceng2Panel, 64);
  lv_obj_set_y(ui_ceng2Panel, 1);
  lv_obj_set_align(ui_ceng2Panel, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_ceng2Panel, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                                       LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags
  lv_obj_set_style_outline_color(ui_ceng2Panel, lv_color_hex(0x6500FD), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_opa(ui_ceng2Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_width(ui_ceng2Panel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_pad(ui_ceng2Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_ceng2DocPanel = lv_obj_create(ui_ceng2Panel);
  lv_obj_set_width(ui_ceng2DocPanel, 196);
  lv_obj_set_height(ui_ceng2DocPanel, 252);
  lv_obj_set_x(ui_ceng2DocPanel, -134);
  lv_obj_set_y(ui_ceng2DocPanel, -61);
  lv_obj_set_align(ui_ceng2DocPanel, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_ceng2DocPanel, LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_GHdocImage2 = lv_img_create(ui_ceng2DocPanel);
  lv_img_set_src(ui_GHdocImage2, &ui_img_missdoctor_png);
  lv_obj_set_width(ui_GHdocImage2, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_GHdocImage2, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_GHdocImage2, -1);
  lv_obj_set_y(ui_GHdocImage2, -26);
  lv_obj_set_align(ui_GHdocImage2, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_GHdocImage2, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
  lv_obj_clear_flag(ui_GHdocImage2, LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_GHdocnameCeng2 = lv_label_create(ui_ceng2DocPanel);
  lv_obj_set_width(ui_GHdocnameCeng2, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_GHdocnameCeng2, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_GHdocnameCeng2, -2);
  lv_obj_set_y(ui_GHdocnameCeng2, 100);
  lv_obj_set_align(ui_GHdocnameCeng2, LV_ALIGN_CENTER);
  lv_label_set_text(ui_GHdocnameCeng2, "姓名");
  lv_obj_set_style_text_color(ui_GHdocnameCeng2, lv_color_hex(0x2C00FF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_GHdocnameCeng2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_GHdocnameCeng2, &ui_font_CHINESEsize25, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_GHceng1countContainerCeng2 = lv_obj_create(ui_ceng2Panel);
  lv_obj_remove_style_all(ui_GHceng1countContainerCeng2);
  lv_obj_set_width(ui_GHceng1countContainerCeng2, 208);
  lv_obj_set_height(ui_GHceng1countContainerCeng2, 68);
  lv_obj_set_x(ui_GHceng1countContainerCeng2, -131);
  lv_obj_set_y(ui_GHceng1countContainerCeng2, 108);
  lv_obj_set_align(ui_GHceng1countContainerCeng2, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_GHceng1countContainerCeng2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_GHdaizhenzhongLabelCeng2 = lv_label_create(ui_GHceng1countContainerCeng2);
  lv_obj_set_width(ui_GHdaizhenzhongLabelCeng2, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_GHdaizhenzhongLabelCeng2, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_GHdaizhenzhongLabelCeng2, 67);
  lv_obj_set_y(ui_GHdaizhenzhongLabelCeng2, -5);
  lv_obj_set_align(ui_GHdaizhenzhongLabelCeng2, LV_ALIGN_CENTER);
  lv_label_set_text(ui_GHdaizhenzhongLabelCeng2, " /8人");
  lv_obj_set_style_text_color(ui_GHdaizhenzhongLabelCeng2, lv_color_hex(0x6600FF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_GHdaizhenzhongLabelCeng2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_GHdaizhenzhongLabelCeng2, &ui_font_CHINESEsize25, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_GHdzzLabelCeng3 = lv_label_create(ui_GHceng1countContainerCeng2);
  lv_obj_set_width(ui_GHdzzLabelCeng3, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_GHdzzLabelCeng3, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_GHdzzLabelCeng3, -50);
  lv_obj_set_y(ui_GHdzzLabelCeng3, -8);
  lv_obj_set_align(ui_GHdzzLabelCeng3, LV_ALIGN_CENTER);
  lv_label_set_text(ui_GHdzzLabelCeng3, "预约人数:");
  lv_obj_set_style_text_color(ui_GHdzzLabelCeng3, lv_color_hex(0x6600FF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_GHdzzLabelCeng3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_GHdzzLabelCeng3, &ui_font_CHINESEsize25, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_GHcountLabelCeng2 = lv_label_create(ui_GHceng1countContainerCeng2);
  lv_obj_set_width(ui_GHcountLabelCeng2, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_GHcountLabelCeng2, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_GHcountLabelCeng2, 27);
  lv_obj_set_y(ui_GHcountLabelCeng2, -7);
  lv_obj_set_align(ui_GHcountLabelCeng2, LV_ALIGN_CENTER);
  lv_label_set_text(ui_GHcountLabelCeng2, "0");
  lv_obj_set_style_text_color(ui_GHcountLabelCeng2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_GHcountLabelCeng2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_GHcountLabelCeng2, &ui_font_CHINESEsize25, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_ImageCeng2 = lv_img_create(ui_ceng2Panel);
  lv_img_set_src(ui_ImageCeng2, &ui_img_style1_png);
  lv_obj_set_width(ui_ImageCeng2, LV_SIZE_CONTENT);  /// 150
  lv_obj_set_height(ui_ImageCeng2, LV_SIZE_CONTENT); /// 33
  lv_obj_set_x(ui_ImageCeng2, 119);
  lv_obj_set_y(ui_ImageCeng2, -180);
  lv_obj_set_align(ui_ImageCeng2, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_ImageCeng2, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
  lv_obj_clear_flag(ui_ImageCeng2, LV_OBJ_FLAG_SCROLLABLE); /// Flags
  lv_img_set_zoom(ui_ImageCeng2, 500);

  ui_LabelselectCeng2 = lv_label_create(ui_ImageCeng2);
  lv_obj_set_width(ui_LabelselectCeng2, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_LabelselectCeng2, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_LabelselectCeng2, 2);
  lv_obj_set_y(ui_LabelselectCeng2, -2);
  lv_obj_set_align(ui_LabelselectCeng2, LV_ALIGN_CENTER);
  lv_label_set_text(ui_LabelselectCeng2, "选择预约时间");
  lv_obj_set_style_text_color(ui_LabelselectCeng2, lv_color_hex(0xA000FF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_LabelselectCeng2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_LabelselectCeng2, &ui_font_CHINESEsize25, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_RollerTimeCeng2 = lv_roller_create(ui_ceng2Panel);
  lv_roller_set_options(ui_RollerTimeCeng2,
                        "8:00~9:00\n9:00~10:00\n10:00~11:00\n休息\n13:00~14:00\n14:00~15:00\n15:00~16:00\n16:00~17:00\n17:00~18:00",
                        LV_ROLLER_MODE_INFINITE);
  lv_obj_set_height(ui_RollerTimeCeng2, 329);
  lv_obj_set_width(ui_RollerTimeCeng2, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_RollerTimeCeng2, 119);
  lv_obj_set_y(ui_RollerTimeCeng2, 26);
  lv_obj_set_align(ui_RollerTimeCeng2, LV_ALIGN_CENTER);
  lv_obj_set_style_text_color(ui_RollerTimeCeng2, lv_color_hex(0x4400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_RollerTimeCeng2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_RollerTimeCeng2, &ui_font_CHINESEsize25, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_ButtonCeng2 = lv_btn_create(ui_ceng2Panel);
  lv_obj_set_width(ui_ButtonCeng2, 206);
  lv_obj_set_height(ui_ButtonCeng2, 50);
  lv_obj_set_x(ui_ButtonCeng2, -136);
  lv_obj_set_y(ui_ButtonCeng2, 162);
  lv_obj_set_align(ui_ButtonCeng2, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_ButtonCeng2, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
  lv_obj_clear_flag(ui_ButtonCeng2, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
  lv_obj_set_style_bg_img_src(ui_ButtonCeng2, &ui_img_tijiao_png, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_Rollerceng2 = lv_roller_create(ui_erceng);
  lv_roller_set_options(ui_Rollerceng2,
                        "内科201室\n内科202室\n内科203室\n外科204室\n外科205室\n外科206室", LV_ROLLER_MODE_INFINITE);
  lv_obj_set_height(ui_Rollerceng2, 403);
  lv_obj_set_width(ui_Rollerceng2, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_Rollerceng2, -286);
  lv_obj_set_y(ui_Rollerceng2, -1);
  lv_obj_set_align(ui_Rollerceng2, LV_ALIGN_CENTER);
  lv_obj_set_style_text_color(ui_Rollerceng2, lv_color_hex(0x7300FD), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_Rollerceng2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_letter_space(ui_Rollerceng2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_line_space(ui_Rollerceng2, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_align(ui_Rollerceng2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_Rollerceng2, &ui_font_CHINESEsize25, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_color(ui_Rollerceng2, lv_color_hex(0xB000F9), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_opa(ui_Rollerceng2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_width(ui_Rollerceng2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_pad(ui_Rollerceng2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_shadow_color(ui_Rollerceng2, lv_color_hex(0x7E00FF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_shadow_opa(ui_Rollerceng2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_shadow_width(ui_Rollerceng2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_shadow_spread(ui_Rollerceng2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_set_style_outline_color(ui_Rollerceng2, lv_color_hex(0x6600FF), LV_PART_SELECTED | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_opa(ui_Rollerceng2, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_width(ui_Rollerceng2, 10, LV_PART_SELECTED | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_pad(ui_Rollerceng2, 2, LV_PART_SELECTED | LV_STATE_DEFAULT);

  ui_guahaohead = lv_obj_create(ui_guahaoWin);
  lv_obj_set_width(ui_guahaohead, 947);
  lv_obj_set_height(ui_guahaohead, 73);
  lv_obj_set_x(ui_guahaohead, -8);
  lv_obj_set_y(ui_guahaohead, -244);
  lv_obj_set_align(ui_guahaohead, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_guahaohead, LV_OBJ_FLAG_SCROLLABLE); /// Flags
  lv_obj_set_style_radius(ui_guahaohead, 25, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_fanhuiditu123 = lv_imgbtn_create(ui_guahaohead);
  lv_imgbtn_set_src(ui_fanhuiditu123, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_back_png, NULL);
  lv_imgbtn_set_src(ui_fanhuiditu123, LV_IMGBTN_STATE_PRESSED, NULL, &ui__temporary_image, NULL);
  lv_imgbtn_set_src(ui_fanhuiditu123, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
  lv_imgbtn_set_src(ui_fanhuiditu123, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
  lv_imgbtn_set_src(ui_fanhuiditu123, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
  lv_imgbtn_set_src(ui_fanhuiditu123, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
  lv_obj_set_width(ui_fanhuiditu123, 47);
  lv_obj_set_height(ui_fanhuiditu123, 47);
  lv_obj_set_x(ui_fanhuiditu123, -437);
  lv_obj_set_y(ui_fanhuiditu123, 0);
  lv_obj_set_align(ui_fanhuiditu123, LV_ALIGN_CENTER);

  ui_jiuxuanyiliao1 = lv_img_create(ui_guahaohead);
  lv_img_set_src(ui_jiuxuanyiliao1, &ui_img_jxyl_png);
  lv_obj_set_height(ui_jiuxuanyiliao1, 114);
  lv_obj_set_width(ui_jiuxuanyiliao1, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_jiuxuanyiliao1, 79);
  lv_obj_set_y(ui_jiuxuanyiliao1, -6);
  lv_obj_set_align(ui_jiuxuanyiliao1, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_jiuxuanyiliao1, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
  lv_obj_clear_flag(ui_jiuxuanyiliao1, LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_JXYLguahao = lv_img_create(ui_guahaohead);
  lv_img_set_src(ui_JXYLguahao, &ui_img_headguahao_png);
  lv_obj_set_width(ui_JXYLguahao, LV_SIZE_CONTENT);  /// 200
  lv_obj_set_height(ui_JXYLguahao, LV_SIZE_CONTENT); /// 100
  lv_obj_set_x(ui_JXYLguahao, 376);
  lv_obj_set_y(ui_JXYLguahao, 4);
  lv_obj_set_align(ui_JXYLguahao, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_JXYLguahao, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
  lv_obj_clear_flag(ui_JXYLguahao, LV_OBJ_FLAG_SCROLLABLE); /// Flags

  // 返回地图
  lv_obj_add_event_cb(ui_fanhuiditu123, ui_event_gotoditu123, LV_EVENT_CLICKED, NULL);

  // 挂号
  lv_obj_add_event_cb(ui_guahaoButton, ui_event_gotoGuaHaoWin, LV_EVENT_CLICKED, NULL);

  // 页签
  lv_tabview_set_act(ui_TabView1, 1, LV_ANIM_OFF); // 设置让页签默认先显示第一层

  // 滚轮
  lv_obj_add_event_cb(ui_RollerCeng1, ui_event_select_id, LV_EVENT_VALUE_CHANGED, "1");
  lv_obj_add_event_cb(ui_Rollerceng2, ui_event_select_id, LV_EVENT_VALUE_CHANGED, "2");
  lv_obj_add_event_cb(ui_RollerTimeCeng1, ui_event_select_time, LV_EVENT_VALUE_CHANGED, "1");
  lv_obj_add_event_cb(ui_RollerTimeCeng2, ui_event_select_time, LV_EVENT_VALUE_CHANGED, "2");

  //按钮
  lv_obj_add_event_cb(ui_ButtonCeng1, ui_event_button_tijiao, LV_EVENT_SHORT_CLICKED, NULL);
  lv_obj_add_event_cb(ui_ButtonCeng2,  ui_event_button_tijiao, LV_EVENT_SHORT_CLICKED,NULL);


  DBG_MSG("ui_guahaoWin_screen_init结束初始化");
}
