// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"
#include "ui_events.h"
#include "../../ui_LoginAndRegiste.h"
void ui_LoginRegisteWin_screen_init(void)
{
    DBG_MSG("开始初始化LoginRegisteWin_screen_init");
    ui_LoginRegisteWin = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_LoginRegisteWin, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_loginBG = lv_img_create(ui_LoginRegisteWin);
    lv_img_set_src(ui_loginBG, &ui_img_loginregiste_png);
    lv_obj_set_width(ui_loginBG, LV_SIZE_CONTENT);  /// 1024
    lv_obj_set_height(ui_loginBG, LV_SIZE_CONTENT); /// 600
    lv_obj_set_x(ui_loginBG, -20);
    lv_obj_set_y(ui_loginBG, -21);
    lv_obj_set_align(ui_loginBG, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_loginBG, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_loginBG, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_img_set_zoom(ui_loginBG, 280);

    ui_LRContainer = lv_obj_create(ui_LoginRegisteWin);
    lv_obj_remove_style_all(ui_LRContainer);
    lv_obj_set_width(ui_LRContainer, 342);
    lv_obj_set_height(ui_LRContainer, 644);
    lv_obj_set_x(ui_LRContainer, 338);
    lv_obj_set_y(ui_LRContainer, 28);
    lv_obj_set_align(ui_LRContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_LRContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_radius(ui_LRContainer, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LRContainer, lv_color_hex(0x0B30FC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LRContainer, 110, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_LRContainer, lv_color_hex(0xCDC1F5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_LRContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_LRContainer, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_LRContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LoginRegiste = lv_obj_create(ui_LRContainer);
    lv_obj_remove_style_all(ui_LoginRegiste);
    lv_obj_set_width(ui_LoginRegiste, 898);
    lv_obj_set_height(ui_LoginRegiste, 475);
    lv_obj_set_x(ui_LoginRegiste, -264);
    lv_obj_set_y(ui_LoginRegiste, -13);
    lv_obj_set_align(ui_LoginRegiste, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_LoginRegiste, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_username = lv_obj_create(ui_LoginRegiste);
    lv_obj_remove_style_all(ui_username);
    lv_obj_set_width(ui_username, 436);
    lv_obj_set_height(ui_username, 157);
    lv_obj_set_x(ui_username, 236);
    lv_obj_set_y(ui_username, -162);
    lv_obj_set_align(ui_username, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_username, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_usernameText = lv_textarea_create(ui_username);
    lv_obj_set_width(ui_usernameText, 297);
    lv_obj_set_height(ui_usernameText, 53);
    lv_obj_set_x(ui_usernameText, 24);
    lv_obj_set_y(ui_usernameText, 2);
    lv_obj_set_align(ui_usernameText, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_usernameText, "请填写真实姓名");
    lv_obj_set_style_text_align(ui_usernameText, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_usernameText, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_usernameText, &ui_font_CHINESEsize25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_usernameLabel = lv_label_create(ui_username);
    lv_obj_set_width(ui_usernameLabel, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_usernameLabel, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_usernameLabel, -89);
    lv_obj_set_y(ui_usernameLabel, -46);
    lv_obj_set_align(ui_usernameLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_usernameLabel, "姓名:");
    lv_obj_set_style_text_color(ui_usernameLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_usernameLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_usernameLabel, &ui_font_CHINESEsize25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_password = lv_obj_create(ui_LoginRegiste);
    lv_obj_remove_style_all(ui_password);
    lv_obj_set_width(ui_password, 436);
    lv_obj_set_height(ui_password, 153);
    lv_obj_set_x(ui_password, 203);
    lv_obj_set_y(ui_password, 46);
    lv_obj_set_align(ui_password, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_password, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_mmText_ = lv_textarea_create(ui_password);
    lv_obj_set_width(ui_mmText_, 297);
    lv_obj_set_height(ui_mmText_, LV_SIZE_CONTENT); /// 41
    lv_obj_set_x(ui_mmText_, 58);
    lv_obj_set_y(ui_mmText_, 3);
    lv_obj_set_align(ui_mmText_, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_mmText_, "大小写字母,数字,8位");
    lv_textarea_set_one_line(ui_mmText_, true);
    lv_textarea_set_password_mode(ui_mmText_, true);
    lv_obj_set_style_text_align(ui_mmText_, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_mmText_, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_mmText_, &ui_font_CHINESEsize25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mmLabel = lv_label_create(ui_password);
    lv_obj_set_width(ui_mmLabel, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_mmLabel, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_mmLabel, -58);
    lv_obj_set_y(ui_mmLabel, -48);
    lv_obj_set_align(ui_mmLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_mmLabel, "密码:");
    lv_obj_set_style_text_color(ui_mmLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_mmLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_mmLabel, &ui_font_CHINESEsize25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mmX = lv_imgbtn_create(ui_password);
    lv_imgbtn_set_src(ui_mmX, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_xianshi_png, NULL);
    lv_imgbtn_set_src(ui_mmX, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_xianshi_png, NULL);
    lv_imgbtn_set_src(ui_mmX, LV_IMGBTN_STATE_DISABLED, NULL, &ui_img_xianshi_png, NULL);
    lv_imgbtn_set_src(ui_mmX, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_xianshi_png, NULL);
    lv_imgbtn_set_src(ui_mmX, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_xianshi_png, NULL);
    lv_imgbtn_set_src(ui_mmX, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui_img_xianshi_png, NULL);
    lv_obj_set_height(ui_mmX, 32);
    lv_obj_set_width(ui_mmX, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_mmX, 177);
    lv_obj_set_y(ui_mmX, 1);
    lv_obj_set_align(ui_mmX, LV_ALIGN_CENTER);

    ui_mmY = lv_imgbtn_create(ui_password);
    lv_imgbtn_set_src(ui_mmY, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_yincang_png, NULL);
    lv_imgbtn_set_src(ui_mmY, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_yincang_png, NULL);
    lv_imgbtn_set_src(ui_mmY, LV_IMGBTN_STATE_DISABLED, NULL, &ui_img_yincang_png, NULL);
    lv_imgbtn_set_src(ui_mmY, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_yincang_png, NULL);
    lv_imgbtn_set_src(ui_mmY, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_yincang_png, NULL);
    lv_imgbtn_set_src(ui_mmY, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui_img_yincang_png, NULL);
    lv_obj_set_height(ui_mmY, 28);
    lv_obj_set_width(ui_mmY, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_mmY, 177);
    lv_obj_set_y(ui_mmY, 11);
    lv_obj_set_align(ui_mmY, LV_ALIGN_CENTER);

    ui_userIDcard = lv_obj_create(ui_LoginRegiste);
    lv_obj_remove_style_all(ui_userIDcard);
    lv_obj_set_width(ui_userIDcard, 436);
    lv_obj_set_height(ui_userIDcard, 150);
    lv_obj_set_x(ui_userIDcard, 204);
    lv_obj_set_y(ui_userIDcard, -62);
    lv_obj_set_align(ui_userIDcard, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_userIDcard, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_userIDcardText_ = lv_textarea_create(ui_userIDcard);
    lv_obj_set_width(ui_userIDcardText_, 297);
    lv_obj_set_height(ui_userIDcardText_, LV_SIZE_CONTENT); /// 41
    lv_obj_set_x(ui_userIDcardText_, 56);
    lv_obj_set_y(ui_userIDcardText_, 4);
    lv_obj_set_align(ui_userIDcardText_, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_userIDcardText_, "请填写真实身份证号");
    lv_textarea_set_one_line(ui_userIDcardText_, true);
    lv_obj_set_style_text_align(ui_userIDcardText_, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_userIDcardText_, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_userIDcardText_, &ui_font_CHINESEsize25, LV_PART_MAIN | LV_STATE_DEFAULT);

    DBG_PRINT();

    ui_userIDcardLabel = lv_label_create(ui_userIDcard);
    lv_obj_set_width(ui_userIDcardLabel, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_userIDcardLabel, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_userIDcardLabel, -34);
    lv_obj_set_y(ui_userIDcardLabel, -47);
    lv_obj_set_align(ui_userIDcardLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_userIDcardLabel, "身份证号:");
    lv_obj_set_style_text_color(ui_userIDcardLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_userIDcardLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_userIDcardLabel, &ui_font_CHINESEsize25, LV_PART_MAIN | LV_STATE_DEFAULT);
DBG_PRINT();
    ui_shenfenChange = lv_obj_create(ui_LoginRegiste);
    lv_obj_remove_style_all(ui_shenfenChange);
    lv_obj_set_width(ui_shenfenChange, 320);
    lv_obj_set_height(ui_shenfenChange, 72);
    lv_obj_set_x(ui_shenfenChange, 270);
    lv_obj_set_y(ui_shenfenChange, 134);
    lv_obj_set_align(ui_shenfenChange, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_shenfenChange, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags
DBG_PRINT();
    ui_shenfenPanel = lv_obj_create(ui_shenfenChange);
    lv_obj_set_width(ui_shenfenPanel, 220);
    lv_obj_set_height(ui_shenfenPanel, 50);
    lv_obj_set_x(ui_shenfenPanel, 31);
    lv_obj_set_y(ui_shenfenPanel, -1);
    lv_obj_set_align(ui_shenfenPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_shenfenPanel, LV_OBJ_FLAG_SCROLLABLE); /// Flags
DBG_PRINT();
    ui_shenfenLabel = lv_label_create(ui_shenfenChange);
    lv_obj_set_width(ui_shenfenLabel, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_shenfenLabel, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_shenfenLabel, 20);
    lv_obj_set_y(ui_shenfenLabel, 1);
    lv_obj_set_align(ui_shenfenLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_shenfenLabel, " ");
    lv_obj_set_style_text_color(ui_shenfenLabel, lv_color_hex(0x7700FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_shenfenLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_shenfenLabel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_shenfenLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_shenfenLabel, &ui_font_CHINESEsize25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_text(ui_shenfenLabel, "普通用户");
DBG_PRINT();
    ui_shenfen = lv_dropdown_create(ui_shenfenChange);
    lv_dropdown_set_options(ui_shenfen, "普通用户\n中医科医师\n康复科医师\n内科医师\n外科医师\n"); // 0 1 2 3 4
    lv_dropdown_set_text(ui_shenfen, "身份");
    lv_obj_set_width(ui_shenfen, 91);
    lv_obj_set_height(ui_shenfen, LV_SIZE_CONTENT); /// 41
    lv_obj_set_x(ui_shenfen, -110);
    lv_obj_set_y(ui_shenfen, -2);
    lv_obj_set_align(ui_shenfen, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_shenfen, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_set_style_text_color(ui_shenfen, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_shenfen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_shenfen, &ui_font_CHINESEsize25, LV_PART_MAIN | LV_STATE_DEFAULT);
DBG_PRINT();
    lv_obj_set_style_text_color(ui_shenfen, lv_color_hex(0x808080), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_shenfen, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_shenfen, &ui_font_CHINESEsize25, LV_PART_INDICATOR | LV_STATE_DEFAULT);
DBG_PRINT();
    lv_obj_set_style_text_color(lv_dropdown_get_list(ui_shenfen), lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(lv_dropdown_get_list(ui_shenfen), 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_shenfen), &ui_font_CHINESEsize25, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(lv_dropdown_get_list(ui_shenfen), lv_color_hex(0x7700FF),
                                LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(lv_dropdown_get_list(ui_shenfen), 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_shenfen), &ui_font_CHINESEsize25,
                               LV_PART_SELECTED | LV_STATE_DEFAULT);
DBG_PRINT();
    ui_doctorCon = lv_obj_create(ui_shenfenChange);
    lv_obj_remove_style_all(ui_doctorCon);
    lv_obj_set_width(ui_doctorCon, 92);
    lv_obj_set_height(ui_doctorCon, 46);
    lv_obj_set_x(ui_doctorCon, 8);
    lv_obj_set_y(ui_doctorCon, 0);
    lv_obj_set_align(ui_doctorCon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_doctorCon, LV_OBJ_FLAG_HIDDEN);                               /// Flags
    lv_obj_clear_flag(ui_doctorCon, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags
DBG_PRINT();
    ui_doctorText = lv_textarea_create(ui_doctorCon);
    lv_obj_set_width(ui_doctorText, 110);
    lv_obj_set_height(ui_doctorText, LV_SIZE_CONTENT); /// 46
    lv_obj_set_x(ui_doctorText, 1);
    lv_obj_set_y(ui_doctorText, 2);
    lv_obj_set_align(ui_doctorText, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_doctorText, 4);
    lv_textarea_set_placeholder_text(ui_doctorText, " ");
    lv_textarea_set_one_line(ui_doctorText, true);
    lv_textarea_set_password_mode(ui_doctorText, true);
    lv_obj_add_flag(ui_doctorText, LV_OBJ_FLAG_HIDDEN);      /// Flags
    lv_obj_clear_flag(ui_doctorText, LV_OBJ_FLAG_CLICKABLE); /// Flags
    lv_obj_set_style_text_font(ui_doctorText, &ui_font_CHINESEsize25, LV_PART_MAIN | LV_STATE_DEFAULT);
DBG_PRINT();
    ui_LRbutton = lv_obj_create(ui_LRContainer);
    lv_obj_remove_style_all(ui_LRbutton);
    lv_obj_set_width(ui_LRbutton, 301);
    lv_obj_set_height(ui_LRbutton, 82);
    lv_obj_set_x(ui_LRbutton, -2);
    lv_obj_set_y(ui_LRbutton, 207);
    lv_obj_set_align(ui_LRbutton, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_LRbutton, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags
DBG_PRINT();
    ui_denglu = lv_imgbtn_create(ui_LRbutton);
    lv_imgbtn_set_src(ui_denglu, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_659432751, NULL);
    lv_imgbtn_set_src(ui_denglu, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_659432751, NULL);
    lv_imgbtn_set_src(ui_denglu, LV_IMGBTN_STATE_DISABLED, NULL, &ui_img_659432751, NULL);
    lv_imgbtn_set_src(ui_denglu, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_659432751, NULL);
    lv_imgbtn_set_src(ui_denglu, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_659432751, NULL);
    lv_imgbtn_set_src(ui_denglu, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui_img_659432751, NULL);
    lv_obj_set_height(ui_denglu, 64);
    lv_obj_set_width(ui_denglu, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_denglu, 60);
    lv_obj_set_y(ui_denglu, 4);
    lv_obj_set_align(ui_denglu, LV_ALIGN_CENTER);
DBG_PRINT();
    ui_zhuce = lv_imgbtn_create(ui_LRbutton);
    lv_imgbtn_set_src(ui_zhuce, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1266464991, NULL);
    lv_imgbtn_set_src(ui_zhuce, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1266464991, NULL);
    lv_imgbtn_set_src(ui_zhuce, LV_IMGBTN_STATE_DISABLED, NULL, &ui_img_1266464991, NULL);
    lv_imgbtn_set_src(ui_zhuce, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_1266464991, NULL);
    lv_imgbtn_set_src(ui_zhuce, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_1266464991, NULL);
    lv_imgbtn_set_src(ui_zhuce, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui_img_1266464991, NULL);
    lv_obj_set_height(ui_zhuce, 64);
    lv_obj_set_width(ui_zhuce, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_zhuce, -60);
    lv_obj_set_y(ui_zhuce, 3);
    lv_obj_set_align(ui_zhuce, LV_ALIGN_CENTER);
DBG_PRINT();
    ui_loginpng1 = lv_img_create(ui_LRContainer);
    lv_img_set_src(ui_loginpng1, &ui_img_style1_png);
    lv_obj_set_width(ui_loginpng1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_loginpng1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_loginpng1, 0);
    lv_obj_set_y(ui_loginpng1, -297);
    lv_obj_set_align(ui_loginpng1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_loginpng1, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_loginpng1, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_img_set_zoom(ui_loginpng1, 380);
DBG_PRINT();
    ui_loginJINGAO = lv_label_create(ui_LRContainer);
    lv_obj_set_width(ui_loginJINGAO, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_loginJINGAO, LV_SIZE_CONTENT); /// 1
    lv_obj_set_y(ui_loginJINGAO, -295);
    lv_obj_set_align(ui_loginJINGAO, LV_ALIGN_CENTER);
    lv_label_set_text(ui_loginJINGAO, "低声交流");
DBG_PRINT();
    lv_obj_set_style_text_color(ui_loginJINGAO, lv_color_hex(0x9400F7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_loginJINGAO, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_loginJINGAO, &ui_font_CHINESEsize25, LV_PART_MAIN | LV_STATE_DEFAULT);
DBG_PRINT();
    ui_jianpanX = lv_obj_create(ui_LoginRegisteWin);
    lv_obj_remove_style_all(ui_jianpanX);
    lv_obj_set_width(ui_jianpanX, 624);
    lv_obj_set_height(ui_jianpanX, 368);
    lv_obj_set_x(ui_jianpanX, 163);
    lv_obj_set_y(ui_jianpanX, -106);
    lv_obj_set_align(ui_jianpanX, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_jianpanX, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags
DBG_PRINT();
    ui_jianpanPanel = lv_obj_create(ui_LoginRegisteWin);
    lv_obj_set_width(ui_jianpanPanel, 665);
    lv_obj_set_height(ui_jianpanPanel, 296);
    lv_obj_set_x(ui_jianpanPanel, -174);
    lv_obj_set_y(ui_jianpanPanel, 182);
    lv_obj_set_align(ui_jianpanPanel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_jianpanPanel, LV_OBJ_FLAG_HIDDEN);       /// Flags
    lv_obj_clear_flag(ui_jianpanPanel, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_jianpanPanel, lv_color_hex(0xD27AFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_jianpanPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
DBG_PRINT();
    ui_jianpan = lv_keyboard_create(ui_jianpanPanel);
    lv_obj_set_width(ui_jianpan, 612);
    lv_obj_set_height(ui_jianpan, 190);
    lv_obj_set_x(ui_jianpan, -2);
    lv_obj_set_y(ui_jianpan, 17);
    lv_obj_set_align(ui_jianpan, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_jianpan, LV_OBJ_FLAG_PRESS_LOCK); /// Flags
DBG_PRINT();
    ui_MSGbg = lv_img_create(ui_jianpanPanel);
    lv_img_set_src(ui_MSGbg, &ui_img_style1_png);
    lv_obj_set_width(ui_MSGbg, LV_SIZE_CONTENT);  /// 150
    lv_obj_set_height(ui_MSGbg, LV_SIZE_CONTENT); /// 33
    lv_obj_set_x(ui_MSGbg, -166);
    lv_obj_set_y(ui_MSGbg, -117);
    lv_obj_set_align(ui_MSGbg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MSGbg, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_MSGbg, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_img_set_zoom(ui_MSGbg, 500);
DBG_PRINT();
    ui_jianpanLabel = lv_label_create(ui_MSGbg);
    lv_obj_set_width(ui_jianpanLabel, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_jianpanLabel, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_jianpanLabel, 0);
    lv_obj_set_y(ui_jianpanLabel, 5);
    lv_obj_set_align(ui_jianpanLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_jianpanLabel, "专用键盘");
    lv_obj_set_style_text_color(ui_jianpanLabel, lv_color_hex(0x422EFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_jianpanLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_jianpanLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_jianpanLabel, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_jianpanLabel, &ui_font_CHINESEsize25, LV_PART_MAIN | LV_STATE_DEFAULT);
DBG_PRINT();
    ui_TextdocID = lv_textarea_create(ui_jianpanPanel);
    lv_obj_set_width(ui_TextdocID, 224);
    lv_obj_set_height(ui_TextdocID, LV_SIZE_CONTENT); /// 45
    lv_obj_set_x(ui_TextdocID, 182);
    lv_obj_set_y(ui_TextdocID, -111);
    lv_obj_set_align(ui_TextdocID, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextdocID, "输入医生编号");
    lv_textarea_set_one_line(ui_TextdocID, true);
    lv_obj_add_flag(ui_TextdocID, LV_OBJ_FLAG_HIDDEN); /// Flags
    lv_obj_set_style_text_color(ui_TextdocID, lv_color_hex(0x3D00FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextdocID, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextdocID, &ui_font_CHINESEsize25, LV_PART_MAIN | LV_STATE_DEFAULT);
DBG_PRINT();
    lv_obj_add_event_cb(ui_TextdocID, ui_event_TextdocIDText, LV_EVENT_CLICKED, NULL);DBG_PRINT();
    lv_obj_add_event_cb(ui_usernameText, ui_event_usernameText, LV_EVENT_CLICKED, NULL);DBG_PRINT();
    lv_obj_add_event_cb(ui_mmText_, ui_event_mmText_, LV_EVENT_CLICKED, NULL);DBG_PRINT();
    lv_obj_add_event_cb(ui_mmX, ui_event_mmX, LV_EVENT_CLICKED, NULL);DBG_PRINT();
    lv_obj_add_event_cb(ui_mmY, ui_event_mmY, LV_EVENT_CLICKED, NULL);DBG_PRINT();
    lv_obj_add_event_cb(ui_userIDcardText_, ui_event_userIDcardText_, LV_EVENT_CLICKED, NULL);DBG_PRINT();
    lv_obj_add_event_cb(ui_shenfen, ui_event_shenfen, LV_EVENT_VALUE_CHANGED, NULL);DBG_PRINT();
    lv_obj_add_event_cb(ui_shenfenChange, ui_event_shenfenChange, LV_EVENT_CLICKED, NULL);DBG_PRINT();
    lv_obj_add_event_cb(ui_zhuce, ui_event_zhuce, LV_EVENT_CLICKED, NULL);DBG_PRINT();
    lv_obj_add_event_cb(ui_jianpanX, ui_event_jianpanX, LV_EVENT_CLICKED, NULL);DBG_PRINT();
    lv_obj_add_event_cb(ui_denglu, ui_event_denglu_click, LV_EVENT_CLICKED, NULL);DBG_PRINT();
    lv_keyboard_set_textarea(ui_jianpan, ui_mmText_);DBG_PRINT();
   DBG_MSG("ui_LoginRegisteWin_screen_init结束初始化");
}
